<?php
/**
 * WoltLab Suite
 * Template: firstTimeSetupCompleted
 * Compiled at: Thu, 08 Jan 2026 08:26:36 +0000
 * 
 * DO NOT EDIT THIS FILE
 */
$this->v['tpl']['template'] = 'firstTimeSetupCompleted';
?>
<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin'] = new wcf\system\template\plugin\IconFunctionTemplatePlugin;
}
?><?php
$this->v['pageTitle'] = 'wcf.acp.firstTimeSetup.completed';

?><?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin'] = new wcf\system\template\plugin\LanguageModifierTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'] = new wcf\system\template\plugin\PhraseModifierTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin'] = new wcf\system\template\plugin\JsFunctionTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'] = new wcf\system\template\plugin\EncodeJSModifierTemplatePlugin;
}
?><!DOCTYPE html>
<html
	dir="<?=$this->v['__wcf']->getLanguage()->getPageDirection();?>"
	lang="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getLanguage()->getBcp47());?>"
	data-color-scheme="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getColorScheme());?>"
>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex">
	<title><?php if (isset($this->v['pageTitle'])) { ?><?=$this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin']->execute([$this->v['pageTitle']], $this);?> - <?php } ?>Administrationsoberfläche<?php if (PACKAGE_ID) { ?> - <?=wcf\util\StringUtil::encodeHTML($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin']->execute([PAGE_TITLE], $this));?><?php } ?></title>
	
	
	<style>ol, ul { list-style: none; }</style>
	
	<!-- Stylesheets -->
	<?=$this->v['__wcf']->getStyleHandler()->getStylesheet(true);?>
	
	
	<!-- Icons -->
	<?php if (PACKAGE_ID && $this->v['__wcf']->getStyleHandler()->getDefaultStyle()) { ?>
		<link rel="apple-touch-icon" sizes="180x180" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconAppleTouchIcon());?>">
		<link rel="manifest" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconManifest());?>">
		<link rel="icon" type="image/png" sizes="48x48" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFavicon());?>">
		<meta name="msapplication-config" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconBrowserconfig());?>">
	<?php } else { ?>	
		<link rel="apple-touch-icon" sizes="180x180" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.apple-touch-icon.png">
		<link rel="manifest" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.manifest.json">
		<link rel="icon" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.favicon.ico">
		<meta name="msapplication-config" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.browserconfig.xml">
	<?php } ?>
	<script data-eager="true">
	{
		<?php if ($this->v['__wcf']->getStyleHandler()->getColorScheme() === 'system') { ?>
		{
			const colorScheme = matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
			document.documentElement.dataset.colorScheme = colorScheme;
		}
		<?php } ?>
		
		const themeColor = document.createElement("meta");
		themeColor.name = "theme-color";
		themeColor.content = window.getComputedStyle(document.documentElement).getPropertyValue("--wcfHeaderBackground");
		document.currentScript.replaceWith(themeColor);
	}
	</script>

	<meta name="timezone" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->user->getTimeZone()->getName());?>">
	
	<script data-eager="true">
		var WCF_PATH = '<?=$this->v['__wcf']->getPath();?>';
		var WSC_API_URL = '<?=$this->v['__wcf']->getPath();?>acp/';
		var WSC_RPC_API_URL = '<?php $this->tagStack[] = ['link', ['controller' => "Api", 'forceFrontend' => true, 'id' => "rpc"]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
		
		var LANGUAGE_ID = <?=$this->v['__wcf']->getLanguage()->languageID;?>;
		var LANGUAGE_USE_INFORMAL_VARIANT = <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>true<?php } else { ?>false<?php } ?>;
		var TIME_NOW = <?=TIME_NOW;?>;
		var LAST_UPDATE_TIME = <?=LAST_UPDATE_TIME;?>;
		var ENABLE_DEBUG_MODE = <?php if (ENABLE_DEBUG_MODE) { ?>true<?php } else { ?>false<?php } ?>;
		var ENABLE_PRODUCTION_DEBUG_MODE = <?php if (ENABLE_PRODUCTION_DEBUG_MODE) { ?>true<?php } else { ?>false<?php } ?>;
		var ENABLE_DEVELOPER_TOOLS = <?php if (ENABLE_DEVELOPER_TOOLS) { ?>true<?php } else { ?>false<?php } ?>;
		
		
		
		var COMPILER_TARGET_DEFAULT = true;
	</script>

	<script data-eager="true" src="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>js/WoltLabSuite/WebComponent.min.js?v=<?=LAST_UPDATE_TIME;?>"></script>
	<script data-eager="true" src="<?=wcf\util\StringUtil::encodeHTML($this->v['phrasePreloader']->getUrl($this->v['__wcf']->language));?>"></script>
	
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require.config', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require.linearExecution', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'wcf.globalHelper', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => '3rdParty/tslib', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<script>
		requirejs.config({
			baseUrl: '<?=$this->v['__wcf']->getPath();?>js',
			urlArgs: 't=<?=LAST_UPDATE_TIME;?>'
			<?php ob_start(); ?><?php
$this->v['tpl']['capture']['default'] = ob_get_clean();
$this->assign('hascontent_14b551e7b1f66d6d243a23953e39ccd6ab237b80', $this->v['tpl']['capture']['default']);
?>
<?php $this->assign('hascontent_14b551e7b1f66d6d243a23953e39ccd6ab237b80', trim($this->v['hascontent_14b551e7b1f66d6d243a23953e39ccd6ab237b80'])); ?>
<?php if ($this->v['hascontent_14b551e7b1f66d6d243a23953e39ccd6ab237b80']) { ?>
			, paths: {
				<?=$this->v['hascontent_14b551e7b1f66d6d243a23953e39ccd6ab237b80'];?>

			}
			<?php } ?>

		});
		
	</script>
	<script>
		require(['Language', 'WoltLabSuite/Core/Acp/Bootstrap', 'User'], function(Language, AcpBootstrap, User) {
			Language.addObject({
				'wcf.acp.search.noResults': 'Keine Treffer',

				
			});
			
			User.init(
				<?=$this->v['__wcf']->user->userID;?>,
				<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->username], $this);?>'<?php } else { ?>''<?php } ?>,
				<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->getLink()], $this);?>'<?php } else { ?>''<?php } ?>
			);
			
			AcpBootstrap.setup({
				bootstrap: {
					dynamicColorScheme: <?php if ($this->v['__wcf']->getStyleHandler()->getColorScheme() === 'system') { ?>true<?php } else { ?>false<?php } ?>,
					enableMobileMenu: <?php if (PACKAGE_ID && empty($this->v['__isLogin'])) { ?>true<?php } else { ?>false<?php } ?>,
				}
			});
		});
	</script>
	
	<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'] = new wcf\system\template\plugin\EncodeJSModifierTemplatePlugin;
}
?><?php if (ENABLE_DEBUG_MODE && ENABLE_DEVELOPER_TOOLS && $this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
	<script data-relocate="true">
		require(['Ajax', 'WoltLabSuite/Core/Language/Chooser'], function(Ajax, LanguageChooser) {
			var item = elCreate('li');
			item.id = 'pageLanguageContainer';
			var userPanelItems = elBySel('.userPanelItems');
			userPanelItems.insertBefore(item, userPanelItems.firstChild);
			
			var languages = {
				<?php
$_length3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6 = count($this->v['__wcf']->getLanguage()->getLanguages());
$_i3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6 = 0;
$_item3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6 = $this->v['_language'] ?? null;
$_key3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6 =  null;
foreach ($this->v['__wcf']->getLanguage()->getLanguages() as $this->v['_language']) { ?>
				'<?=$this->v['_language']->languageID;?>': {
					iconPath: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']->getIconPath()], $this);?>',
					languageName: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']], $this);?>',
					languageCode: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']->languageCode], $this);?>'
				}
				<?php
if (++$_i3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6 < $_length3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6) { echo ', '; }
}
unset($this->v['_language']);$this->v['_language'] = $_item3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6;
unset($_length3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6, $_i3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6);
unset($_item3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6, $_key3b95da0fb0dfe73e4b95224a89d5821edaf9e9a6);
?>
			};
			
			var callback = function(listItem) {
				Ajax.apiOnce({
					data: {
						actionName: 'devtoolsSetLanguage',
						className: 'wcf\\data\\user\\UserAction',
						parameters: {
							languageID: elData(listItem, 'language-id')
						}
					},
					success: function() {
						window.location.reload();
					}
				});
			};
			
			LanguageChooser.init('pageLanguageContainer', 'pageLanguageID', <?=$this->v['__wcf']->getLanguage()->languageID;?>, languages, callback);
		});
	</script>
<?php } ?>
	
	<script>
		// prevent jQuery and other libraries from utilizing define()
		__require_define_amd = define.amd;
		define.amd = undefined;
	</script>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui', 'file' => 'touchPunch', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui', 'file' => 'nestedSortable', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Assets', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'acp' => 'true', 'file' => 'WCF.ACP'], $this);?>
	<script>
		define.amd = __require_define_amd;
		$.holdReady(true);
		WCF.User.init(
			<?=$this->v['__wcf']->user->userID;?>,
			<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->username], $this);?>'<?php } else { ?>''<?php } ?>
		);
	</script>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Message', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Label', 'bundle' => 'WCF.Combined'], $this);?>
	<script>
		$(function() {
			if (jQuery.browser.touch) $('html').addClass('touch');
			
			<?php if ($this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
				new WCF.ACP.Search();
			<?php } ?>
			
			
			
			$('form[method=get]').attr('method', 'post');
			
			// rewrites legacy links using the `dereferrer.php` service
			// see https://github.com/WoltLab/WCF/issues/2557
			elBySelAll('a', undefined, function(link) {
				if (/\/dereferrer.php$/.test(link.pathname) && link.search.match(/^\?url=([^&=]+)$/)) {
					link.href = unescape(RegExp.$1);
				}
				
				if (link.classList.contains('externalURL')) {
					var rel = (link.rel === '') ? [] : link.rel.split(' ');
					if (rel.indexOf('noopener') === -1) rel.push('noopener');
					
					link.rel = rel.join(' ');
				}
			});
			
			WCF.DOMNodeInsertedHandler.execute();
		});
	</script>
	
	
	<?php if ( ! empty($this->v['headContent'])) { ?>
		<?=$this->v['headContent'];?>
	<?php } ?>
</head>

<body id="tpl<?=wcf\util\StringUtil::encodeHTML(ucfirst($this->v['templateName']));?>" data-template="<?=wcf\util\StringUtil::encodeHTML($this->v['templateName']);?>" data-application="<?=wcf\util\StringUtil::encodeHTML($this->v['templateNameApplication']);?>" class="wcfAcp<?php if ( ! empty($this->v['__isLogin'])) { ?> acpAuthFlow<?php } ?>">
	<span id="top"></span>
	
	<?php $this->assign('_acpPageSubMenuActive', false); ?>
	<?php if (PACKAGE_ID) { ?>
		<?php $this->assign('_activeMenuItems', $this->v['__wcf']->getACPMenu()->getActiveMenuItems()); ?>
		<?php
$_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['abf196d0476836cfa9062a70a8572d2dfadeb9d8'] = [];
$this->foreachVars['abf196d0476836cfa9062a70a8572d2dfadeb9d8']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8) && count($_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8) > 0) || (!is_countable($_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8) && $_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8)) {
foreach ($_foreach_abf196d0476836cfa9062a70a8572d2dfadeb9d8 as $this->v['_sectionMenuItem']) {
?>
			<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?><?php $this->assign('_acpPageSubMenuActive', true); ?><?php } ?>
		<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['abf196d0476836cfa9062a70a8572d2dfadeb9d8']['item'];
unset($this->foreachVars['abf196d0476836cfa9062a70a8572d2dfadeb9d8']);
 } ?>
	<?php } ?>
	<div id="pageContainer" class="pageContainer<?php if ( ! PACKAGE_ID ||  ! $this->v['__wcf']->user->userID ||  ! empty($this->v['__isLogin'])) { ?> acpPageHiddenMenu<?php } elseif ($this->v['_acpPageSubMenuActive']) { ?> acpPageSubMenuActive<?php } ?>">
		
		
		<div class="pageHeaderContainer<?php if ( ! empty($this->v['__isLogin'])) { ?> pageHeaderContainerIsLogin<?php } ?>">
	<header id="pageHeader" class="pageHeader">
		<div id="pageHeaderPanel" class="pageHeaderPanel">
			<div class="layoutBoundary">
				<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
?><div
	id="pageHeaderLogo"
	class="
		pageHeaderLogo
		<?php if (ENABLE_DEBUG_MODE) { ?> pageHeaderLogo--debug<?php } ?>
		<?php if (ENABLE_DEVELOPER_TOOLS) { ?> pageHeaderLogo--dev<?php } ?>
	"
>
	<a href="<?php $this->tagStack[] = ['link', []];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">
		<img src="<?=$this->v['__wcf']->getPath();?>acp/images/woltlabSuite.png" alt="" width="562" height="80" loading="eager" class="pageHeaderLogoLarge">
		<img src="<?=$this->v['__wcf']->getPath();?>acp/images/woltlabSuite-small.png" alt="" width="55" height="30" loading="eager" class="pageHeaderLogoSmall">
	</a>
</div>
				
				
				<?php if (empty($this->v['__isLogin'])) { ?>
					<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
?><nav id="topMenu" class="userPanel">
	<ul class="userPanelItems">
		<?php if ($this->v['__wcf']->user->userID) { ?>
			<?php if (PACKAGE_ID) { ?>
				<li id="userMenu" class="dropdown">
					<a href="#" class="dropdownToggle jsTooltip" title="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->user->username);?>"><?=$this->v['__wcf']->getUserProfileHandler()->getAvatar()->getImageTag(24);?></a>
					<ul class="dropdownMenu dropdownMenuUserPanel" data-dropdown-alignment-horizontal="right">
						<li><a href="<?php $this->tagStack[] = ['link', ['controller' => 'Logout']];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?>t=<?=rawurlencode($this->v['__wcf']->session->getSecurityToken());?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Abmelden</a></li>
					</ul>
				</li>
				
				<li id="jumpToPage">
					<a href="<?php $this->tagStack[] = ['link', ['forceFrontend' => true]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="jsTooltip" title="Zur Seite">
						<fa-icon size="16" name="house"></fa-icon>
						<fa-icon size="32" name="house"></fa-icon>
					</a>
				</li>
				
				<?php if ($this->v['__wcf']->session->getPermission('admin.configuration.package.canUpdatePackage') && $this->v['__wcf']->getAvailableUpdates()) { ?>
					<li id="outstandingUpdatesNotification">
						<a href="<?php $this->tagStack[] = ['link', ['controller' => 'PackageList', 'searchForUpdates' => true]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="jsTooltip" title="Aktualisierungen">
							<fa-icon size="16" name="arrows-rotate"></fa-icon>
							<fa-icon size="32" name="arrows-rotate"></fa-icon>
							<span class="badge badgeUpdate"><?=wcf\util\StringUtil::formatNumeric((float)$this->v['__wcf']->getAvailableUpdates());?></span>
						</a>
					</li>
				<?php } ?>
			<?php } ?>
			
			<li id="woltlab" class="dropdown">
				<a href="#" class="dropdownToggle jsTooltip" title="WoltLab&reg;">
					<fa-icon size="16" name="info"></fa-icon>
					<fa-icon size="32" name="info"></fa-icon>
				</a>
				
				<ul class="dropdownMenu dropdownMenuUserPanel" data-dropdown-alignment-horizontal="right">
					<li><a class="externalURL" href="https://www.woltlab.com/<?php if ($this->v['__wcf']->getLanguage()->getFixedLanguageCode() === 'de') { ?>de/<?php } ?>"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Website</a></li>
					<li><a class="externalURL" href="https://manual.woltlab.com/<?php if ($this->v['__wcf']->getLanguage()->getFixedLanguageCode() === 'de') { ?>de<?php } else { ?>en<?php } ?>/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Handbuch</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/community/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Supportforum</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/ticket-add/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Ticket-Support</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/pluginstore/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Plugin-Store</a></li>
				</ul>
			</li>
		<?php } ?>
		
		
	</ul>
</nav>
					
					<div id="mainMenu" class="mainMenu">
	<!-- Placeholder for the mobile UI. -->
</div>
<button type="button" class="pageHeaderMenuMobile" aria-expanded="false" aria-label="Menü">
	<span class="pageHeaderMenuMobileInactive">
		<fa-icon size="32" name="bars"></fa-icon>
	</span>
	<span class="pageHeaderMenuMobileActive">
		<fa-icon size="32" name="xmark"></fa-icon>
	</span>
</button>
					
					<button type="button" id="pageHeaderSearchMobile" class="pageHeaderSearchMobile" aria-expanded="false" aria-label="Suche">
	<fa-icon size="32" name="magnifying-glass"></fa-icon>
</button>

<div id="pageHeaderSearch" class="pageHeaderSearch" data-disable-auto-focus="true">
	<div class="pageHeaderSearchInputContainer">
		<div id="pageHeaderSearchType" class="pageHeaderSearchType dropdown">
			<a href="#" class="button dropdownToggle" id="pageHeaderSearchTypeSelect">
				<span class="pageHeaderSearchTypeLabel">Alles</span>
				<fa-icon size="16" name="caret-down" solid></fa-icon>
			</a>
			<ul class="dropdownMenu">
				<li><a href="#" data-provider-name="everywhere">Alles</a></li>
				<li class="dropdownDivider"></li>
				
				<?php
$_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595 = $this->v['availableAcpSearchProviders'];
$this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595'] = [];
$this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595']['item'] = $this->v['availableAcpSearchProviderLabel'] ?? null;
if ((is_countable($_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595) && count($_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595) > 0) || (!is_countable($_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595) && $_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595)) {
$this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595']['key'] = $this->v['availableAcpSearchProviderName'] ?? null;
foreach ($_foreach_1cb92b74dc389ffcffc076586a276d4f0cd5c595 as $this->v['availableAcpSearchProviderName'] => $this->v['availableAcpSearchProviderLabel']) {
?>
					<li><a href="#" data-provider-name="<?=$this->v['availableAcpSearchProviderName'];?>"><?=$this->v['availableAcpSearchProviderLabel'];?></a></li>
				<?php }
unset($this->v['availableAcpSearchProviderLabel']);$this->v['availableAcpSearchProviderLabel'] = $this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595']['item'];
unset($this->v['availableAcpSearchProviderName']);if (array_key_exists('key', $this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595'])) {
$this->v['availableAcpSearchProviderName'] = $this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595']['key'];
}
unset($this->foreachVars['1cb92b74dc389ffcffc076586a276d4f0cd5c595']);
 } ?>
			</ul>
		</div>
		
		<input type="search" name="q" id="pageHeaderSearchInput" class="pageHeaderSearchInput" placeholder="Suchbegriff eingeben" autocomplete="off" required value="" data-toggle="search">

		<span class="pageHeaderSearchShortcut" aria-hidden="true">S</span>
		
		<button type="button" class="button pageHeaderSearchInputButton" type="submit" title="Suche">
			<fa-icon size="16" name="magnifying-glass"></fa-icon>
		</button>
	</div>
</div>
				<?php } ?>
			</div>
		</div>
	</header>
</div>
		
		
		
		<div id="acpPageContentContainer" class="acpPageContentContainer">
			<?php if (PACKAGE_ID && $this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
	<?php $this->assign('_activeMenuItems', $this->v['__wcf']->getACPMenu()->getActiveMenuItems()); ?>
	
	<nav id="acpPageMenu" class="acpPageMenu">
		<ol class="acpPageMenuList">
			<?php
$_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['3ec834a26ae9eda6c93d637e1419a9ad377513a1'] = [];
$this->foreachVars['3ec834a26ae9eda6c93d637e1419a9ad377513a1']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1) && count($_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1) > 0) || (!is_countable($_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1) && $_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1)) {
foreach ($_foreach_3ec834a26ae9eda6c93d637e1419a9ad377513a1 as $this->v['_sectionMenuItem']) {
?>
				<li>
					<button type="button" class="acpPageMenuLink<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" data-menu-item="<?=wcf\util\StringUtil::encodeHTML($this->v['_sectionMenuItem']->menuItem);?>">
						<?=$this->v['_sectionMenuItem']->getIcon()->toHtml(32);?>
						<span class="acpPageMenuItemLabel"><?=$this->v['_sectionMenuItem'];?></span>
					</button>
				</li>
			<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['3ec834a26ae9eda6c93d637e1419a9ad377513a1']['item'];
unset($this->foreachVars['3ec834a26ae9eda6c93d637e1419a9ad377513a1']);
 } ?>
		</ol>
	</nav>
	
	<nav id="acpPageSubMenu" class="acpPageSubMenu">
		<?php
$_foreach_f838b23e37da9626a334e773bba403bc882b6aa5 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['f838b23e37da9626a334e773bba403bc882b6aa5'] = [];
$this->foreachVars['f838b23e37da9626a334e773bba403bc882b6aa5']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_f838b23e37da9626a334e773bba403bc882b6aa5) && count($_foreach_f838b23e37da9626a334e773bba403bc882b6aa5) > 0) || (!is_countable($_foreach_f838b23e37da9626a334e773bba403bc882b6aa5) && $_foreach_f838b23e37da9626a334e773bba403bc882b6aa5)) {
foreach ($_foreach_f838b23e37da9626a334e773bba403bc882b6aa5 as $this->v['_sectionMenuItem']) {
?>
			<ol class="acpPageSubMenuCategoryList<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" data-menu-item="<?=wcf\util\StringUtil::encodeHTML($this->v['_sectionMenuItem']->menuItem);?>">
				<?php
$_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb = $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_sectionMenuItem']->menuItem);
$this->foreachVars['0aa35527d75b5a0b97d95aee62c440386d0338fb'] = [];
$this->foreachVars['0aa35527d75b5a0b97d95aee62c440386d0338fb']['item'] = $this->v['_menuItemCategory'] ?? null;
if ((is_countable($_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb) && count($_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb) > 0) || (!is_countable($_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb) && $_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb)) {
foreach ($_foreach_0aa35527d75b5a0b97d95aee62c440386d0338fb as $this->v['_menuItemCategory']) {
?>
					<li class="acpPageSubMenuCategory">
						<span><?=$this->v['_menuItemCategory'];?></span>
						
						<ol class="acpPageSubMenuItemList">
							<?php
$_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118 = $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_menuItemCategory']->menuItem);
$this->foreachVars['36f665ac15fb75f0df310bd5b7e6e9914be51118'] = [];
$this->foreachVars['36f665ac15fb75f0df310bd5b7e6e9914be51118']['item'] = $this->v['_menuItem'] ?? null;
if ((is_countable($_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118) && count($_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118) > 0) || (!is_countable($_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118) && $_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118)) {
foreach ($_foreach_36f665ac15fb75f0df310bd5b7e6e9914be51118 as $this->v['_menuItem']) {
?>
								<?php $this->assign('_subMenuItems', $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_menuItem']->menuItem)); ?>
								
								<?php if (empty($this->v['_subMenuItems'])) { ?>
									<li<?php if (in_array($this->v['_menuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> class="active"<?php } ?>><a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_menuItem']->getLink());?>" class="acpPageSubMenuLink"><?=$this->v['_menuItem'];?></a></li>
								<?php } else { ?>
									<?php if ($this->v['_menuItem']->menuItem === 'wcf.acp.menu.link.option.category') { ?>
										
										<?php
$_foreach_ce6c6b4c75d03a9580c61741160caef282f00276 = $this->v['_subMenuItems'];
$this->foreachVars['ce6c6b4c75d03a9580c61741160caef282f00276'] = [];
$this->foreachVars['ce6c6b4c75d03a9580c61741160caef282f00276']['item'] = $this->v['_subMenuItem'] ?? null;
if ((is_countable($_foreach_ce6c6b4c75d03a9580c61741160caef282f00276) && count($_foreach_ce6c6b4c75d03a9580c61741160caef282f00276) > 0) || (!is_countable($_foreach_ce6c6b4c75d03a9580c61741160caef282f00276) && $_foreach_ce6c6b4c75d03a9580c61741160caef282f00276)) {
foreach ($_foreach_ce6c6b4c75d03a9580c61741160caef282f00276 as $this->v['_subMenuItem']) {
?>
											<li<?php if (in_array($this->v['_subMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> class="active"<?php } ?>><a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_subMenuItem']->getLink());?>" class="acpPageSubMenuLink"><?=$this->v['_subMenuItem'];?></a></li>
										<?php }
unset($this->v['_subMenuItem']);$this->v['_subMenuItem'] = $this->foreachVars['ce6c6b4c75d03a9580c61741160caef282f00276']['item'];
unset($this->foreachVars['ce6c6b4c75d03a9580c61741160caef282f00276']);
 } ?>
									<?php } else { ?>
										<li class="acpPageSubMenuLinkWrapper">
											<a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_menuItem']->getLink());?>" class="acpPageSubMenuLink<?php if (in_array($this->v['_menuItem']->menuItem,$this->v['_activeMenuItems']) && $this->v['_activeMenuItems'][0] === $this->v['_menuItem']->menuItem) { ?> active<?php } ?>"><?=$this->v['_menuItem'];?></a>
											
											<?php
$_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c = $this->v['_subMenuItems'];
$this->foreachVars['db4d8d3c254ddd5838580650c3eb9605b509397c'] = [];
$this->foreachVars['db4d8d3c254ddd5838580650c3eb9605b509397c']['item'] = $this->v['_subMenuItem'] ?? null;
if ((is_countable($_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c) && count($_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c) > 0) || (!is_countable($_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c) && $_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c)) {
foreach ($_foreach_db4d8d3c254ddd5838580650c3eb9605b509397c as $this->v['_subMenuItem']) {
?>
												<a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_subMenuItem']->getLink());?>" class="acpPageSubMenuIcon jsTooltip<?php if (in_array($this->v['_subMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" title="<?=$this->v['_subMenuItem'];?>">
													<?=$this->v['_subMenuItem']->getIcon()->toHtml();?>
												</a>
											<?php }
unset($this->v['_subMenuItem']);$this->v['_subMenuItem'] = $this->foreachVars['db4d8d3c254ddd5838580650c3eb9605b509397c']['item'];
unset($this->foreachVars['db4d8d3c254ddd5838580650c3eb9605b509397c']);
 } ?>
										</li>
									<?php } ?>
								<?php } ?>
							<?php }
unset($this->v['_menuItem']);$this->v['_menuItem'] = $this->foreachVars['36f665ac15fb75f0df310bd5b7e6e9914be51118']['item'];
unset($this->foreachVars['36f665ac15fb75f0df310bd5b7e6e9914be51118']);
 } ?>
						</ol>
					</li>
				<?php }
unset($this->v['_menuItemCategory']);$this->v['_menuItemCategory'] = $this->foreachVars['0aa35527d75b5a0b97d95aee62c440386d0338fb']['item'];
unset($this->foreachVars['0aa35527d75b5a0b97d95aee62c440386d0338fb']);
 } ?>
			</ol>
		<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['f838b23e37da9626a334e773bba403bc882b6aa5']['item'];
unset($this->foreachVars['f838b23e37da9626a334e773bba403bc882b6aa5']);
 } ?>
	</nav>
<?php } ?>
			
			<section id="main" class="main" role="main">
				<div class="layoutBoundary">
					<div id="content" class="content">

<header class="contentHeader">
	<div class="contentHeaderTitle">
		<h1 class="contentTitle">Erstmalige Einrichtung abgeschlossen</h1>
	</div>
	
	<?php ob_start(); ?>
					<li><a href="<?php $this->tagStack[] = ['link', []];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="button"><fa-icon size="16" name="house"></fa-icon> <span>Administrationsoberfläche</span></a></li>
					
					
				<?php
$this->v['tpl']['capture']['default'] = ob_get_clean();
$this->assign('hascontent_6a87519540bd54f48f44b81f6818ad9935844322', $this->v['tpl']['capture']['default']);
?>
<?php $this->assign('hascontent_6a87519540bd54f48f44b81f6818ad9935844322', trim($this->v['hascontent_6a87519540bd54f48f44b81f6818ad9935844322'])); ?>
<?php if ($this->v['hascontent_6a87519540bd54f48f44b81f6818ad9935844322']) { ?>
		<nav class="contentHeaderNavigation">
			<ul>
				<?=$this->v['hascontent_6a87519540bd54f48f44b81f6818ad9935844322'];?>

			</ul>
		</nav>
	<?php } ?>

</header>

<section class="firstTimeSetup__section section">
	<h2 class="firstTimeSetup__title sectionTitle">
		Die nächsten Schritte
	</h2>

	<div class="firstTimeSetup__nextSteps">
		<div class="firstTimeSetup__nextStep">
			<div class="firstTimeSetup__nextStep__icon">
				<?=$this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin']->execute(['name' => 'plus', 'size' => 64], $this);?>
			</div>
			<div class="firstTimeSetup__nextStep__content">
				<h3 class="firstTimeSetup__nextStep__title">
					<a href="<?php $this->tagStack[] = ['link', ['controller' => 'License']];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">
						WoltLab Apps und Erweiterungen installieren
					</a>
				</h3>
				<p class="firstTimeSetup__nextStep__description">
					Erweitern Sie Ihre Community um offizielle Apps und Erweiterungen von WoltLab. Mit wenigen Klicks können Sie Ihre Community um ein Forum, Kalender, Galerie, Blog oder Dateiverwaltung erweitern.
				</p>
			</div>
		</div>
		<div class="firstTimeSetup__nextStep">
			<div class="firstTimeSetup__nextStep__icon">
				<?=$this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin']->execute(['name' => 'book', 'size' => 64], $this);?>
			</div>
			<div class="firstTimeSetup__nextStep__content">
				<h3 class="firstTimeSetup__nextStep__title">
					<a href="https://manual.woltlab.com/<?php if ($this->v['__wcf']->language->getFixedLanguageCode() === 'de') { ?>de<?php } else { ?>en<?php } ?>/" class="externalURL">
						Handbuch für WoltLab Suite
					</a>
				</h3>
				<p class="firstTimeSetup__nextStep__description">
					Im Handbuch finden Sie hilfreiche Anleitungen und Beschreibungen der verschiedenen Funktionen von WoltLab Suite.
				</p>
			</div>
		</div>
		<div class="firstTimeSetup__nextStep">
			<div class="firstTimeSetup__nextStep__icon">
				<?=$this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin']->execute(['name' => 'plug', 'size' => 64], $this);?>
			</div>
			<div class="firstTimeSetup__nextStep__content">
				<h3 class="firstTimeSetup__nextStep__title">
					<a href="https://www.woltlab.com/pluginstore/" class="externalURL">
						Erweiterungen und Stile im Plugin-Store
					</a>
				</h3>
				<p class="firstTimeSetup__nextStep__description">
					Im offiziellen Plugin-Store finden Sie viele nützliche Erweiterungen, um Ihre Seite auf Ihre Bedürfnisse zuzuschneiden. Alle angebotenen Erweiterungen werden vorab von WoltLab auf Sicherheit und Stabilität geprüft.
				</p>
			</div>
		</div>
		<div class="firstTimeSetup__nextStep">
			<div class="firstTimeSetup__nextStep__icon">
				<?=$this->pluginObjects['wcf\system\template\plugin\IconFunctionTemplatePlugin']->execute(['name' => 'circle-question', 'size' => 64], $this);?>
			</div>
			<div class="firstTimeSetup__nextStep__content">
				<h3 class="firstTimeSetup__nextStep__title">
					<a href="https://www.woltlab.com/ticket-add/" class="externalURL">
						Ticket-Support für Fragen und Probleme
					</a>
				</h3>
				<p class="firstTimeSetup__nextStep__description">
					Sie haben Fragen zu einzelnen Funktionen oder haben Probleme bei der Einrichtung Ihrer Installation? Über das Ticket-System im Kundenbereich erhalten Sie Hilfestellung durch unsere Kundenbetreuung.
				</p>
			</div>
		</div>
	</div>
</section>

				</div>
			</div>
		</section>
	</div>
	
	<footer id="pageFooter" class="pageFooter">
	<?php if ( ! empty($this->v['errorField']) ||  ! empty($this->v['errorType'])) { ?>
		<!--
			DEBUG: FORM_VALIDATION_FAILED
			
			errorField: <?php if (empty($this->v['errorField'])) { ?>(empty)<?php } else { ?><?=wcf\util\StringUtil::encodeHTML(print_r($this->v['errorField'],true));?><?php } ?>
			
			errorType: <?php if (empty($this->v['errorType'])) { ?>(empty)<?php } else { ?><?=wcf\util\StringUtil::encodeHTML(print_r($this->v['errorType'],true));?><?php } ?>
		
		-->
	<?php } ?>
	
	<div id="pageFooterCopyright" class="pageFooterCopyright">
		<div class="layoutBoundary">
			

			<?php if (ENABLE_BENCHMARK) { ?><?php
$outerTemplateNamee46744f612241203352a732d6d46785df6499b4c = $this->v['tpl']['template'];
$this->includeTemplate('shared_benchmark', 'wcf', [], 1);
$this->v['tpl']['template'] = $outerTemplateNamee46744f612241203352a732d6d46785df6499b4c;
$this->v['tpl']['includedTemplates']['shared_benchmark'] = 1;
?><?php } ?>
			
			
			
			<div class="copyright"><a href="https://www.woltlab.com/de/" rel="nofollow"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank"<?php } ?>>Community-Software: <strong>WoltLab Suite&trade;<?php if (SHOW_VERSION_NUMBER) { ?> <?=WCF_VERSION;?><?php } ?></strong></a></div>
		</div>
	</div>
</footer>
</div>



<!-- <?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getRequestNonce('JAVASCRIPT_RELOCATE_POSITION'));?> -->

<span id="bottom"></span>

</body>
</html>