<?php
/**
 * WoltLab Suite
 * Template: firstTimeSetupOptionsEmail
 * Compiled at: Thu, 08 Jan 2026 08:26:35 +0000
 * 
 * DO NOT EDIT THIS FILE
 */
$this->v['tpl']['template'] = 'firstTimeSetupOptionsEmail';
?>
<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
?><?php
$this->v['pageTitle'] = 'wcf.acp.firstTimeSetup.optionsEmail';

?><?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin'] = new wcf\system\template\plugin\LanguageModifierTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'] = new wcf\system\template\plugin\PhraseModifierTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin'] = new wcf\system\template\plugin\JsFunctionTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'] = new wcf\system\template\plugin\EncodeJSModifierTemplatePlugin;
}
?><!DOCTYPE html>
<html
	dir="<?=$this->v['__wcf']->getLanguage()->getPageDirection();?>"
	lang="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getLanguage()->getBcp47());?>"
	data-color-scheme="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getColorScheme());?>"
>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="robots" content="noindex">
	<title><?php if (isset($this->v['pageTitle'])) { ?><?=$this->pluginObjects['wcf\system\template\plugin\LanguageModifierTemplatePlugin']->execute([$this->v['pageTitle']], $this);?> - <?php } ?>Administrationsoberfläche<?php if (PACKAGE_ID) { ?> - <?=wcf\util\StringUtil::encodeHTML($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin']->execute([PAGE_TITLE], $this));?><?php } ?></title>
	
	
	<style>ol, ul { list-style: none; }</style>
	
	<!-- Stylesheets -->
	<?=$this->v['__wcf']->getStyleHandler()->getStylesheet(true);?>
	
	
	<!-- Icons -->
	<?php if (PACKAGE_ID && $this->v['__wcf']->getStyleHandler()->getDefaultStyle()) { ?>
		<link rel="apple-touch-icon" sizes="180x180" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconAppleTouchIcon());?>">
		<link rel="manifest" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconManifest());?>">
		<link rel="icon" type="image/png" sizes="48x48" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFavicon());?>">
		<meta name="msapplication-config" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getStyleHandler()->getDefaultStyle()->getFaviconBrowserconfig());?>">
	<?php } else { ?>	
		<link rel="apple-touch-icon" sizes="180x180" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.apple-touch-icon.png">
		<link rel="manifest" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.manifest.json">
		<link rel="icon" href="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.favicon.ico">
		<meta name="msapplication-config" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>images/favicon/default.browserconfig.xml">
	<?php } ?>
	<script data-eager="true">
	{
		<?php if ($this->v['__wcf']->getStyleHandler()->getColorScheme() === 'system') { ?>
		{
			const colorScheme = matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
			document.documentElement.dataset.colorScheme = colorScheme;
		}
		<?php } ?>
		
		const themeColor = document.createElement("meta");
		themeColor.name = "theme-color";
		themeColor.content = window.getComputedStyle(document.documentElement).getPropertyValue("--wcfHeaderBackground");
		document.currentScript.replaceWith(themeColor);
	}
	</script>

	<meta name="timezone" content="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->user->getTimeZone()->getName());?>">
	
	<script data-eager="true">
		var WCF_PATH = '<?=$this->v['__wcf']->getPath();?>';
		var WSC_API_URL = '<?=$this->v['__wcf']->getPath();?>acp/';
		var WSC_RPC_API_URL = '<?php $this->tagStack[] = ['link', ['controller' => "Api", 'forceFrontend' => true, 'id' => "rpc"]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
		
		var LANGUAGE_ID = <?=$this->v['__wcf']->getLanguage()->languageID;?>;
		var LANGUAGE_USE_INFORMAL_VARIANT = <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>true<?php } else { ?>false<?php } ?>;
		var TIME_NOW = <?=TIME_NOW;?>;
		var LAST_UPDATE_TIME = <?=LAST_UPDATE_TIME;?>;
		var ENABLE_DEBUG_MODE = <?php if (ENABLE_DEBUG_MODE) { ?>true<?php } else { ?>false<?php } ?>;
		var ENABLE_PRODUCTION_DEBUG_MODE = <?php if (ENABLE_PRODUCTION_DEBUG_MODE) { ?>true<?php } else { ?>false<?php } ?>;
		var ENABLE_DEVELOPER_TOOLS = <?php if (ENABLE_DEVELOPER_TOOLS) { ?>true<?php } else { ?>false<?php } ?>;
		
		
		
		var COMPILER_TARGET_DEFAULT = true;
	</script>

	<script data-eager="true" src="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getPath());?>js/WoltLabSuite/WebComponent.min.js?v=<?=LAST_UPDATE_TIME;?>"></script>
	<script data-eager="true" src="<?=wcf\util\StringUtil::encodeHTML($this->v['phrasePreloader']->getUrl($this->v['__wcf']->language));?>"></script>
	
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require.config', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'require.linearExecution', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'wcf.globalHelper', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => '3rdParty/tslib', 'bundle' => 'WoltLabSuite.Core', 'core' => 'true'], $this);?>
	<script>
		requirejs.config({
			baseUrl: '<?=$this->v['__wcf']->getPath();?>js',
			urlArgs: 't=<?=LAST_UPDATE_TIME;?>'
			<?php ob_start(); ?><?php
$this->v['tpl']['capture']['default'] = ob_get_clean();
$this->assign('hascontent_dd43b4273eb32aebaee00c3c495a66841cedbad7', $this->v['tpl']['capture']['default']);
?>
<?php $this->assign('hascontent_dd43b4273eb32aebaee00c3c495a66841cedbad7', trim($this->v['hascontent_dd43b4273eb32aebaee00c3c495a66841cedbad7'])); ?>
<?php if ($this->v['hascontent_dd43b4273eb32aebaee00c3c495a66841cedbad7']) { ?>
			, paths: {
				<?=$this->v['hascontent_dd43b4273eb32aebaee00c3c495a66841cedbad7'];?>

			}
			<?php } ?>

		});
		
	</script>
	<script>
		require(['Language', 'WoltLabSuite/Core/Acp/Bootstrap', 'User'], function(Language, AcpBootstrap, User) {
			Language.addObject({
				'wcf.acp.search.noResults': 'Keine Treffer',

				
			});
			
			User.init(
				<?=$this->v['__wcf']->user->userID;?>,
				<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->username], $this);?>'<?php } else { ?>''<?php } ?>,
				<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->getLink()], $this);?>'<?php } else { ?>''<?php } ?>
			);
			
			AcpBootstrap.setup({
				bootstrap: {
					dynamicColorScheme: <?php if ($this->v['__wcf']->getStyleHandler()->getColorScheme() === 'system') { ?>true<?php } else { ?>false<?php } ?>,
					enableMobileMenu: <?php if (PACKAGE_ID && empty($this->v['__isLogin'])) { ?>true<?php } else { ?>false<?php } ?>,
				}
			});
		});
	</script>
	
	<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin'] = new wcf\system\template\plugin\EncodeJSModifierTemplatePlugin;
}
?><?php if (ENABLE_DEBUG_MODE && ENABLE_DEVELOPER_TOOLS && $this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
	<script data-relocate="true">
		require(['Ajax', 'WoltLabSuite/Core/Language/Chooser'], function(Ajax, LanguageChooser) {
			var item = elCreate('li');
			item.id = 'pageLanguageContainer';
			var userPanelItems = elBySel('.userPanelItems');
			userPanelItems.insertBefore(item, userPanelItems.firstChild);
			
			var languages = {
				<?php
$_length8e653bdf33de2f7a1e0359ebf61314cd35ab68dc = count($this->v['__wcf']->getLanguage()->getLanguages());
$_i8e653bdf33de2f7a1e0359ebf61314cd35ab68dc = 0;
$_item8e653bdf33de2f7a1e0359ebf61314cd35ab68dc = $this->v['_language'] ?? null;
$_key8e653bdf33de2f7a1e0359ebf61314cd35ab68dc =  null;
foreach ($this->v['__wcf']->getLanguage()->getLanguages() as $this->v['_language']) { ?>
				'<?=$this->v['_language']->languageID;?>': {
					iconPath: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']->getIconPath()], $this);?>',
					languageName: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']], $this);?>',
					languageCode: '<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['_language']->languageCode], $this);?>'
				}
				<?php
if (++$_i8e653bdf33de2f7a1e0359ebf61314cd35ab68dc < $_length8e653bdf33de2f7a1e0359ebf61314cd35ab68dc) { echo ', '; }
}
unset($this->v['_language']);$this->v['_language'] = $_item8e653bdf33de2f7a1e0359ebf61314cd35ab68dc;
unset($_length8e653bdf33de2f7a1e0359ebf61314cd35ab68dc, $_i8e653bdf33de2f7a1e0359ebf61314cd35ab68dc);
unset($_item8e653bdf33de2f7a1e0359ebf61314cd35ab68dc, $_key8e653bdf33de2f7a1e0359ebf61314cd35ab68dc);
?>
			};
			
			var callback = function(listItem) {
				Ajax.apiOnce({
					data: {
						actionName: 'devtoolsSetLanguage',
						className: 'wcf\\data\\user\\UserAction',
						parameters: {
							languageID: elData(listItem, 'language-id')
						}
					},
					success: function() {
						window.location.reload();
					}
				});
			};
			
			LanguageChooser.init('pageLanguageContainer', 'pageLanguageID', <?=$this->v['__wcf']->getLanguage()->languageID;?>, languages, callback);
		});
	</script>
<?php } ?>
	
	<script>
		// prevent jQuery and other libraries from utilizing define()
		__require_define_amd = define.amd;
		define.amd = undefined;
	</script>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui', 'file' => 'touchPunch', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'lib' => 'jquery-ui', 'file' => 'nestedSortable', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Assets', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'acp' => 'true', 'file' => 'WCF.ACP'], $this);?>
	<script>
		define.amd = __require_define_amd;
		$.holdReady(true);
		WCF.User.init(
			<?=$this->v['__wcf']->user->userID;?>,
			<?php if ($this->v['__wcf']->user->userID) { ?>'<?=$this->pluginObjects['wcf\system\template\plugin\EncodeJSModifierTemplatePlugin']->execute([$this->v['__wcf']->user->username], $this);?>'<?php } else { ?>''<?php } ?>
		);
	</script>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Message', 'bundle' => 'WCF.Combined'], $this);?>
	<?=$this->pluginObjects['wcf\system\template\plugin\JsFunctionTemplatePlugin']->execute(['application' => 'wcf', 'file' => 'WCF.Label', 'bundle' => 'WCF.Combined'], $this);?>
	<script>
		$(function() {
			if (jQuery.browser.touch) $('html').addClass('touch');
			
			<?php if ($this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
				new WCF.ACP.Search();
			<?php } ?>
			
			
			
			$('form[method=get]').attr('method', 'post');
			
			// rewrites legacy links using the `dereferrer.php` service
			// see https://github.com/WoltLab/WCF/issues/2557
			elBySelAll('a', undefined, function(link) {
				if (/\/dereferrer.php$/.test(link.pathname) && link.search.match(/^\?url=([^&=]+)$/)) {
					link.href = unescape(RegExp.$1);
				}
				
				if (link.classList.contains('externalURL')) {
					var rel = (link.rel === '') ? [] : link.rel.split(' ');
					if (rel.indexOf('noopener') === -1) rel.push('noopener');
					
					link.rel = rel.join(' ');
				}
			});
			
			WCF.DOMNodeInsertedHandler.execute();
		});
	</script>
	
	
	<?php if ( ! empty($this->v['headContent'])) { ?>
		<?=$this->v['headContent'];?>
	<?php } ?>
</head>

<body id="tpl<?=wcf\util\StringUtil::encodeHTML(ucfirst($this->v['templateName']));?>" data-template="<?=wcf\util\StringUtil::encodeHTML($this->v['templateName']);?>" data-application="<?=wcf\util\StringUtil::encodeHTML($this->v['templateNameApplication']);?>" class="wcfAcp<?php if ( ! empty($this->v['__isLogin'])) { ?> acpAuthFlow<?php } ?>">
	<span id="top"></span>
	
	<?php $this->assign('_acpPageSubMenuActive', false); ?>
	<?php if (PACKAGE_ID) { ?>
		<?php $this->assign('_activeMenuItems', $this->v['__wcf']->getACPMenu()->getActiveMenuItems()); ?>
		<?php
$_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['5eb7f0138daf7c6d0a0880176b6529f07628a8f6'] = [];
$this->foreachVars['5eb7f0138daf7c6d0a0880176b6529f07628a8f6']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6) && count($_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6) > 0) || (!is_countable($_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6) && $_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6)) {
foreach ($_foreach_5eb7f0138daf7c6d0a0880176b6529f07628a8f6 as $this->v['_sectionMenuItem']) {
?>
			<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?><?php $this->assign('_acpPageSubMenuActive', true); ?><?php } ?>
		<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['5eb7f0138daf7c6d0a0880176b6529f07628a8f6']['item'];
unset($this->foreachVars['5eb7f0138daf7c6d0a0880176b6529f07628a8f6']);
 } ?>
	<?php } ?>
	<div id="pageContainer" class="pageContainer<?php if ( ! PACKAGE_ID ||  ! $this->v['__wcf']->user->userID ||  ! empty($this->v['__isLogin'])) { ?> acpPageHiddenMenu<?php } elseif ($this->v['_acpPageSubMenuActive']) { ?> acpPageSubMenuActive<?php } ?>">
		
		
		<div class="pageHeaderContainer<?php if ( ! empty($this->v['__isLogin'])) { ?> pageHeaderContainerIsLogin<?php } ?>">
	<header id="pageHeader" class="pageHeader">
		<div id="pageHeaderPanel" class="pageHeaderPanel">
			<div class="layoutBoundary">
				<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
?><div
	id="pageHeaderLogo"
	class="
		pageHeaderLogo
		<?php if (ENABLE_DEBUG_MODE) { ?> pageHeaderLogo--debug<?php } ?>
		<?php if (ENABLE_DEVELOPER_TOOLS) { ?> pageHeaderLogo--dev<?php } ?>
	"
>
	<a href="<?php $this->tagStack[] = ['link', []];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">
		<img src="<?=$this->v['__wcf']->getPath();?>acp/images/woltlabSuite.png" alt="" width="562" height="80" loading="eager" class="pageHeaderLogoLarge">
		<img src="<?=$this->v['__wcf']->getPath();?>acp/images/woltlabSuite-small.png" alt="" width="55" height="30" loading="eager" class="pageHeaderLogoSmall">
	</a>
</div>
				
				
				<?php if (empty($this->v['__isLogin'])) { ?>
					<?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin'] = new wcf\system\template\plugin\LinkBlockTemplatePlugin;
}
?><nav id="topMenu" class="userPanel">
	<ul class="userPanelItems">
		<?php if ($this->v['__wcf']->user->userID) { ?>
			<?php if (PACKAGE_ID) { ?>
				<li id="userMenu" class="dropdown">
					<a href="#" class="dropdownToggle jsTooltip" title="<?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->user->username);?>"><?=$this->v['__wcf']->getUserProfileHandler()->getAvatar()->getImageTag(24);?></a>
					<ul class="dropdownMenu dropdownMenuUserPanel" data-dropdown-alignment-horizontal="right">
						<li><a href="<?php $this->tagStack[] = ['link', ['controller' => 'Logout']];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?>t=<?=rawurlencode($this->v['__wcf']->session->getSecurityToken());?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Abmelden</a></li>
					</ul>
				</li>
				
				<li id="jumpToPage">
					<a href="<?php $this->tagStack[] = ['link', ['forceFrontend' => true]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="jsTooltip" title="Zur Seite">
						<fa-icon size="16" name="house"></fa-icon>
						<fa-icon size="32" name="house"></fa-icon>
					</a>
				</li>
				
				<?php if ($this->v['__wcf']->session->getPermission('admin.configuration.package.canUpdatePackage') && $this->v['__wcf']->getAvailableUpdates()) { ?>
					<li id="outstandingUpdatesNotification">
						<a href="<?php $this->tagStack[] = ['link', ['controller' => 'PackageList', 'searchForUpdates' => true]];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="jsTooltip" title="Aktualisierungen">
							<fa-icon size="16" name="arrows-rotate"></fa-icon>
							<fa-icon size="32" name="arrows-rotate"></fa-icon>
							<span class="badge badgeUpdate"><?=wcf\util\StringUtil::formatNumeric((float)$this->v['__wcf']->getAvailableUpdates());?></span>
						</a>
					</li>
				<?php } ?>
			<?php } ?>
			
			<li id="woltlab" class="dropdown">
				<a href="#" class="dropdownToggle jsTooltip" title="WoltLab&reg;">
					<fa-icon size="16" name="info"></fa-icon>
					<fa-icon size="32" name="info"></fa-icon>
				</a>
				
				<ul class="dropdownMenu dropdownMenuUserPanel" data-dropdown-alignment-horizontal="right">
					<li><a class="externalURL" href="https://www.woltlab.com/<?php if ($this->v['__wcf']->getLanguage()->getFixedLanguageCode() === 'de') { ?>de/<?php } ?>"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Website</a></li>
					<li><a class="externalURL" href="https://manual.woltlab.com/<?php if ($this->v['__wcf']->getLanguage()->getFixedLanguageCode() === 'de') { ?>de<?php } else { ?>en<?php } ?>/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Handbuch</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/community/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Supportforum</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/ticket-add/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Ticket-Support</a></li>
					<li><a class="externalURL" href="https://www.woltlab.com/pluginstore/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank" rel="noopener"<?php } ?>>Plugin-Store</a></li>
				</ul>
			</li>
		<?php } ?>
		
		
	</ul>
</nav>
					
					<div id="mainMenu" class="mainMenu">
	<!-- Placeholder for the mobile UI. -->
</div>
<button type="button" class="pageHeaderMenuMobile" aria-expanded="false" aria-label="Menü">
	<span class="pageHeaderMenuMobileInactive">
		<fa-icon size="32" name="bars"></fa-icon>
	</span>
	<span class="pageHeaderMenuMobileActive">
		<fa-icon size="32" name="xmark"></fa-icon>
	</span>
</button>
					
					<button type="button" id="pageHeaderSearchMobile" class="pageHeaderSearchMobile" aria-expanded="false" aria-label="Suche">
	<fa-icon size="32" name="magnifying-glass"></fa-icon>
</button>

<div id="pageHeaderSearch" class="pageHeaderSearch" data-disable-auto-focus="true">
	<div class="pageHeaderSearchInputContainer">
		<div id="pageHeaderSearchType" class="pageHeaderSearchType dropdown">
			<a href="#" class="button dropdownToggle" id="pageHeaderSearchTypeSelect">
				<span class="pageHeaderSearchTypeLabel">Alles</span>
				<fa-icon size="16" name="caret-down" solid></fa-icon>
			</a>
			<ul class="dropdownMenu">
				<li><a href="#" data-provider-name="everywhere">Alles</a></li>
				<li class="dropdownDivider"></li>
				
				<?php
$_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921 = $this->v['availableAcpSearchProviders'];
$this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921'] = [];
$this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921']['item'] = $this->v['availableAcpSearchProviderLabel'] ?? null;
if ((is_countable($_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921) && count($_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921) > 0) || (!is_countable($_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921) && $_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921)) {
$this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921']['key'] = $this->v['availableAcpSearchProviderName'] ?? null;
foreach ($_foreach_a907b56e4c9032f99b7ec0ca5eb3fefe52a82921 as $this->v['availableAcpSearchProviderName'] => $this->v['availableAcpSearchProviderLabel']) {
?>
					<li><a href="#" data-provider-name="<?=$this->v['availableAcpSearchProviderName'];?>"><?=$this->v['availableAcpSearchProviderLabel'];?></a></li>
				<?php }
unset($this->v['availableAcpSearchProviderLabel']);$this->v['availableAcpSearchProviderLabel'] = $this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921']['item'];
unset($this->v['availableAcpSearchProviderName']);if (array_key_exists('key', $this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921'])) {
$this->v['availableAcpSearchProviderName'] = $this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921']['key'];
}
unset($this->foreachVars['a907b56e4c9032f99b7ec0ca5eb3fefe52a82921']);
 } ?>
			</ul>
		</div>
		
		<input type="search" name="q" id="pageHeaderSearchInput" class="pageHeaderSearchInput" placeholder="Suchbegriff eingeben" autocomplete="off" required value="" data-toggle="search">

		<span class="pageHeaderSearchShortcut" aria-hidden="true">S</span>
		
		<button type="button" class="button pageHeaderSearchInputButton" type="submit" title="Suche">
			<fa-icon size="16" name="magnifying-glass"></fa-icon>
		</button>
	</div>
</div>
				<?php } ?>
			</div>
		</div>
	</header>
</div>
		
		
		
		<div id="acpPageContentContainer" class="acpPageContentContainer">
			<?php if (PACKAGE_ID && $this->v['__wcf']->user->userID && empty($this->v['__isLogin'])) { ?>
	<?php $this->assign('_activeMenuItems', $this->v['__wcf']->getACPMenu()->getActiveMenuItems()); ?>
	
	<nav id="acpPageMenu" class="acpPageMenu">
		<ol class="acpPageMenuList">
			<?php
$_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['dacc4d6873671e2054945c69b0c310398d0d83c2'] = [];
$this->foreachVars['dacc4d6873671e2054945c69b0c310398d0d83c2']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2) && count($_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2) > 0) || (!is_countable($_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2) && $_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2)) {
foreach ($_foreach_dacc4d6873671e2054945c69b0c310398d0d83c2 as $this->v['_sectionMenuItem']) {
?>
				<li>
					<button type="button" class="acpPageMenuLink<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" data-menu-item="<?=wcf\util\StringUtil::encodeHTML($this->v['_sectionMenuItem']->menuItem);?>">
						<?=$this->v['_sectionMenuItem']->getIcon()->toHtml(32);?>
						<span class="acpPageMenuItemLabel"><?=$this->v['_sectionMenuItem'];?></span>
					</button>
				</li>
			<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['dacc4d6873671e2054945c69b0c310398d0d83c2']['item'];
unset($this->foreachVars['dacc4d6873671e2054945c69b0c310398d0d83c2']);
 } ?>
		</ol>
	</nav>
	
	<nav id="acpPageSubMenu" class="acpPageSubMenu">
		<?php
$_foreach_56f38facb44c2e855a2230792073dd3e8da538a7 = $this->v['__wcf']->getACPMenu()->getMenuItems('');
$this->foreachVars['56f38facb44c2e855a2230792073dd3e8da538a7'] = [];
$this->foreachVars['56f38facb44c2e855a2230792073dd3e8da538a7']['item'] = $this->v['_sectionMenuItem'] ?? null;
if ((is_countable($_foreach_56f38facb44c2e855a2230792073dd3e8da538a7) && count($_foreach_56f38facb44c2e855a2230792073dd3e8da538a7) > 0) || (!is_countable($_foreach_56f38facb44c2e855a2230792073dd3e8da538a7) && $_foreach_56f38facb44c2e855a2230792073dd3e8da538a7)) {
foreach ($_foreach_56f38facb44c2e855a2230792073dd3e8da538a7 as $this->v['_sectionMenuItem']) {
?>
			<ol class="acpPageSubMenuCategoryList<?php if (in_array($this->v['_sectionMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" data-menu-item="<?=wcf\util\StringUtil::encodeHTML($this->v['_sectionMenuItem']->menuItem);?>">
				<?php
$_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d = $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_sectionMenuItem']->menuItem);
$this->foreachVars['6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d'] = [];
$this->foreachVars['6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d']['item'] = $this->v['_menuItemCategory'] ?? null;
if ((is_countable($_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d) && count($_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d) > 0) || (!is_countable($_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d) && $_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d)) {
foreach ($_foreach_6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d as $this->v['_menuItemCategory']) {
?>
					<li class="acpPageSubMenuCategory">
						<span><?=$this->v['_menuItemCategory'];?></span>
						
						<ol class="acpPageSubMenuItemList">
							<?php
$_foreach_11f446399fac02545efb3656ed78995cc46d7bfd = $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_menuItemCategory']->menuItem);
$this->foreachVars['11f446399fac02545efb3656ed78995cc46d7bfd'] = [];
$this->foreachVars['11f446399fac02545efb3656ed78995cc46d7bfd']['item'] = $this->v['_menuItem'] ?? null;
if ((is_countable($_foreach_11f446399fac02545efb3656ed78995cc46d7bfd) && count($_foreach_11f446399fac02545efb3656ed78995cc46d7bfd) > 0) || (!is_countable($_foreach_11f446399fac02545efb3656ed78995cc46d7bfd) && $_foreach_11f446399fac02545efb3656ed78995cc46d7bfd)) {
foreach ($_foreach_11f446399fac02545efb3656ed78995cc46d7bfd as $this->v['_menuItem']) {
?>
								<?php $this->assign('_subMenuItems', $this->v['__wcf']->getACPMenu()->getMenuItems($this->v['_menuItem']->menuItem)); ?>
								
								<?php if (empty($this->v['_subMenuItems'])) { ?>
									<li<?php if (in_array($this->v['_menuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> class="active"<?php } ?>><a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_menuItem']->getLink());?>" class="acpPageSubMenuLink"><?=$this->v['_menuItem'];?></a></li>
								<?php } else { ?>
									<?php if ($this->v['_menuItem']->menuItem === 'wcf.acp.menu.link.option.category') { ?>
										
										<?php
$_foreach_e389c971abc16023273d61485d887cf3f80fafbb = $this->v['_subMenuItems'];
$this->foreachVars['e389c971abc16023273d61485d887cf3f80fafbb'] = [];
$this->foreachVars['e389c971abc16023273d61485d887cf3f80fafbb']['item'] = $this->v['_subMenuItem'] ?? null;
if ((is_countable($_foreach_e389c971abc16023273d61485d887cf3f80fafbb) && count($_foreach_e389c971abc16023273d61485d887cf3f80fafbb) > 0) || (!is_countable($_foreach_e389c971abc16023273d61485d887cf3f80fafbb) && $_foreach_e389c971abc16023273d61485d887cf3f80fafbb)) {
foreach ($_foreach_e389c971abc16023273d61485d887cf3f80fafbb as $this->v['_subMenuItem']) {
?>
											<li<?php if (in_array($this->v['_subMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> class="active"<?php } ?>><a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_subMenuItem']->getLink());?>" class="acpPageSubMenuLink"><?=$this->v['_subMenuItem'];?></a></li>
										<?php }
unset($this->v['_subMenuItem']);$this->v['_subMenuItem'] = $this->foreachVars['e389c971abc16023273d61485d887cf3f80fafbb']['item'];
unset($this->foreachVars['e389c971abc16023273d61485d887cf3f80fafbb']);
 } ?>
									<?php } else { ?>
										<li class="acpPageSubMenuLinkWrapper">
											<a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_menuItem']->getLink());?>" class="acpPageSubMenuLink<?php if (in_array($this->v['_menuItem']->menuItem,$this->v['_activeMenuItems']) && $this->v['_activeMenuItems'][0] === $this->v['_menuItem']->menuItem) { ?> active<?php } ?>"><?=$this->v['_menuItem'];?></a>
											
											<?php
$_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7 = $this->v['_subMenuItems'];
$this->foreachVars['4bf90891a822676fdc98ed577d0aee0640a2aef7'] = [];
$this->foreachVars['4bf90891a822676fdc98ed577d0aee0640a2aef7']['item'] = $this->v['_subMenuItem'] ?? null;
if ((is_countable($_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7) && count($_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7) > 0) || (!is_countable($_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7) && $_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7)) {
foreach ($_foreach_4bf90891a822676fdc98ed577d0aee0640a2aef7 as $this->v['_subMenuItem']) {
?>
												<a href="<?=wcf\util\StringUtil::encodeHTML($this->v['_subMenuItem']->getLink());?>" class="acpPageSubMenuIcon jsTooltip<?php if (in_array($this->v['_subMenuItem']->menuItem,$this->v['_activeMenuItems'])) { ?> active<?php } ?>" title="<?=$this->v['_subMenuItem'];?>">
													<?=$this->v['_subMenuItem']->getIcon()->toHtml();?>
												</a>
											<?php }
unset($this->v['_subMenuItem']);$this->v['_subMenuItem'] = $this->foreachVars['4bf90891a822676fdc98ed577d0aee0640a2aef7']['item'];
unset($this->foreachVars['4bf90891a822676fdc98ed577d0aee0640a2aef7']);
 } ?>
										</li>
									<?php } ?>
								<?php } ?>
							<?php }
unset($this->v['_menuItem']);$this->v['_menuItem'] = $this->foreachVars['11f446399fac02545efb3656ed78995cc46d7bfd']['item'];
unset($this->foreachVars['11f446399fac02545efb3656ed78995cc46d7bfd']);
 } ?>
						</ol>
					</li>
				<?php }
unset($this->v['_menuItemCategory']);$this->v['_menuItemCategory'] = $this->foreachVars['6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d']['item'];
unset($this->foreachVars['6202a2aa02ea9e6ae11a9a3c7c1ce1321a487b1d']);
 } ?>
			</ol>
		<?php }
unset($this->v['_sectionMenuItem']);$this->v['_sectionMenuItem'] = $this->foreachVars['56f38facb44c2e855a2230792073dd3e8da538a7']['item'];
unset($this->foreachVars['56f38facb44c2e855a2230792073dd3e8da538a7']);
 } ?>
	</nav>
<?php } ?>
			
			<section id="main" class="main" role="main">
				<div class="layoutBoundary">
					<div id="content" class="content">



<script data-relocate="true">
	$(function() {
		new WCF.Option.Handler();
	});
	
	
</script>

<header class="contentHeader">
	<div class="contentHeaderTitle">
		<h1 class="contentTitle">Erstmalige Einrichtung: E-Mail-Einstellungen</h1>
	</div>
</header>

<?php if (isset($this->v['success'])) { ?>
	<woltlab-core-notice type="success">Die Änderungen wurden gespeichert.</woltlab-core-notice>
<?php } ?>

<woltlab-core-notice type="info">Konfigurieren Sie jetzt die von Ihrer Community genutzten E-Mail-Adressen. Der Versand erfolgt standardmäßig direkt durch PHP, nach Abschluss der Ersteinrichtung haben Sie die Möglichkeit in den Optionen einen SMTP-Server zu hinterlegen.</woltlab-core-notice>

<?php if ( ! empty($this->v['errorField'])) { ?>
	<?php if ((is_array($this->v['errorField']) && isset($this->v['errorField']['__securityToken'])) || $this->v['errorField'] == '__securityToken') { ?>
		<woltlab-core-notice type="error">Die Gültigkeit der Anfrage konnte aufgrund eines fehlerhaften XSRF-Tokens nicht verifiziert werden. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>sende<?php } else { ?>senden Sie<?php } ?> das Formular erneut ab.</woltlab-core-notice>
	<?php } else { ?>
		<woltlab-core-notice type="error"><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> Angaben sind ungültig. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>überprüfe<?php } else { ?>überprüfen Sie<?php } ?> die markierten Eingabefelder.</woltlab-core-notice>
	<?php } ?>
<?php } ?>

<form method="post" action="<?php $this->tagStack[] = ['link', ['controller' => 'FirstTimeSetupOptionsEmail']];
$this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects['wcf\system\template\plugin\LinkBlockTemplatePlugin']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" enctype="multipart/form-data">
	<?php
$this->v['langPrefix'] = 'wcf.acp.option.';

?><?php
if (!isset($this->pluginObjects['wcf\system\template\plugin\ConcatModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\ConcatModifierTemplatePlugin'] = new wcf\system\template\plugin\ConcatModifierTemplatePlugin;
}
if (!isset($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'])) {
$this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin'] = new wcf\system\template\plugin\PhraseModifierTemplatePlugin;
}
?><?php if ( ! isset($this->v['isGuestGroup'])) { ?><?php $this->assign('isGuestGroup', false); ?><?php } ?>
<?php if ( ! isset($this->v['groupIsOwner'])) { ?><?php $this->assign('groupIsOwner', false); ?><?php } ?>
<?php
$_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95 = $this->v['options'];
$this->foreachVars['eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95'] = [];
$this->foreachVars['eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95']['item'] = $this->v['optionData'] ?? null;
if ((is_countable($_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95) && count($_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95) > 0) || (!is_countable($_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95) && $_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95)) {
foreach ($_foreach_eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95 as $this->v['optionData']) {
?>
	<?php $this->assign('option', $this->v['optionData']['object']); ?>
	<?php if (is_array($this->v['errorType']) && isset($this->v['errorType'][$this->v['option']->optionName])) { ?>
		<?php $this->assign('error', $this->v['errorType'][$this->v['option']->optionName]); ?>
	<?php } else { ?>
		<?php $this->assign('error', ''); ?>
	<?php } ?>
	<dl class="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>Input<?php if ($this->v['error']) { ?> formError<?php } ?>">
		<dt<?php if ($this->v['optionData']['cssClassName']) { ?> class="<?=wcf\util\StringUtil::encodeHTML($this->v['optionData']['cssClassName']);?>"<?php } ?>>
			<?php if (empty($this->v['isSearchMode']) ||  ! $this->v['optionData']['hideLabelInSearch']) { ?>
				<label for="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>">
					<?php if (VISITOR_USE_TINY_BUILD && $this->v['isGuestGroup'] && $this->v['option']->excludedInTinyBuild) { ?>
						<span class="jsTooltip" title="Seitenbeschleunigung für Gäste ist aktiv">
							<fa-icon size="16" name="bolt"></fa-icon>
						</span>
					<?php } ?>
					<?php if ($this->v['groupIsOwner'] && in_array($this->v['option']->optionName,$this->v['ownerGroupPermissions'])) { ?>
						<span class="jsTooltip" title="Die Besitzer-Gruppe verfügt immer über diese Berechtigung, sie kann nicht entzogen werden.">
							<fa-icon size="16" name="shield-halved"></fa-icon>
						</span>
					<?php } ?>
					
					<?=wcf\util\StringUtil::encodeHTML($this->pluginObjects['wcf\system\template\plugin\PhraseModifierTemplatePlugin']->execute([$this->pluginObjects['wcf\system\template\plugin\ConcatModifierTemplatePlugin']->execute([$this->v['langPrefix'],$this->v['option']->optionName], $this)], $this));?>

					
				</label>
			<?php } ?>
		</dt>
		<dd><?=$this->v['optionData']['html'];?>
			<?php if ($this->v['error']) { ?>
				<small class="innerError">
					<?php if ($this->v['error'] == 'empty') { ?>
						Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>fülle<?php } else { ?>füllen Sie<?php } ?> dieses Eingabefeld aus.
					<?php } else { ?>
						<?php
			$this->tagStack[] = ['lang', array_merge($this->v, [])];
			ob_start();
			?><?=$this->v['langPrefix'];?>error.<?=wcf\util\StringUtil::encodeHTML($this->v['error']);?><?php
			echo wcf\system\WCF::getLanguage()->tplGet(ob_get_clean(), $this->tagStack[count($this->tagStack) - 1][1]);
			array_pop($this->tagStack); ?>
					<?php } ?>
				</small>
			<?php } ?>
			<small><?php
			$this->tagStack[] = ['lang', array_merge($this->v, ['__optional' => true])];
			ob_start();
			?><?=$this->v['langPrefix'];?><?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>.description<?php
			echo wcf\system\WCF::getLanguage()->tplGet(ob_get_clean(), $this->tagStack[count($this->tagStack) - 1][1]);
			array_pop($this->tagStack); ?></small>
		</dd>
	</dl>
<?php }
unset($this->v['optionData']);$this->v['optionData'] = $this->foreachVars['eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95']['item'];
unset($this->foreachVars['eba7ee57ac4d56672f5edb51ba4e78cfb9f34f95']);
 } ?>
	
	<div class="formSubmit">
		<input type="submit" value="Absenden" name="__submit" accesskey="s">
		<input type="hidden" name="t" class="xsrfTokenInput" value="<?='NOT_MODIFIED';?>">
	</div>
</form>

				</div>
			</div>
		</section>
	</div>
	
	<footer id="pageFooter" class="pageFooter">
	<?php if ( ! empty($this->v['errorField']) ||  ! empty($this->v['errorType'])) { ?>
		<!--
			DEBUG: FORM_VALIDATION_FAILED
			
			errorField: <?php if (empty($this->v['errorField'])) { ?>(empty)<?php } else { ?><?=wcf\util\StringUtil::encodeHTML(print_r($this->v['errorField'],true));?><?php } ?>
			
			errorType: <?php if (empty($this->v['errorType'])) { ?>(empty)<?php } else { ?><?=wcf\util\StringUtil::encodeHTML(print_r($this->v['errorType'],true));?><?php } ?>
		
		-->
	<?php } ?>
	
	<div id="pageFooterCopyright" class="pageFooterCopyright">
		<div class="layoutBoundary">
			

			<?php if (ENABLE_BENCHMARK) { ?><?php
$outerTemplateName25b63f3cfeca8313364f9d19944689cc3f3cb0bd = $this->v['tpl']['template'];
$this->includeTemplate('shared_benchmark', 'wcf', [], 1);
$this->v['tpl']['template'] = $outerTemplateName25b63f3cfeca8313364f9d19944689cc3f3cb0bd;
$this->v['tpl']['includedTemplates']['shared_benchmark'] = 1;
?><?php } ?>
			
			
			
			<div class="copyright"><a href="https://www.woltlab.com/de/" rel="nofollow"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank"<?php } ?>>Community-Software: <strong>WoltLab Suite&trade;<?php if (SHOW_VERSION_NUMBER) { ?> <?=WCF_VERSION;?><?php } ?></strong></a></div>
		</div>
	</div>
</footer>
</div>



<!-- <?=wcf\util\StringUtil::encodeHTML($this->v['__wcf']->getRequestNonce('JAVASCRIPT_RELOCATE_POSITION'));?> -->

<span id="bottom"></span>

</body>
</html>