<?php
/**
 * WoltLab Suite
 * Template: shared_booleanOptionType
 * Compiled at: Thu, 08 Jan 2026 08:26:35 +0000
 * 
 * DO NOT EDIT THIS FILE
 */
$this->v['tpl']['template'] = 'shared_booleanOptionType';
?>
<ol class="flexibleButtonGroup optionTypeBoolean">
	<li>
		<input type="radio" id="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>"<?php if ($this->v['value'] == 1) { ?> checked<?php } ?> name="values[<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>]" value="1"<?php if ($this->v['disableOptions'] || $this->v['enableOptions']) { ?> class="jsEnablesOptions" data-is-boolean="true" data-disable-options="[ <?=$this->v['disableOptions'];?>]" data-enable-options="[ <?=$this->v['enableOptions'];?>]"<?php } ?>>
		<label for="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>" class="green"><fa-icon size="16" name="check"></fa-icon> Ja</label>
	</li>
	<li>
		<input type="radio" id="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>_no"<?php if ($this->v['value'] == 0) { ?> checked<?php } ?> name="values[<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>]" value="0"<?php if ($this->v['disableOptions'] || $this->v['enableOptions']) { ?> class="jsEnablesOptions" data-is-boolean="true" data-disable-options="[ <?=$this->v['disableOptions'];?>]" data-enable-options="[ <?=$this->v['enableOptions'];?>]"<?php } ?>>
		<label for="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>_no" class="red"><fa-icon size="16" name="xmark"></fa-icon> Nein</label>
	</li>
</ol>