<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.user
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.user.controlPanel'] = 'Kontrollzentrum';
$this->items['wcf.user.email'] = 'E-Mail-Adresse';
$this->items['wcf.user.email.error.notUnique'] = 'Diese E-Mail-Adresse ist bereits durch einen anderen Benutzer vergeben.';
$this->items['wcf.user.email.error.invalid'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} eine ungültige E-Mail-Adresse eingegeben.';
$this->dynamicItems['wcf.user.email.error.invalid'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> eine ungültige E-Mail-Adresse eingegeben.';
$this->items['wcf.user.ipAddress'] = 'IP-Adresse';
$this->items['wcf.user.ipAddress.searchEngine'] = '{if !$host|empty}Auf {$host} nach{else}Nach{/if} {if !$ipAddress|empty}{$ipAddress}{else}dieser IP-Adresse{/if} suchen';
$this->dynamicItems['wcf.user.ipAddress.searchEngine'] = '<?php if ( ! empty($this->v[\'host\'])) { ?>Auf <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'host\']);?> nach<?php } else { ?>Nach<?php } ?> <?php if ( ! empty($this->v[\'ipAddress\'])) { ?><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'ipAddress\']);?><?php } else { ?>dieser IP-Adresse<?php } ?> suchen';
$this->items['wcf.user.userAgent'] = 'Browser-Kennung';
$this->items['wcf.user.login'] = 'Anmeldung';
$this->items['wcf.user.login.error.cookieRequired'] = 'Die Anmeldung erfordert den Einsatz von Cookies, bitte {if LANGUAGE_USE_INFORMAL_VARIANT}aktiviere{else}aktivieren Sie{/if} diese, um die Anmeldung durchzuführen.';
$this->dynamicItems['wcf.user.login.error.cookieRequired'] = 'Die Anmeldung erfordert den Einsatz von Cookies, bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>aktiviere<?php } else { ?>aktivieren Sie<?php } ?> diese, um die Anmeldung durchzuführen.';
$this->items['wcf.user.login.forceLogin'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du musst{else}Sie müssen{/if} angemeldet sein, um diese Seite aufrufen zu können.';
$this->dynamicItems['wcf.user.login.forceLogin'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du musst<?php } else { ?>Sie müssen<?php } ?> angemeldet sein, um diese Seite aufrufen zu können.';
$this->items['wcf.user.login.register.teaser'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} noch kein Benutzerkonto auf unserer Seite? <a href="{link controller=\'Register\'}{/link}">{if LANGUAGE_USE_INFORMAL_VARIANT}Registriere dich{else}Registrieren Sie sich{/if} kostenlos</a> und {if LANGUAGE_USE_INFORMAL_VARIANT}nimm{else}nehmen Sie{/if} an unserer Community teil!';
$this->dynamicItems['wcf.user.login.register.teaser'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> noch kein Benutzerkonto auf unserer Seite? <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'Register\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>"><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Registriere dich<?php } else { ?>Registrieren Sie sich<?php } ?> kostenlos</a> und <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>nimm<?php } else { ?>nehmen Sie<?php } ?> an unserer Community teil!';
$this->items['wcf.user.login.register.registerNow'] = 'Benutzerkonto erstellen';
$this->items['wcf.user.login.thirdPartySeparator'] = 'oder';
$this->items['wcf.user.login.noAccount'] = 'Noch kein Benutzerkonto? <a href="{link controller=\'Register\'}{/link}">Jetzt registrieren!</a>';
$this->dynamicItems['wcf.user.login.noAccount'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Noch kein Benutzerkonto? <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'Register\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Jetzt registrieren!</a>';
$this->items['wcf.user.password.error.false'] = 'Dieses Kennwort ist falsch.';
$this->items['wcf.user.language'] = 'Sprache';
$this->items['wcf.user.language.description'] = 'Sprache der Benutzeroberfläche';
$this->items['wcf.user.logout'] = 'Abmelden';
$this->items['wcf.user.password'] = 'Kennwort';
$this->items['wcf.user.registrationDate'] = 'Registrierungsdatum';
$this->items['wcf.user.registrationIpAddress'] = 'Registrierungs-IP-Adresse';
$this->items['wcf.user.visibleLanguages'] = 'Inhaltssprachen';
$this->items['wcf.user.visibleLanguages.description'] = 'Zeigt Inhalte der ausgewählten Sprachen an';
$this->items['wcf.user.userID'] = 'Benutzer-ID';
$this->items['wcf.user.username'] = 'Benutzername';
$this->items['wcf.user.username.placeholder'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} einen Benutzernamen ein';
$this->dynamicItems['wcf.user.username.placeholder'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> einen Benutzernamen ein';
$this->items['wcf.user.username.error.acpNotAuthorized'] = 'Dieser Benutzer ist nicht berechtigt, sich an der Administrationsoberfläche anzumelden.';
$this->items['wcf.user.username.error.notFound'] = 'Der Benutzername {$username} konnte nicht gefunden werden.';
$this->dynamicItems['wcf.user.username.error.notFound'] = 'Der Benutzername <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'username\']);?> konnte nicht gefunden werden.';
$this->items['wcf.user.username.error.notUnique'] = 'Dieser Benutzername ist bereits vergeben.';
$this->items['wcf.user.username.error.invalid'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Benutzernamen eingegeben.';
$this->dynamicItems['wcf.user.username.error.invalid'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Benutzernamen eingegeben.';
$this->items['wcf.user.userNote'] = '{$__wcf->user->username}';
$this->dynamicItems['wcf.user.userNote'] = '<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'__wcf\']->user->username);?>';
$this->items['wcf.user.group'] = 'Benutzergruppe';
$this->items['wcf.user.group.groupName'] = 'Gruppenname';
$this->items['wcf.user.option.error.tooLong'] = 'Der eingegebene Text ist zu lang.';
$this->items['wcf.user.option.error.tooShort'] = 'Der eingegebene Text ist zu kurz.';
$this->items['wcf.user.option.error.tooHigh'] = 'Der angegebene Wert ist zu hoch.{if $option->maxvalue !== null} Der maximale Wert ist {#$option->maxvalue}.{/if}';
$this->dynamicItems['wcf.user.option.error.tooHigh'] = 'Der angegebene Wert ist zu hoch.<?php if ($this->v[\'option\']->maxvalue !== null) { ?> Der maximale Wert ist <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'option\']->maxvalue);?>.<?php } ?>';
$this->items['wcf.user.option.error.tooLow'] = 'Der angegebene Wert ist zu gering.{if $option->minvalue !== null} Der minimale Wert ist {#$option->minvalue}.{/if}';
$this->dynamicItems['wcf.user.option.error.tooLow'] = 'Der angegebene Wert ist zu gering.<?php if ($this->v[\'option\']->minvalue !== null) { ?> Der minimale Wert ist <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'option\']->minvalue);?>.<?php } ?>';
$this->items['wcf.user.option.error.validationFailed'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Inhalt eingegeben.';
$this->dynamicItems['wcf.user.option.error.validationFailed'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Inhalt eingegeben.';
$this->items['wcf.user.option.error.birthdayTooYoung'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du bist{else}Sie sind{/if} zu jung. Für eine Anmeldung auf dieser Seite {if LANGUAGE_USE_INFORMAL_VARIANT}musst du{else}müssen Sie{/if} mindestens {#REGISTER_MIN_USER_AGE} Jahre alt sein.';
$this->dynamicItems['wcf.user.option.error.birthdayTooYoung'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du bist<?php } else { ?>Sie sind<?php } ?> zu jung. Für eine Anmeldung auf dieser Seite <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>musst du<?php } else { ?>müssen Sie<?php } ?> mindestens <?=wcf\\util\\StringUtil::formatNumeric((float)REGISTER_MIN_USER_AGE);?> Jahre alt sein.';
$this->items['wcf.user.option.error.censoredWordsFound'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Text verwendet nicht gestattete Begriffe: {implode from=$censoredWords key=censoredWord item=number}{$censoredWord}{if $number > 1} ({#$number}×){/if}{/implode}';
$this->dynamicItems['wcf.user.option.error.censoredWordsFound'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Text verwendet nicht gestattete Begriffe: <?php
$_lengthe1c8627f3d330b7564f8ece7dc9e73bdcfa01c12 = count($this->v[\'censoredWords\']);
$_ie1c8627f3d330b7564f8ece7dc9e73bdcfa01c12 = 0;
$_iteme1c8627f3d330b7564f8ece7dc9e73bdcfa01c12 = $this->v[\'number\'] ?? null;
$_keye1c8627f3d330b7564f8ece7dc9e73bdcfa01c12 = $this->v[\'censoredWord\'] ??  null;
foreach ($this->v[\'censoredWords\'] as $this->v[\'censoredWord\'] => $this->v[\'number\']) { ?><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'censoredWord\']);?><?php if ($this->v[\'number\'] > 1) { ?> (<?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'number\']);?>×)<?php } ?><?php
if (++$_ie1c8627f3d330b7564f8ece7dc9e73bdcfa01c12 < $_lengthe1c8627f3d330b7564f8ece7dc9e73bdcfa01c12) { echo \', \'; }
}
unset($this->v[\'number\']);$this->v[\'number\'] = $_iteme1c8627f3d330b7564f8ece7dc9e73bdcfa01c12;
unset($this->v[\'censoredWord\']);$this->v[\'censoredWord\'] = $_keye1c8627f3d330b7564f8ece7dc9e73bdcfa01c12;
unset($_lengthe1c8627f3d330b7564f8ece7dc9e73bdcfa01c12, $_ie1c8627f3d330b7564f8ece7dc9e73bdcfa01c12);
unset($_iteme1c8627f3d330b7564f8ece7dc9e73bdcfa01c12, $_keye1c8627f3d330b7564f8ece7dc9e73bdcfa01c12);
?>';
$this->items['wcf.user.option.error.disallowedBBCodes'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} Nachricht enthält die folgenden BBCodes, die {if LANGUAGE_USE_INFORMAL_VARIANT}du nicht verwenden darfst{else}Sie nicht verwenden dürfen{/if}: {implode from=$disallowedBBCodes item=disallowedBBCode}{$disallowedBBCode}{/implode}';
$this->dynamicItems['wcf.user.option.error.disallowedBBCodes'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> Nachricht enthält die folgenden BBCodes, die <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du nicht verwenden darfst<?php } else { ?>Sie nicht verwenden dürfen<?php } ?>: <?php
$_lengthd98a90606f8bc76da747b028a80f0c98b6e782c8 = count($this->v[\'disallowedBBCodes\']);
$_id98a90606f8bc76da747b028a80f0c98b6e782c8 = 0;
$_itemd98a90606f8bc76da747b028a80f0c98b6e782c8 = $this->v[\'disallowedBBCode\'] ?? null;
$_keyd98a90606f8bc76da747b028a80f0c98b6e782c8 =  null;
foreach ($this->v[\'disallowedBBCodes\'] as $this->v[\'disallowedBBCode\']) { ?><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'disallowedBBCode\']);?><?php
if (++$_id98a90606f8bc76da747b028a80f0c98b6e782c8 < $_lengthd98a90606f8bc76da747b028a80f0c98b6e782c8) { echo \', \'; }
}
unset($this->v[\'disallowedBBCode\']);$this->v[\'disallowedBBCode\'] = $_itemd98a90606f8bc76da747b028a80f0c98b6e782c8;
unset($_lengthd98a90606f8bc76da747b028a80f0c98b6e782c8, $_id98a90606f8bc76da747b028a80f0c98b6e782c8);
unset($_itemd98a90606f8bc76da747b028a80f0c98b6e782c8, $_keyd98a90606f8bc76da747b028a80f0c98b6e782c8);
?>';
$this->items['wcf.user.error.isBanned'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto wurde{if $__wcf->user->banExpires != 0} bis zum {@$__wcf->user->banExpires|date}{/if} gesperrt{if $__wcf->user->banReason}: {@$__wcf->user->banReason|newlineToBreak}{else}.{/if}';
$this->dynamicItems['wcf.user.error.isBanned'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\NewlineToBreakModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\NewlineToBreakModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\NewlineToBreakModifierTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto wurde<?php if ($this->v[\'__wcf\']->user->banExpires != 0) { ?> bis zum <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'__wcf\']->user->banExpires], $this);?><?php } ?> gesperrt<?php if ($this->v[\'__wcf\']->user->banReason) { ?>: <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\NewlineToBreakModifierTemplatePlugin\']->execute([$this->v[\'__wcf\']->user->banReason], $this);?><?php } else { ?>.<?php } ?>';
$this->items['wcf.user.access.everyone'] = 'Jeder';
$this->items['wcf.user.access.following'] = 'Benutzer, denen ich folge';
$this->items['wcf.user.access.nobody'] = 'Keiner';
$this->items['wcf.user.access.registered'] = 'Registrierte Benutzer';
$this->items['wcf.user.button.login'] = 'Anmelden';
$this->items['wcf.user.button.register'] = 'Registrieren';
$this->items['wcf.user.username.error.3rdParty'] = 'Das Benutzerkonto ist mit einem Drittanbieter-Konto verbunden, ein Kennwort kann nicht angefordert werden.';
$this->items['wcf.user.username.error.3rdParty.redirect'] = 'Das Benutzerkonto ist mit {$provider} verbunden, ein Kennwort kann nicht angefordert werden. Sie werden jetzt zur Anmeldung mit {$provider} weitergeleitet.';
$this->dynamicItems['wcf.user.username.error.3rdParty.redirect'] = 'Das Benutzerkonto ist mit <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'provider\']);?> verbunden, ein Kennwort kann nicht angefordert werden. Sie werden jetzt zur Anmeldung mit <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'provider\']);?> weitergeleitet.';
$this->items['wcf.user.usernameOrEmail'] = 'Benutzername oder E-Mail-Adresse';
$this->items['wcf.user.gender.male'] = 'Männlich';
$this->items['wcf.user.gender.female'] = 'Weiblich';
$this->items['wcf.user.gender.other'] = 'Divers';
$this->items['wcf.user.members'] = 'Mitglieder';
$this->items['wcf.user.members.filter'] = 'Mitglieder filtern';
$this->items['wcf.user.members.noMembers'] = 'Es wurden keine Mitglieder gefunden. <a href="{link controller=\'MembersList\'}{/link}">Die aktiven Filter zurücksetzen.</a>';
$this->dynamicItems['wcf.user.members.noMembers'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Es wurden keine Mitglieder gefunden. <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'MembersList\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Die aktiven Filter zurücksetzen.</a>';
$this->items['wcf.user.members.sort'] = 'Sortierung';
$this->items['wcf.user.members.sort.letters'] = 'Anfangsbuchstabe';
$this->items['wcf.user.members.sort.letters.all'] = 'Alle';
$this->items['wcf.user.membersList.registrationDate'] = 'Mitglied seit {@$user->registrationDate|date}';
$this->dynamicItems['wcf.user.membersList.registrationDate'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
?>Mitglied seit <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'user\']->registrationDate], $this);?>';
$this->items['wcf.user.membersList.location'] = 'aus {$user->location}';
$this->dynamicItems['wcf.user.membersList.location'] = 'aus <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->location);?>';
$this->items['wcf.user.myProfile'] = 'Mein Profil';
$this->items['wcf.user.editProfile'] = 'Profil bearbeiten';
$this->items['wcf.user.profileHits'] = 'Profil-Aufrufe';
$this->items['wcf.user.profileHits.hitsPerDay'] = '{#$user->profileHits/$user->getProfileAge()} Aufrufe pro Tag';
$this->dynamicItems['wcf.user.profileHits.hitsPerDay'] = '<?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'user\']->profileHits/$this->v[\'user\']->getProfileAge());?> Aufrufe pro Tag';
$this->items['wcf.user.online'] = 'Online';
$this->items['wcf.user.online.title'] = '{$username} ist online';
$this->dynamicItems['wcf.user.online.title'] = '<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'username\']);?> ist online';
$this->items['wcf.user.button.follow'] = 'Folgen';
$this->items['wcf.user.button.unfollow'] = 'Entfolgen';
$this->items['wcf.user.button.ignore'] = 'Blockieren';
$this->items['wcf.user.button.unignore'] = 'Nicht mehr blockieren';
$this->items['wcf.user.style'] = 'Stil';
$this->items['wcf.user.styles'] = 'Stile';
$this->items['wcf.user.style.description'] = 'Stil der Benutzeroberfläche';
$this->items['wcf.user.style.colorScheme'] = 'Bevorzugtes Farbschema';
$this->items['wcf.user.style.colorScheme.description'] = 'Die automatische Erkennung wendet das Farbschema basierend auf den Präferenzen Ihres Geräts an. Einige Stile verfügen möglicherweise nicht über angepasste Farbschemata.';
$this->items['wcf.user.username.description'] = 'Der Benutzername muss mindestens {REGISTER_USERNAME_MIN_LENGTH} und darf maximal {REGISTER_USERNAME_MAX_LENGTH} Zeichen lang sein.';
$this->dynamicItems['wcf.user.username.description'] = 'Der Benutzername muss mindestens <?=wcf\\util\\StringUtil::encodeHTML(REGISTER_USERNAME_MIN_LENGTH);?> und darf maximal <?=wcf\\util\\StringUtil::encodeHTML(REGISTER_USERNAME_MAX_LENGTH);?> Zeichen lang sein.';
$this->items['wcf.user.password.description'] = 'Ein sicheres Kennwort sollte mindestens 10 Zeichen lang sein.';
$this->items['wcf.user.password.strength'] = 'Kennwortstärke';
$this->items['wcf.user.password.zxcvbn.suggestions.use_words_avoid_common_phrases'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Verwende{else}Verwenden Sie{/if} einige Wörter. {if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} gängige Phrasen.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.use_words_avoid_common_phrases'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Verwende<?php } else { ?>Verwenden Sie<?php } ?> einige Wörter. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> gängige Phrasen.';
$this->items['wcf.user.password.zxcvbn.suggestions.no_need_for_symbols_digits_uppercase'] = 'Sonderzeichen, Zahlen oder Großbuchstaben werden nicht benötigt.';
$this->items['wcf.user.password.zxcvbn.suggestions.add_word_uncommon_better'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Ergänze{else}Ergänzen Sie{/if} ein oder zwei weitere Worte. Unübliche Worte sind zu bevorzugen.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.add_word_uncommon_better'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Ergänze<?php } else { ?>Ergänzen Sie<?php } ?> ein oder zwei weitere Worte. Unübliche Worte sind zu bevorzugen.';
$this->items['wcf.user.password.zxcvbn.suggestions.use_longer_keyboard_pattern'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Verwende{else}Verwenden Sie{/if} ein längeres und zufälligeres Muster auf der Tastatur.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.use_longer_keyboard_pattern'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Verwende<?php } else { ?>Verwenden Sie<?php } ?> ein längeres und zufälligeres Muster auf der Tastatur.';
$this->items['wcf.user.password.zxcvbn.suggestions.avoid_repeat'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} Wiederholungen.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.avoid_repeat'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> Wiederholungen.';
$this->items['wcf.user.password.zxcvbn.suggestions.avoid_sequence'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} Sequenzen.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.avoid_sequence'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> Sequenzen.';
$this->items['wcf.user.password.zxcvbn.suggestions.avoid_recent_year'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} Jahreszahlen der letzten Jahre.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.avoid_recent_year'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> Jahreszahlen der letzten Jahre.';
$this->items['wcf.user.password.zxcvbn.suggestions.avoid_associated_year'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} Jahreszahlen, die {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} zugeordnet werden können.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.avoid_associated_year'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> Jahreszahlen, die <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> zugeordnet werden können.';
$this->items['wcf.user.password.zxcvbn.suggestions.avoid_date'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Vermeide{else}Vermeiden Sie{/if} Daten und Jahreszahlen, die {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} zugeordnet werden können.';
$this->dynamicItems['wcf.user.password.zxcvbn.suggestions.avoid_date'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Vermeide<?php } else { ?>Vermeiden Sie<?php } ?> Daten und Jahreszahlen, die <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> zugeordnet werden können.';
$this->items['wcf.user.password.zxcvbn.suggestions.start_upper'] = 'Großbuchstaben zu Beginn erhöhen die Sicherheit nicht.';
$this->items['wcf.user.password.zxcvbn.suggestions.all_upper'] = 'Nur Großbuchstaben sind genau so einfach zu erraten, wie nur Kleinbuchstaben.';
$this->items['wcf.user.password.zxcvbn.suggestions.reversed'] = 'Umgekehrte Worte sind nicht viel schwieriger zu erraten.';
$this->items['wcf.user.password.zxcvbn.suggestions.l33t'] = 'Vorhersehbare Ersetzungen, wie beispielsweise „@“ statt „a“, erhöhen die Sicherheit nicht.';
$this->items['wcf.user.password.zxcvbn.warnings.straight_row'] = 'Geradlinige Sequenzen auf der Tastatur sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.short_keyboard_pattern'] = 'Kurze Sequenzen auf der Tastatur sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.repeat_single_char'] = 'Wiederholungen wie beispielsweise „aaa“ sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.repeat'] = 'Wiederholungen wie beispielsweise „abcabcabc“ sind nicht viel schwieriger zu erraten als „abc“.';
$this->items['wcf.user.password.zxcvbn.warnings.sequence'] = 'Sequenzen wie „abc“ oder „6543“ sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.recent_year'] = 'Kürzliche Jahreszahlen sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.date'] = 'Daten sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.top_10'] = 'Dies ist eines der 10 häufigsten Kennwörter.';
$this->items['wcf.user.password.zxcvbn.warnings.top_100'] = 'Dies ist eines der 100 häufigsten Kennwörter.';
$this->items['wcf.user.password.zxcvbn.warnings.common'] = 'Dies ist ein sehr häufiges Kennwort.';
$this->items['wcf.user.password.zxcvbn.warnings.common_alike'] = 'Dies ist ähnlich zu einem sehr häufigen Kennwort.';
$this->items['wcf.user.password.zxcvbn.warnings.sole_word'] = 'Ein einzelnes Wort ist einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.sole_name'] = 'Alleinstehende Namen sind einfach zu erraten.';
$this->items['wcf.user.password.zxcvbn.warnings.name'] = 'Häufige Namen sind einfach zu erraten.';
$this->items['wcf.user.lostPassword'] = 'Kennwort vergessen';
$this->items['wcf.user.lostPassword.email.error.notFound'] = 'Es wurde kein Benutzer mit der E-Mail-Adresse: „{$email}“ gefunden.';
$this->dynamicItems['wcf.user.lostPassword.email.error.notFound'] = 'Es wurde kein Benutzer mit der E-Mail-Adresse: „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'email\']);?>“ gefunden.';
$this->items['wcf.user.lostPassword.error.tooManyRequests'] = 'Das Kennwort für dieses Benutzerkonto wurde in den letzten 24 Stunden bereits einmal angefordert. Aus Sicherheitsgründen kann das Kennwort eines Benutzers nur einmal pro Tag angefordert werden. {if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} das Kennwort für dieses Benutzerkonto in {#$hours} Stunde{if $hours != 1}n{/if} erneut anfordern.';
$this->dynamicItems['wcf.user.lostPassword.error.tooManyRequests'] = 'Das Kennwort für dieses Benutzerkonto wurde in den letzten 24 Stunden bereits einmal angefordert. Aus Sicherheitsgründen kann das Kennwort eines Benutzers nur einmal pro Tag angefordert werden. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst<?php } else { ?>Sie können<?php } ?> das Kennwort für dieses Benutzerkonto in <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'hours\']);?> Stunde<?php if ($this->v[\'hours\'] != 1) { ?>n<?php } ?> erneut anfordern.';
$this->items['wcf.user.lostPassword.error.flood'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} zu viele neue Kennwörter angefordert. Die Funktion wurde daher aus Sicherheitsgründen temporär deaktiviert. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}versuche{else}versuchen Sie{/if} es später erneut.';
$this->dynamicItems['wcf.user.lostPassword.error.flood'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> zu viele neue Kennwörter angefordert. Die Funktion wurde daher aus Sicherheitsgründen temporär deaktiviert. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>versuche<?php } else { ?>versuchen Sie<?php } ?> es später erneut.';
$this->items['wcf.user.lostPassword.mail.subject'] = 'Kennwort vergessen auf der Website: {@PAGE_TITLE|phrase}';
$this->dynamicItems['wcf.user.lostPassword.mail.subject'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>Kennwort vergessen auf der Website: <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this);?>';
$this->items['wcf.user.lostPassword.mail.plaintext'] = 'Hallo {@$mailbox->getUser()->username},

{if LANGUAGE_USE_INFORMAL_VARIANT}du (oder jemand anderes) hat{else}Sie (oder jemand anderes) haben{/if} angegeben, das Kennwort für das Benutzerkonto
{@$mailbox->getUser()->username} auf der Seite {@PAGE_TITLE|phrase} [URL:{link isEmail=true}{/link}] vergessen zu haben. {if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst dein{else}Sie können Ihr{/if} Kennwort
nach einem Klick auf den folgenden Link ändern:

    {link controller=\'NewPassword\' object=$mailbox->getUser() isEmail=true}k={@$mailbox->getUser()->lostPasswordKey}{/link} {* this line ends with a space *}

Wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du dein{else}Sie Ihr{/if} Kennwort nicht ändern {if LANGUAGE_USE_INFORMAL_VARIANT}möchtest{else}möchten{/if}, dann wird diese Anfrage
am {@$mailbox->getUser()->lastLostPasswordRequestTime+86400|plainTime} automatisch ablaufen.';
$this->dynamicItems['wcf.user.lostPassword.mail.plaintext'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin;
}
?>Hallo <?=$this->v[\'mailbox\']->getUser()->username;?>,

<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du (oder jemand anderes) hat<?php } else { ?>Sie (oder jemand anderes) haben<?php } ?> angegeben, das Kennwort für das Benutzerkonto
<?=$this->v[\'mailbox\']->getUser()->username;?> auf der Seite <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this);?> [URL:<?php $this->tagStack[] = [\'link\', [\'isEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>] vergessen zu haben. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst dein<?php } else { ?>Sie können Ihr<?php } ?> Kennwort
nach einem Klick auf den folgenden Link ändern:

    <?php $this->tagStack[] = [\'link\', [\'controller\' => \'NewPassword\', \'object\' => $this->v[\'mailbox\']->getUser(), \'isEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?>k=<?=$this->v[\'mailbox\']->getUser()->lostPasswordKey;?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?> 

Wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du dein<?php } else { ?>Sie Ihr<?php } ?> Kennwort nicht ändern <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>möchtest<?php } else { ?>möchten<?php } ?>, dann wird diese Anfrage
am <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\']->execute([$this->v[\'mailbox\']->getUser()->lastLostPasswordRequestTime+86400], $this);?> automatisch ablaufen.';
$this->items['wcf.user.lostPassword.mail.html.headline'] = 'Hallo {$mailbox->getUser()->username},';
$this->dynamicItems['wcf.user.lostPassword.mail.html.headline'] = 'Hallo <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'mailbox\']->getUser()->username);?>,';
$this->items['wcf.user.lostPassword.mail.html.intro'] = '
<p>{if LANGUAGE_USE_INFORMAL_VARIANT}du (oder jemand anderes) hat{else}Sie (oder jemand anderes) haben{/if} angegeben, das
Kennwort für das Benutzerkonto {$mailbox->getUser()->username} auf der Seite <a href="{link isHtmlEmail=true}{/link}">{PAGE_TITLE|phrase}</a> vergessen zu
haben:</p>';
$this->dynamicItems['wcf.user.lostPassword.mail.html.intro'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>
<p><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du (oder jemand anderes) hat<?php } else { ?>Sie (oder jemand anderes) haben<?php } ?> angegeben, das
Kennwort für das Benutzerkonto <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'mailbox\']->getUser()->username);?> auf der Seite <a href="<?php $this->tagStack[] = [\'link\', [\'isHtmlEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>"><?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this));?></a> vergessen zu
haben:</p>';
$this->items['wcf.user.lostPassword.mail.html.reset'] = 'Kennwort ändern';
$this->items['wcf.user.lostPassword.mail.html.outro'] = '
<p>Wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du dein{else}Sie Ihr{/if} Kennwort nicht ändern {if LANGUAGE_USE_INFORMAL_VARIANT}möchtest{else}möchten{/if},
dann wird diese Anfrage am {$mailbox->getUser()->lastLostPasswordRequestTime+86400|plainTime} automatisch ablaufen.</p>';
$this->dynamicItems['wcf.user.lostPassword.mail.html.outro'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin;
}
?>
<p>Wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du dein<?php } else { ?>Sie Ihr<?php } ?> Kennwort nicht ändern <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>möchtest<?php } else { ?>möchten<?php } ?>,
dann wird diese Anfrage am <?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\']->execute([$this->v[\'mailbox\']->getUser()->lastLostPasswordRequestTime+86400], $this));?> automatisch ablaufen.</p>';
$this->items['wcf.user.lostPassword.mail.sent'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du erhältst{else}Sie erhalten{/if} in Kürze eine E-Mail mit weiteren Informationen.';
$this->dynamicItems['wcf.user.lostPassword.mail.sent'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du erhältst<?php } else { ?>Sie erhalten<?php } ?> in Kürze eine E-Mail mit weiteren Informationen.';
$this->items['wcf.user.lostPasswordKey'] = 'Sicherheitsschlüssel';
$this->items['wcf.user.lostPasswordKey.error.invalid'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Sicherheitsschlüssel angegeben.';
$this->dynamicItems['wcf.user.lostPasswordKey.error.invalid'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Sicherheitsschlüssel angegeben.';
$this->items['wcf.user.newPassword'] = 'Neues Kennwort';
$this->items['wcf.user.newPassword.info'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du bist{else}Sie sind{/if} im Begriff das Kennwort des Benutzers „{$user->username}“ zu ändern.';
$this->dynamicItems['wcf.user.newPassword.info'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du bist<?php } else { ?>Sie sind<?php } ?> im Begriff das Kennwort des Benutzers „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->username);?>“ zu ändern.';
$this->items['wcf.user.newPassword.success'] = 'Das Kennwort des Benutzers „{$user->username}“ wurde erfolgreich geändert. {if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst dich{else}Sie können sich{/if} nun mit dem neuen Kennwort anmelden.';
$this->dynamicItems['wcf.user.newPassword.success'] = 'Das Kennwort des Benutzers „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->username);?>“ wurde erfolgreich geändert. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst dich<?php } else { ?>Sie können sich<?php } ?> nun mit dem neuen Kennwort anmelden.';
$this->items['wcf.user.newPassword.error.invalidLink'] = 'Der aufgerufene Link zur Festlegung eines neuen Kennwortes ist nicht mehr gültig. Aus Sicherheitsgründen ist dieser Link zeitlich beschränkt und kann nur einmalig verwendet werden. {if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} über die folgende Seite einen neuen Link anfordern: <a href="{link controller=\'LostPassword\'}{/link}">Kennwort vergessen</a>';
$this->dynamicItems['wcf.user.newPassword.error.invalidLink'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Der aufgerufene Link zur Festlegung eines neuen Kennwortes ist nicht mehr gültig. Aus Sicherheitsgründen ist dieser Link zeitlich beschränkt und kann nur einmalig verwendet werden. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst<?php } else { ?>Sie können<?php } ?> über die folgende Seite einen neuen Link anfordern: <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'LostPassword\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Kennwort vergessen</a>';
$this->items['wcf.user.userID.error.invalid'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} eine ungültige Benutzer-ID angegeben.';
$this->dynamicItems['wcf.user.userID.error.invalid'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> eine ungültige Benutzer-ID angegeben.';
$this->items['wcf.user.accountManagement'] = 'Benutzerkonto-Verwaltung';
$this->items['wcf.user.accountManagement.warning'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du bearbeitest dein{else}Sie bearbeiten Ihr{/if} eigenes Benutzerkonto. Unbedachte Änderungen können dazu führen, dass {if LANGUAGE_USE_INFORMAL_VARIANT}du dich nicht mehr anmelden kannst. Bitte sei entsprechend vorsichtig!{else}Sie sich nicht mehr anmelden können. Bitte seien Sie entsprechend vorsichtig!{/if}';
$this->dynamicItems['wcf.user.accountManagement.warning'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du bearbeitest dein<?php } else { ?>Sie bearbeiten Ihr<?php } ?> eigenes Benutzerkonto. Unbedachte Änderungen können dazu führen, dass <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du dich nicht mehr anmelden kannst. Bitte sei entsprechend vorsichtig!<?php } else { ?>Sie sich nicht mehr anmelden können. Bitte seien Sie entsprechend vorsichtig!<?php } ?>';
$this->items['wcf.user.accountManagement.password.description'] = 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}gib zur Bestätigung dein{else}geben Sie zur Bestätigung Ihr{/if} <u>bisheriges</u> Kennwort ein!';
$this->dynamicItems['wcf.user.accountManagement.password.description'] = 'Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>gib zur Bestätigung dein<?php } else { ?>geben Sie zur Bestätigung Ihr<?php } ?> <u>bisheriges</u> Kennwort ein!';
$this->items['wcf.user.changeUsername'] = 'Benutzernamen ändern';
$this->items['wcf.user.changeUsername.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst deinen{else}Sie können Ihren{/if} Benutzernamen nur einmal alle {$renamePeriod} Tage ändern. Änderungen von Groß- auf Kleinschreibung und umgekehrt sind jederzeit möglich.
		{if $__wcf->getUser()->lastUsernameChange}Die letzte Änderung erfolgte am {@$__wcf->getUser()->lastUsernameChange|date}.{/if}';
$this->dynamicItems['wcf.user.changeUsername.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst deinen<?php } else { ?>Sie können Ihren<?php } ?> Benutzernamen nur einmal alle <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'renamePeriod\']);?> Tage ändern. Änderungen von Groß- auf Kleinschreibung und umgekehrt sind jederzeit möglich.
		<?php if ($this->v[\'__wcf\']->getUser()->lastUsernameChange) { ?>Die letzte Änderung erfolgte am <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'__wcf\']->getUser()->lastUsernameChange], $this);?>.<?php } ?>';
$this->items['wcf.user.changePassword'] = 'Kennwort ändern';
$this->items['wcf.user.changeEmail'] = 'E-Mail-Adresse ändern';
$this->items['wcf.user.newEmail'] = 'Neue E-Mail-Adresse';
$this->items['wcf.user.newUsername'] = 'Neuer Benutzername';
$this->items['wcf.user.quit'] = 'Benutzerkonto kündigen';
$this->items['wcf.user.quit.sure'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du dein{else}Wollen Sie Ihr{/if} Benutzerkonto mitsamt {if LANGUAGE_USE_INFORMAL_VARIANT}deiner{else}Ihrer{/if} persönlichen Daten dauerhaft löschen?';
$this->dynamicItems['wcf.user.quit.sure'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du dein<?php } else { ?>Wollen Sie Ihr<?php } ?> Benutzerkonto mitsamt <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deiner<?php } else { ?>Ihrer<?php } ?> persönlichen Daten dauerhaft löschen?';
$this->items['wcf.user.quit.cancel'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto wird am {$quitStarted+7*86400|date} gelöscht. {if LANGUAGE_USE_INFORMAL_VARIANT}Bitte aktiviere diese Option, wenn du die Löschung abbrechen möchtest.{else}Bitte aktivieren Sie diese Option, wenn Sie die Löschung abbrechen möchten.{/if}';
$this->dynamicItems['wcf.user.quit.cancel'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto wird am <?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'quitStarted\']+7*86400], $this));?> gelöscht. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Bitte aktiviere diese Option, wenn du die Löschung abbrechen möchtest.<?php } else { ?>Bitte aktivieren Sie diese Option, wenn Sie die Löschung abbrechen möchten.<?php } ?>';
$this->items['wcf.user.quit.description'] = 'Hinweis: Beiträge, Anhänge und Ähnliches werden nicht gelöscht.';
$this->items['wcf.user.quit.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto wird am {TIME_NOW+7*86400|date} gelöscht. Bis dahin {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} die Löschung auf dieser Seite abbrechen.';
$this->dynamicItems['wcf.user.quit.success'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto wird am <?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([TIME_NOW+7*86400], $this));?> gelöscht. Bis dahin <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> die Löschung auf dieser Seite abbrechen.';
$this->items['wcf.user.quit.cancel.success'] = 'Die Löschung {if LANGUAGE_USE_INFORMAL_VARIANT}deines{else}Ihres{/if} Benutzerkontos wurde erfolgreich abgebrochen.';
$this->dynamicItems['wcf.user.quit.cancel.success'] = 'Die Löschung <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deines<?php } else { ?>Ihres<?php } ?> Benutzerkontos wurde erfolgreich abgebrochen.';
$this->items['wcf.user.quit.active'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto wird am {$__wcf->user->quitStarted+7*86400|date} gelöscht. Bis dahin {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} die Löschung in der <a href="{link controller=\'AccountManagement\'}{/link}">Benutzerkonto-Verwaltung</a> abbrechen.';
$this->dynamicItems['wcf.user.quit.active'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto wird am <?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'__wcf\']->user->quitStarted+7*86400], $this));?> gelöscht. Bis dahin <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> die Löschung in der <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'AccountManagement\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Benutzerkonto-Verwaltung</a> abbrechen.';
$this->items['wcf.user.emailActivation'] = 'Neue E-Mail-Adresse aktivieren';
$this->items['wcf.user.password.error.notSecure'] = 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}wähle{else}wählen Sie{/if} ein sichereres Kennwort aus.';
$this->dynamicItems['wcf.user.password.error.notSecure'] = 'Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>wähle<?php } else { ?>wählen Sie<?php } ?> ein sichereres Kennwort aus.';
$this->items['wcf.user.changeUsername.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzername wurde erfolgreich geändert.';
$this->dynamicItems['wcf.user.changeUsername.success'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzername wurde erfolgreich geändert.';
$this->items['wcf.user.changeEmail.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} E-Mail-Adresse wurde erfolgreich geändert.';
$this->dynamicItems['wcf.user.changeEmail.success'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> E-Mail-Adresse wurde erfolgreich geändert.';
$this->items['wcf.user.changeEmail.needReactivation'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} neue E-Mail-Adresse{if $newEmail|isset} („{$newEmail}“){/if} muss noch aktiviert werden. Dazu wurde eine E-Mail mit einem Aktivierungslink an die neue Adresse gesandt. {if LANGUAGE_USE_INFORMAL_VARIANT}Du musst{else}Sie müssen{/if} diesen Aktivierungslink aufrufen, um die neue E-Mail-Adresse zu aktivieren.';
$this->dynamicItems['wcf.user.changeEmail.needReactivation'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> neue E-Mail-Adresse<?php if (isset($this->v[\'newEmail\'])) { ?> („<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'newEmail\']);?>“)<?php } ?> muss noch aktiviert werden. Dazu wurde eine E-Mail mit einem Aktivierungslink an die neue Adresse gesandt. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du musst<?php } else { ?>Sie müssen<?php } ?> diesen Aktivierungslink aufrufen, um die neue E-Mail-Adresse zu aktivieren.';
$this->items['wcf.user.changeEmail.needReactivation.mail.subject'] = 'Aktivierung der neuen E-Mail-Adresse auf der Website: {@PAGE_TITLE|phrase}';
$this->dynamicItems['wcf.user.changeEmail.needReactivation.mail.subject'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>Aktivierung der neuen E-Mail-Adresse auf der Website: <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this);?>';
$this->items['wcf.user.changeEmail.needReactivation.mail.html.headline'] = 'Hallo {$mailbox->getUser()->username},';
$this->dynamicItems['wcf.user.changeEmail.needReactivation.mail.html.headline'] = 'Hallo <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'mailbox\']->getUser()->username);?>,';
$this->items['wcf.user.changeEmail.needReactivation.mail.html.intro'] = '
<p>{if LANGUAGE_USE_INFORMAL_VARIANT}du hast deine{else}Sie haben Ihre{/if} E-Mail-Adresse auf der Website: <a href="{link isHtmlEmail=true}{/link}">{PAGE_TITLE|phrase}</a> geändert.
Zum Abschließen dieser Änderung {if LANGUAGE_USE_INFORMAL_VARIANT}musst du{else}müssen Sie{/if} einmalig die Gültigkeit der neuen E-Mail-Adresse bestätigen:</p>';
$this->dynamicItems['wcf.user.changeEmail.needReactivation.mail.html.intro'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>
<p><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du hast deine<?php } else { ?>Sie haben Ihre<?php } ?> E-Mail-Adresse auf der Website: <a href="<?php $this->tagStack[] = [\'link\', [\'isHtmlEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>"><?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this));?></a> geändert.
Zum Abschließen dieser Änderung <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>musst du<?php } else { ?>müssen Sie<?php } ?> einmalig die Gültigkeit der neuen E-Mail-Adresse bestätigen:</p>';
$this->items['wcf.user.changeEmail.needReactivation.mail.html.activate'] = 'Neue E-Mail-Adresse aktivieren';
$this->items['wcf.user.changeEmail.needReactivation.mail.html.outro'] = '
<p>{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Aktivierungscode lautet: <kbd>{$mailbox->getUser()->reactivationCode}</kbd>.</p>
<p>{if LANGUAGE_USE_INFORMAL_VARIANT}Wenn du Probleme mit der Aktivierung haben solltest, wende dich{else}Wenn Sie Probleme mit der Aktivierung haben, wenden Sie sich{/if} bitte an den Administrator:
<a href="mailto:{MAIL_ADMIN_ADDRESS}">{MAIL_ADMIN_ADDRESS}</a>. Wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du dich{else}Sie sich{/if} nicht bei uns registriert {if LANGUAGE_USE_INFORMAL_VARIANT}hast{else}haben{/if},
dann {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} diese E-Mail ignorieren.</p>';
$this->dynamicItems['wcf.user.changeEmail.needReactivation.mail.html.outro'] = '
<p><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Aktivierungscode lautet: <kbd><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'mailbox\']->getUser()->reactivationCode);?></kbd>.</p>
<p><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Wenn du Probleme mit der Aktivierung haben solltest, wende dich<?php } else { ?>Wenn Sie Probleme mit der Aktivierung haben, wenden Sie sich<?php } ?> bitte an den Administrator:
<a href="mailto:<?=wcf\\util\\StringUtil::encodeHTML(MAIL_ADMIN_ADDRESS);?>"><?=wcf\\util\\StringUtil::encodeHTML(MAIL_ADMIN_ADDRESS);?></a>. Wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du dich<?php } else { ?>Sie sich<?php } ?> nicht bei uns registriert <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>hast<?php } else { ?>haben<?php } ?>,
dann <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> diese E-Mail ignorieren.</p>';
$this->items['wcf.user.changeEmail.needReactivation.mail.plaintext'] = 'Hallo {@$mailbox->getUser()->username},

{if LANGUAGE_USE_INFORMAL_VARIANT}du hast deine{else}Sie haben Ihre{/if} E-Mail-Adresse auf der Website: {@PAGE_TITLE|phrase} [URL:{link isEmail=true}{/link}] geändert.
Zum Abschließen dieser Änderung {if LANGUAGE_USE_INFORMAL_VARIANT}musst du{else}müssen Sie{/if} einmalig die Gültigkeit der neuen E-Mail-Adresse bestätigen:

    {link controller=\'EmailActivation\' isEmail=true}u={@$mailbox->getUser()->userID}&a={@$mailbox->getUser()->reactivationCode}{/link} {* this line ends with a space *}

{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Aktivierungscode lautet: {@$mailbox->getUser()->reactivationCode} {* this line ends with a space *}

{if LANGUAGE_USE_INFORMAL_VARIANT}Wenn du Probleme mit der Aktivierung haben solltest, wende dich{else}Wenn Sie Probleme mit der Aktivierung haben, wenden Sie sich{/if} bitte an den Administrator: {@MAIL_ADMIN_ADDRESS}. Wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du
dich{else}Sie
sich{/if} nicht bei uns registriert {if LANGUAGE_USE_INFORMAL_VARIANT}hast{else}haben{/if}, dann {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} diese E-Mail ignorieren.';
$this->dynamicItems['wcf.user.changeEmail.needReactivation.mail.plaintext'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Hallo <?=$this->v[\'mailbox\']->getUser()->username;?>,

<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du hast deine<?php } else { ?>Sie haben Ihre<?php } ?> E-Mail-Adresse auf der Website: <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([PAGE_TITLE], $this);?> [URL:<?php $this->tagStack[] = [\'link\', [\'isEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>] geändert.
Zum Abschließen dieser Änderung <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>musst du<?php } else { ?>müssen Sie<?php } ?> einmalig die Gültigkeit der neuen E-Mail-Adresse bestätigen:

    <?php $this->tagStack[] = [\'link\', [\'controller\' => \'EmailActivation\', \'isEmail\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?>u=<?=$this->v[\'mailbox\']->getUser()->userID;?>&a=<?=$this->v[\'mailbox\']->getUser()->reactivationCode;?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?> 

<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Aktivierungscode lautet: <?=$this->v[\'mailbox\']->getUser()->reactivationCode;?> 

<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Wenn du Probleme mit der Aktivierung haben solltest, wende dich<?php } else { ?>Wenn Sie Probleme mit der Aktivierung haben, wenden Sie sich<?php } ?> bitte an den Administrator: <?=MAIL_ADMIN_ADDRESS;?>. Wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du
dich<?php } else { ?>Sie
sich<?php } ?> nicht bei uns registriert <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>hast<?php } else { ?>haben<?php } ?>, dann <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> diese E-Mail ignorieren.';
$this->items['wcf.user.changePassword.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Kennwort wurde erfolgreich geändert.';
$this->dynamicItems['wcf.user.changePassword.success'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Kennwort wurde erfolgreich geändert.';
$this->items['wcf.user.activationCode'] = 'Aktivierungscode';
$this->items['wcf.user.newActivationCode'] = 'Neuen Aktivierungscode anfordern';
$this->items['wcf.user.registerActivation'] = 'Registrierung abschließen';
$this->items['wcf.user.registerActivation.error.userAlreadyEnabled'] = 'Die E-Mail-Adresse ist bereits aktiviert.';
$this->items['wcf.user.registerActivation.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto wurde erfolgreich freigeschaltet.';
$this->dynamicItems['wcf.user.registerActivation.success'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto wurde erfolgreich freigeschaltet.';
$this->items['wcf.user.registerActivation.success.awaitAdminActivation'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} E-Mail-Adresse wurde erfolgreich bestätigt. {if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} Benutzerkonto muss nun noch von einem Administrator freigeschaltet werden.';
$this->dynamicItems['wcf.user.registerActivation.success.awaitAdminActivation'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> E-Mail-Adresse wurde erfolgreich bestätigt. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> Benutzerkonto muss nun noch von einem Administrator freigeschaltet werden.';
$this->items['wcf.user.activationCode.error.invalid'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Aktivierungscode eingegeben. {if LANGUAGE_USE_INFORMAL_VARIANT}Klicke auf den unten stehenden Link, falls du einen neuen Aktivierungscode anfordern möchtest.{else}Klicken Sie auf den unten stehenden Link, falls Sie einen neuen Aktivierungscode anfordern möchten.{/if}';
$this->dynamicItems['wcf.user.activationCode.error.invalid'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Aktivierungscode eingegeben. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Klicke auf den unten stehenden Link, falls du einen neuen Aktivierungscode anfordern möchtest.<?php } else { ?>Klicken Sie auf den unten stehenden Link, falls Sie einen neuen Aktivierungscode anfordern möchten.<?php } ?>';
$this->items['wcf.user.registerNewActivationCode.email.description'] = 'Optional {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} hier eine neue E-Mail-Adresse eintragen, an die der neue Aktivierungscode gesendet werden soll. {if LANGUAGE_USE_INFORMAL_VARIANT}Lasse{else}Lassen Sie{/if} dieses Feld frei, wenn der Aktivierungscode an die bestehende Adresse geschickt werden soll.';
$this->dynamicItems['wcf.user.registerNewActivationCode.email.description'] = 'Optional <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> hier eine neue E-Mail-Adresse eintragen, an die der neue Aktivierungscode gesendet werden soll. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Lasse<?php } else { ?>Lassen Sie<?php } ?> dieses Feld frei, wenn der Aktivierungscode an die bestehende Adresse geschickt werden soll.';
$this->items['wcf.user.newActivationCode.success'] = 'Eine E-Mail mit dem neuen Aktivierungscode wurde an {$email} versendet.';
$this->dynamicItems['wcf.user.newActivationCode.success'] = 'Eine E-Mail mit dem neuen Aktivierungscode wurde an <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'email\']);?> versendet.';
$this->items['wcf.user.emailActivation.success'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} neue E-Mail-Adresse wurde erfolgreich aktiviert.';
$this->dynamicItems['wcf.user.emailActivation.success'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> neue E-Mail-Adresse wurde erfolgreich aktiviert.';
$this->items['wcf.user.registerActivation.info'] = 'Eine E-Mail mit dem Aktivierungscode wurde an {if LANGUAGE_USE_INFORMAL_VARIANT}deine{else}Ihre{/if} E-Mail-Adresse {$__wcf->user->email} verschickt.';
$this->dynamicItems['wcf.user.registerActivation.info'] = 'Eine E-Mail mit dem Aktivierungscode wurde an <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deine<?php } else { ?>Ihre<?php } ?> E-Mail-Adresse <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'__wcf\']->user->email);?> verschickt.';
$this->items['wcf.user.username.error.alreadyRenamed'] = 'Der Benutzername wurde innerhalb der letzten {#$__wcf->getSession()->getPermission(\'user.profile.renamePeriod\')} Tage bereits einmal verändert.';
$this->dynamicItems['wcf.user.username.error.alreadyRenamed'] = 'Der Benutzername wurde innerhalb der letzten <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'__wcf\']->getSession()->getPermission(\'user.profile.renamePeriod\'));?> Tage bereits einmal verändert.';
$this->items['wcf.user.guest'] = 'Gast';
$this->items['wcf.user.signature'] = 'Signatur';
$this->items['wcf.user.signature.current'] = 'Aktuelle Signatur';
$this->items['wcf.user.signature.error.disabled'] = 'Der Administrator hat{if $__wcf->user->signature} {if LANGUAGE_USE_INFORMAL_VARIANT}deine{else}Ihre{/if} derzeitige Signatur gesperrt und{/if} {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} die weitere Nutzungsberechtigung der Signatur-Funktion {if !$__wcf->user->disableSignatureReason}entzogen.{else} aus folgenden Gründen entzogen: {$__wcf->user->disableSignatureReason}{/if}';
$this->dynamicItems['wcf.user.signature.error.disabled'] = 'Der Administrator hat<?php if ($this->v[\'__wcf\']->user->signature) { ?> <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deine<?php } else { ?>Ihre<?php } ?> derzeitige Signatur gesperrt und<?php } ?> <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> die weitere Nutzungsberechtigung der Signatur-Funktion <?php if ( ! $this->v[\'__wcf\']->user->disableSignatureReason) { ?>entzogen.<?php } else { ?> aus folgenden Gründen entzogen: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'__wcf\']->user->disableSignatureReason);?><?php } ?>';
$this->items['wcf.user.activityPoint'] = 'Punkte';
$this->items['wcf.user.activityPoint.showActivityPoints'] = 'Punkte von {$user->username} anzeigen';
$this->dynamicItems['wcf.user.activityPoint.showActivityPoints'] = 'Punkte von <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->username);?> anzeigen';
$this->items['wcf.user.activityPoint.objects'] = 'Anzahl';
$this->items['wcf.user.activityPoint.objectType'] = 'Art';
$this->items['wcf.user.activityPoint.pointsPerObject'] = 'Punkte';
$this->items['wcf.user.activityPoint.sum'] = 'Summe';
$this->items['wcf.user.usercp'] = 'Benutzerkonto';
$this->items['wcf.user.button.mail'] = 'E-Mail senden';
$this->items['wcf.user.ignoredUsers.noUsers'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du blockierst{else}Sie blockieren{/if} derzeit keine Benutzer.';
$this->dynamicItems['wcf.user.ignoredUsers.noUsers'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du blockierst<?php } else { ?>Sie blockieren<?php } ?> derzeit keine Benutzer.';
$this->items['wcf.user.following.noUsers'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du folgst{else}Sie folgen{/if} derzeit keinen Benutzern.';
$this->dynamicItems['wcf.user.following.noUsers'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du folgst<?php } else { ?>Sie folgen<?php } ?> derzeit keinen Benutzern.';
$this->items['wcf.user.userTitle'] = 'Individueller Benutzertitel';
$this->items['wcf.user.userTitle.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst dir{else}Sie können sich{/if} einen individuellen Benutzertitel geben.';
$this->dynamicItems['wcf.user.userTitle.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst dir<?php } else { ?>Sie können sich<?php } ?> einen individuellen Benutzertitel geben.';
$this->items['wcf.user.userTitle.error.tooLong'] = 'Der eingegebene Titel ist zu lang. Die maximal zulässige Gesamtlänge beträgt {#USER_TITLE_MAX_LENGTH} Zeichen.';
$this->dynamicItems['wcf.user.userTitle.error.tooLong'] = 'Der eingegebene Titel ist zu lang. Die maximal zulässige Gesamtlänge beträgt <?=wcf\\util\\StringUtil::formatNumeric((float)USER_TITLE_MAX_LENGTH);?> Zeichen.';
$this->items['wcf.user.userTitle.error.forbidden'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Benutzertitel eingegeben.';
$this->dynamicItems['wcf.user.userTitle.error.forbidden'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Benutzertitel eingegeben.';
$this->items['wcf.user.birthday.age'] = 'Alter';
$this->items['wcf.user.birthday.age.from'] = 'von';
$this->items['wcf.user.birthday.age.to'] = 'bis';
$this->items['wcf.user.search'] = 'Mitgliedersuche';
$this->items['wcf.user.search.error.noMatches'] = 'Zu den angegebenen Kriterien wurde kein Mitglied gefunden.';
$this->items['wcf.user.newestMember'] = 'Neuestes Mitglied';
$this->items['wcf.user.search.results'] = 'Suchergebnisse';
$this->items['wcf.user.lastActivityTime'] = 'Letzte Aktivität';
$this->items['wcf.user.activityPoint.objectType.com.woltlab.wcf.like.activityPointEvent.receivedLikes'] = 'Erhaltene Reaktionen';
$this->items['wcf.user.searchUserContent'] = 'Inhalte suchen';
$this->items['wcf.user.author'] = 'Autor';
$this->items['wcf.user.moderate'] = 'Benutzer moderieren';
$this->items['wcf.user.ban'] = 'Benutzer sperren';
$this->items['wcf.user.ban.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} den Benutzer wirklich sperren?';
$this->dynamicItems['wcf.user.ban.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> den Benutzer wirklich sperren?';
$this->items['wcf.user.ban.expires'] = 'Entsperrung';
$this->items['wcf.user.ban.expires.description'] = 'Der Benutzer wird zum festgelegten Zeitpunkt automatisch entsperrt.';
$this->items['wcf.user.ban.neverExpires'] = 'Dauerhafte Sperrung';
$this->items['wcf.user.ban.reason.description'] = 'Die Begründung wird dem gesperrten Benutzer beim Aufruf der Seite angezeigt.';
$this->items['wcf.user.unban'] = 'Benutzer entsperren';
$this->items['wcf.user.disableAvatar'] = 'Avatar sperren';
$this->items['wcf.user.disableAvatar.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} den Avatar des Benutzers wirklich sperren?';
$this->dynamicItems['wcf.user.disableAvatar.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> den Avatar des Benutzers wirklich sperren?';
$this->items['wcf.user.disableAvatar.expires'] = 'Entsperrung';
$this->items['wcf.user.disableAvatar.expires.description'] = 'Der Avatar des Benutzer wird zum festgelegten Zeitpunkt automatisch entsperrt.';
$this->items['wcf.user.disableAvatar.neverExpires'] = 'Dauerhafte Sperrung';
$this->items['wcf.user.enableAvatar'] = 'Avatar entsperren';
$this->items['wcf.user.disableCoverPhoto'] = 'Titelbild sperren';
$this->items['wcf.user.disableCoverPhoto.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} das Titelbild des Benutzers wirklich sperren?';
$this->dynamicItems['wcf.user.disableCoverPhoto.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> das Titelbild des Benutzers wirklich sperren?';
$this->items['wcf.user.disableCoverPhoto.expires'] = 'Entsperrung';
$this->items['wcf.user.disableCoverPhoto.expires.description'] = 'Das Titelbild des Benutzer wird zum festgelegten Zeitpunkt automatisch entsperrt.';
$this->items['wcf.user.disableCoverPhoto.neverExpires'] = 'Dauerhafte Sperrung';
$this->items['wcf.user.enableCoverPhoto'] = 'Titelbild entsperren';
$this->items['wcf.user.disableSignature'] = 'Signatur sperren';
$this->items['wcf.user.disableSignature.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} die Signatur des Benutzers wirklich sperren?';
$this->dynamicItems['wcf.user.disableSignature.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> die Signatur des Benutzers wirklich sperren?';
$this->items['wcf.user.disableSignature.expires'] = 'Entsperrung';
$this->items['wcf.user.disableSignature.expires.description'] = 'Die Signatur des Benutzer wird zum festgelegten Zeitpunkt automatisch entsperrt.';
$this->items['wcf.user.disableSignature.neverExpires'] = 'Dauerhafte Sperrung';
$this->items['wcf.user.enableSignature'] = 'Signatur entsperren';
$this->items['wcf.user.edit'] = 'Benutzer bearbeiten';
$this->items['wcf.user.birthdayToday'] = 'Hat heute Geburtstag';
$this->items['wcf.user.login.blocked'] = 'Aufgrund einer hohen Anzahl von fehlgeschlagenen Anmeldeversuchen durch {if LANGUAGE_USE_INFORMAL_VARIANT}deine{else}Ihre{/if} IP-Adresse steht {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} die Anmeldung aus Sicherheitsgründen vorübergehend nicht zur Verfügung. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}versuche{else}versuchen Sie{/if} es später erneut!';
$this->dynamicItems['wcf.user.login.blocked'] = 'Aufgrund einer hohen Anzahl von fehlgeschlagenen Anmeldeversuchen durch <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deine<?php } else { ?>Ihre<?php } ?> IP-Adresse steht <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> die Anmeldung aus Sicherheitsgründen vorübergehend nicht zur Verfügung. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>versuche<?php } else { ?>versuchen Sie<?php } ?> es später erneut!';
$this->items['wcf.user.banned'] = 'Der Benutzer {$user->username} wurde{if $user->banExpires != 0} bis zum {@$user->banExpires|date}{/if} gesperrt.';
$this->dynamicItems['wcf.user.banned'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateModifierTemplatePlugin;
}
?>Der Benutzer <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->username);?> wurde<?php if ($this->v[\'user\']->banExpires != 0) { ?> bis zum <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateModifierTemplatePlugin\']->execute([$this->v[\'user\']->banExpires], $this);?><?php } ?> gesperrt.';
$this->items['wcf.user.panel.settings'] = 'Einstellungen';
$this->items['wcf.user.panel.showAll'] = 'Alle anzeigen';
$this->items['wcf.user.boxList.description.activityPoints'] = '{#$boxUser->activityPoints} Punkt{if $boxUser->activityPoints != 1}e{/if}';
$this->dynamicItems['wcf.user.boxList.description.activityPoints'] = '<?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'boxUser\']->activityPoints);?> Punkt<?php if ($this->v[\'boxUser\']->activityPoints != 1) { ?>e<?php } ?>';
$this->items['wcf.user.boxList.description.likesReceived'] = '{#$boxUser->likesReceived} Like{if $boxUser->likesReceived != 1}s{/if}';
$this->dynamicItems['wcf.user.boxList.description.likesReceived'] = '<?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'boxUser\']->likesReceived);?> Like<?php if ($this->v[\'boxUser\']->likesReceived != 1) { ?>s<?php } ?>';
$this->items['wcf.user.boxList.description.registrationDate'] = '{@$boxUser->registrationDate|time}';
$this->dynamicItems['wcf.user.boxList.description.registrationDate'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin;
}
?><?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\']->execute([$this->v[\'boxUser\']->registrationDate], $this);?>';
$this->items['wcf.user.mostOnlineUsers'] = 'Meiste Benutzer online';
$this->items['wcf.user.sortField.activityPoints'] = 'Punkte';
$this->items['wcf.user.sortField.likesReceived'] = 'Erhaltene Reaktionen';
$this->items['wcf.user.sortField.registrationDate'] = 'Registrierungsdatum';
$this->items['wcf.user.sortField.username'] = 'Benutzername';
$this->items['wcf.user.sortField.lastActivityTime'] = 'Letzte Aktivität';
$this->items['wcf.user.articles'] = 'Artikel';
$this->items['wcf.user.status.banned'] = 'Der Benutzer ist gesperrt.';
$this->items['wcf.user.status.isDisabled'] = 'Der Benutzer ist nicht freigeschaltet.';
$this->items['wcf.user.status.blacklistMatches'] = 'Der Benutzer wurde aufgrund eines Treffers in der Datenbank von „Stop Forum Spam“ automatisch deaktiviert (Übereinstimmungen: {implode glue=\', \' from=$user->getBlacklistMatchesTitle() item=matchLabel}{$matchLabel}{/implode}).';
$this->dynamicItems['wcf.user.status.blacklistMatches'] = 'Der Benutzer wurde aufgrund eines Treffers in der Datenbank von „Stop Forum Spam“ automatisch deaktiviert (Übereinstimmungen: <?php
$_length87c64f16d038188044aaf61ebf8740bd4c1cb675 = count($this->v[\'user\']->getBlacklistMatchesTitle());
$_i87c64f16d038188044aaf61ebf8740bd4c1cb675 = 0;
$_item87c64f16d038188044aaf61ebf8740bd4c1cb675 = $this->v[\'matchLabel\'] ?? null;
$_key87c64f16d038188044aaf61ebf8740bd4c1cb675 =  null;
foreach ($this->v[\'user\']->getBlacklistMatchesTitle() as $this->v[\'matchLabel\']) { ?><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'matchLabel\']);?><?php
if (++$_i87c64f16d038188044aaf61ebf8740bd4c1cb675 < $_length87c64f16d038188044aaf61ebf8740bd4c1cb675) { echo \', \'; }
}
unset($this->v[\'matchLabel\']);$this->v[\'matchLabel\'] = $_item87c64f16d038188044aaf61ebf8740bd4c1cb675;
unset($_length87c64f16d038188044aaf61ebf8740bd4c1cb675, $_i87c64f16d038188044aaf61ebf8740bd4c1cb675);
unset($_item87c64f16d038188044aaf61ebf8740bd4c1cb675, $_key87c64f16d038188044aaf61ebf8740bd4c1cb675);
?>).';
$this->items['wcf.user.reauthentication'] = 'Erneute Authentifizierung';
$this->items['wcf.user.reauthentication.explanation'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du betrittst einen besonders geschützten Bereich. Aus Sicherheitsgründen ist es notwendig, dass du dich durch Eingabe deines Kennworts erneut authentifizierst.{else}Sie betreten einen besonders geschützten Bereich. Aus Sicherheitsgründen ist es notwendig, dass Sie sich durch Eingabe Ihres Kennworts erneut authentifizieren.{/if}';
$this->dynamicItems['wcf.user.reauthentication.explanation'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du betrittst einen besonders geschützten Bereich. Aus Sicherheitsgründen ist es notwendig, dass du dich durch Eingabe deines Kennworts erneut authentifizierst.<?php } else { ?>Sie betreten einen besonders geschützten Bereich. Aus Sicherheitsgründen ist es notwendig, dass Sie sich durch Eingabe Ihres Kennworts erneut authentifizieren.<?php } ?>';
$this->items['wcf.user.reauthentication.loginAs'] = 'Angemeldet als';
$this->items['wcf.user.reauthentication.logoutAndChangeUser'] = 'Nicht {$__wcf->user->username}? <a href="{link controller=\'FullLogout\' application=\'wcf\'}t={csrfToken type=\'url\'}{/link}">Abmelden und Benutzer wechseln</a>.';
$this->dynamicItems['wcf.user.reauthentication.logoutAndChangeUser'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\CsrfTokenFunctionTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\CsrfTokenFunctionTemplatePlugin\'] = new wcf\\system\\template\\plugin\\CsrfTokenFunctionTemplatePlugin;
}
?>Nicht <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'__wcf\']->user->username);?>? <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'FullLogout\', \'application\' => \'wcf\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?>t=<?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\CsrfTokenFunctionTemplatePlugin\']->execute([\'type\' => \'url\'], $this);?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Abmelden und Benutzer wechseln</a>.';
$this->items['wcf.user.ignore.type'] = 'Benutzer blockieren';
$this->items['wcf.user.ignore.type.noIgnore'] = 'Nicht blockieren';
$this->items['wcf.user.ignore.type.blockDirectContact'] = 'Direkten Kontakt blockieren';
$this->items['wcf.user.ignore.type.hideMessages'] = 'Direkten Kontakt blockieren und erstellte Inhalte ausblenden';
$this->items['wcf.user.ignore.error.cannotBeIgnored'] = 'Der Benutzer kann nicht blockiert werden.';
$this->items['wcf.user.reactionsReceived'] = 'Reaktionen';
