<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.menu
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.menu.page'] = 'Menü';
$this->items['wcf.menu.page.button.toggle'] = 'Weitere {$title} Seiten';
$this->dynamicItems['wcf.menu.page.button.toggle'] = 'Weitere <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'title\']);?> Seiten';
$this->items['wcf.menu.page.location'] = 'Aktueller Ort';
$this->items['wcf.menu.page.navigation'] = 'Navigation';
$this->items['wcf.menu.page.options'] = 'Optionen';
$this->items['wcf.menu.user'] = 'Benutzer-Menü';
$this->items['wcf.menu.com.woltlab.wcf.MainMenu'] = 'Hauptmenü';
$this->items['wcf.menu.com.woltlab.wcf.FooterMenu'] = 'Footer-Menü';
$this->items['wcf.menu.com.woltlab.wcf.FooterLinks'] = 'Footer-Links';
$this->items['wcf.menu.item.com.woltlab.wcf.Dashboard'] = 'Dashboard';
$this->items['wcf.menu.item.com.woltlab.wcf.ArticleList'] = 'Artikel';
$this->items['wcf.menu.item.com.woltlab.wcf.UnreadArticleList'] = 'Ungelesene Artikel';
$this->items['wcf.menu.item.com.woltlab.wcf.WatchedArticleList'] = 'Abonnierte Artikel';
$this->items['wcf.menu.item.com.woltlab.wcf.MembersList'] = 'Mitglieder';
$this->items['wcf.menu.item.com.woltlab.wcf.RecentActivityList'] = 'Letzte Aktivitäten';
$this->items['wcf.menu.item.com.woltlab.wcf.UsersOnlineList'] = 'Benutzer online';
$this->items['wcf.menu.item.com.woltlab.wcf.Team'] = 'Team';
$this->items['wcf.menu.item.com.woltlab.wcf.UserSearch'] = 'Mitgliedersuche';
$this->items['wcf.menu.item.com.woltlab.wcf.PrivacyPolicy'] = 'Datenschutzerklärung';
$this->items['wcf.menu.item.com.woltlab.wcf.Contact'] = 'Kontakt';
