<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.search
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.search.author'] = 'Suche nach Autor';
$this->items['wcf.search.extended'] = 'Erweiterte Suche';
$this->items['wcf.search.period'] = 'Im Zeitraum';
$this->items['wcf.search.sortBy'] = 'Sortierung';
$this->items['wcf.search.sortBy.relevance'] = 'Relevanz';
$this->items['wcf.search.sortBy.time'] = 'Datum';
$this->items['wcf.search.sortBy.username'] = 'Autor';
$this->items['wcf.search.searchIn'] = 'Suchen in';
$this->items['wcf.search.searchIn.subjectAndMessage'] = 'Betreff und Nachricht';
$this->items['wcf.search.searchIn.subjectOnly'] = 'Nur Betreff';
$this->items['wcf.search.type'] = 'Art der Inhalte';
$this->items['wcf.search.type.everywhere'] = 'Alles';
$this->items['wcf.search.object.com.woltlab.wcf.article'] = 'Artikel';
$this->items['wcf.search.type.com.woltlab.wcf.article'] = 'Artikel';
$this->items['wcf.search.object.com.woltlab.wcf.page'] = 'Seite';
$this->items['wcf.search.type.com.woltlab.wcf.page'] = 'Seiten';
$this->items['wcf.search.type.tags'] = 'Suche nach Tags';
$this->items['wcf.search.type.tags.popular'] = 'Beliebte Tags';
$this->items['wcf.search.results.title'] = '{plural value=$count 0=\'Keine Ergebnisse\' one=\'Ein Ergebnis\' other=\'# Ergebnisse\'}{if $query} für „{@$query}“{/if}';
$this->dynamicItems['wcf.search.results.title'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PluralFunctionTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PluralFunctionTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PluralFunctionTemplatePlugin;
}
?><?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\PluralFunctionTemplatePlugin\']->execute([\'value\' => $this->v[\'count\'], \'0\' => \'Keine Ergebnisse\', \'one\' => \'Ein Ergebnis\', \'other\' => \'# Ergebnisse\'], $this);?><?php if ($this->v[\'query\']) { ?> für „<?=$this->v[\'query\'];?>“<?php } ?>';
$this->items['wcf.search.button.showMoreFilters'] = 'Erweiterte Filter';
$this->items['wcf.search.searchInCategories'] = 'Folgende Kategorien durchsuchen';
