<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.acp.option
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.acp.option.cache_source_redis_host'] = 'Redis-Server';
$this->items['wcf.acp.option.cache_source_redis_host.description'] = 'Die Adresse des Servers, zum Beispiel „localhost“ oder „10.0.13.37:1337“.';
$this->items['wcf.acp.option.cache_source_type'] = 'Cache-Methode';
$this->items['wcf.acp.option.cache_source_type.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Beachte{else}Beachten Sie{/if}, dass einige Methoden spezielle Anforderungen an das Server-System stellen und nicht auf jedem Server zur Verfügung stehen.';
$this->dynamicItems['wcf.acp.option.cache_source_type.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Beachte<?php } else { ?>Beachten Sie<?php } ?>, dass einige Methoden spezielle Anforderungen an das Server-System stellen und nicht auf jedem Server zur Verfügung stehen.';
$this->items['wcf.acp.option.cache_source_type.disk'] = 'Dateisystem (Standard)';
$this->items['wcf.acp.option.cache_source_type.redis'] = 'Redis';
$this->items['wcf.acp.option.category.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.general.cache'] = 'Cache';
$this->items['wcf.acp.option.category.general.cache.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.general.cache.redis'] = 'Redis';
$this->items['wcf.acp.option.category.general.cache.redis.description'] = 'Redis speichert häufig benötigte Daten im Arbeitsspeicher zwischen. Dies kann die Last auf die Datenbank und das Dateisystem drastisch reduzieren. {if LANGUAGE_USE_INFORMAL_VARIANT}Lies{else}Lesen Sie{/if} mehr über dieses Thema auf der folgenden Seite: <a href="https://redis.io/" class="externalURL">redis.io</a>.';
$this->dynamicItems['wcf.acp.option.category.general.cache.redis.description'] = 'Redis speichert häufig benötigte Daten im Arbeitsspeicher zwischen. Dies kann die Last auf die Datenbank und das Dateisystem drastisch reduzieren. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Lies<?php } else { ?>Lesen Sie<?php } ?> mehr über dieses Thema auf der folgenden Seite: <a href="https://redis.io/" class="externalURL">redis.io</a>.';
$this->items['wcf.acp.option.category.general.system.date'] = 'Datum &amp; Zeit';
$this->items['wcf.acp.option.category.general.system.image'] = 'Grafik';
$this->items['wcf.acp.option.category.general.system'] = 'System';
$this->items['wcf.acp.option.category.general.system.error'] = 'Fehlermeldungen';
$this->items['wcf.acp.option.category.general.system.cookie'] = 'Cookies';
$this->items['wcf.acp.option.category.general.system.http'] = 'HTTP';
$this->items['wcf.acp.option.category.general.system.proxy'] = 'Proxy-Server';
$this->items['wcf.acp.option.category.general.system.proxy.description'] = 'Hier {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} optional Proxy-Server für Verbindungen zu externen Servern konfigurieren.';
$this->dynamicItems['wcf.acp.option.category.general.system.proxy.description'] = 'Hier <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> optional Proxy-Server für Verbindungen zu externen Servern konfigurieren.';
$this->items['wcf.acp.option.category.general.system.search'] = 'Suche';
$this->items['wcf.acp.option.category.general.system.search.description'] = 'Die Änderung des Backends erfordert die Aktualisierung des Such-Index über die Seite „Anzeigen aktualisieren“.';
$this->items['wcf.acp.option.category.general.mail'] = 'E-Mails';
$this->items['wcf.acp.option.category.general.mail.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.general.mail.send'] = 'Versand';
$this->items['wcf.acp.option.category.general.page'] = 'Seite';
$this->items['wcf.acp.option.category.general.page.seo'] = 'Suchmaschinenoptimierung (SEO)';
$this->items['wcf.acp.option.category.general.page.sitemap'] = 'Sitemap';
$this->items['wcf.acp.option.category.message'] = 'Nachrichten';
$this->items['wcf.acp.option.category.message.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.module'] = 'Module';
$this->items['wcf.acp.option.category.module.content'] = 'Inhalte';
$this->items['wcf.acp.option.category.module.user'] = 'Benutzer';
$this->items['wcf.acp.option.category.module.system'] = 'System';
$this->items['wcf.acp.option.category.module.community'] = 'Community';
$this->items['wcf.acp.option.category.module.customization'] = 'Anpassung';
$this->items['wcf.acp.option.category.security'] = 'Sicherheit';
$this->items['wcf.acp.option.category.security.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.security.general.session'] = 'Sitzungen';
$this->items['wcf.acp.option.category.security.general.secrets'] = 'Geheimschlüssel';
$this->items['wcf.acp.option.category.general.offline'] = 'Wartungsmodus';
$this->items['wcf.acp.option.category.user'] = 'Benutzer';
$this->items['wcf.acp.option.category.user.general'] = 'Allgemein';
$this->items['wcf.acp.option.category.security.antispam'] = 'Anti-Spam';
$this->items['wcf.acp.option.category.security.censorship'] = 'Zensur';
$this->items['wcf.acp.option.exception_privacy'] = 'Privatsphäre';
$this->items['wcf.acp.option.exception_privacy.description'] = 'Gibt an, wie detailliert die Fehlermeldungen sind. „Privat“ versteckt Fehler vollständig, „Gekürzt“ versucht private Informationen zu verstecken und „Öffentlich“ (nur bei aktivem Debug-Modus) zeigt alle Informationen an.';
$this->items['wcf.acp.option.exception_privacy.public'] = 'Öffentlich';
$this->items['wcf.acp.option.exception_privacy.reduced'] = 'Gekürzt';
$this->items['wcf.acp.option.exception_privacy.private'] = 'Privat';
$this->items['wcf.acp.option.cookie_prefix'] = 'Präfix für Cookienamen';
$this->items['wcf.acp.option.error.controllerReplacementCollision'] = 'Das Alias „{$urlControllerReplacementError}“ kollidiert mit einem real existierenden Controller und ist daher unzulässig.';
$this->dynamicItems['wcf.acp.option.error.controllerReplacementCollision'] = 'Das Alias „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'urlControllerReplacementError\']);?>“ kollidiert mit einem real existierenden Controller und ist daher unzulässig.';
$this->items['wcf.acp.option.error.controllerReplacementDuplicateAlias'] = 'Das Alias „{$urlControllerReplacementError}“ wird bereits verwendet.';
$this->dynamicItems['wcf.acp.option.error.controllerReplacementDuplicateAlias'] = 'Das Alias „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'urlControllerReplacementError\']);?>“ wird bereits verwendet.';
$this->items['wcf.acp.option.error.controllerReplacementDuplicateController'] = 'Dem Controller „{$urlControllerReplacementError}“ wurde bereits ein Alias zugewiesen.';
$this->dynamicItems['wcf.acp.option.error.controllerReplacementDuplicateController'] = 'Dem Controller „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'urlControllerReplacementError\']);?>“ wurde bereits ein Alias zugewiesen.';
$this->items['wcf.acp.option.error.controllerReplacementInvalidFormat'] = 'Die Angabe muss im Format „realer-name=neuer-name“ erfolgen, die Zeile „{$urlControllerReplacementError}“ ist ungültig.';
$this->dynamicItems['wcf.acp.option.error.controllerReplacementInvalidFormat'] = 'Die Angabe muss im Format „realer-name=neuer-name“ erfolgen, die Zeile „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'urlControllerReplacementError\']);?>“ ist ungültig.';
$this->items['wcf.acp.option.error.controllerReplacementUnknown'] = 'Der Controller „{$urlControllerReplacementError}“ ist unbekannt.';
$this->dynamicItems['wcf.acp.option.error.controllerReplacementUnknown'] = 'Der Controller „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'urlControllerReplacementError\']);?>“ ist unbekannt.';
$this->items['wcf.acp.option.error.tooHigh'] = 'Der angegebene Wert ist zu hoch.{if $option->maxvalue !== null} Der maximale Wert ist {#$option->maxvalue}.{/if}';
$this->dynamicItems['wcf.acp.option.error.tooHigh'] = 'Der angegebene Wert ist zu hoch.<?php if ($this->v[\'option\']->maxvalue !== null) { ?> Der maximale Wert ist <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'option\']->maxvalue);?>.<?php } ?>';
$this->items['wcf.acp.option.error.tooLow'] = 'Der angegebene Wert ist zu gering.{if $option->minvalue !== null} Der minimale Wert ist {#$option->minvalue}.{/if}';
$this->dynamicItems['wcf.acp.option.error.tooLow'] = 'Der angegebene Wert ist zu gering.<?php if ($this->v[\'option\']->minvalue !== null) { ?> Der minimale Wert ist <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'option\']->minvalue);?>.<?php } ?>';
$this->items['wcf.acp.option.error.tooLong'] = 'Der eingegebene Text ist zu lang.';
$this->items['wcf.acp.option.error.tooShort'] = 'Der eingegebene Text ist zu kurz.';
$this->items['wcf.acp.option.image_adapter_type'] = 'Grafik-Bibliothek';
$this->items['wcf.acp.option.image_adapter_type.gd'] = 'GD Graphics Library (Standard)';
$this->items['wcf.acp.option.image_adapter_type.imagick'] = 'ImageMagick';
$this->items['wcf.acp.option.image_adapter_type.description'] = 'Bibliothek für die Generierung von Grafiken, wird z.B. für die Skalierung von hochgeladenen Bildern verwendet. „ImageMagick“ ist in der Regel deutlich schneller, steht aber nicht auf jedem Server zur Verfügung.';
$this->items['wcf.acp.option.log_ip_address'] = 'Speicherung von IP-Adressen';
$this->items['wcf.acp.option.log_ip_address.description'] = 'Aktiviert die dauerhafte Speicherung von IP-Adressen der Benutzer in z.B. Benutzerprofilen und Forenbeiträgen.';
$this->items['wcf.acp.option.mail_admin_address'] = 'Administrator-Adresse';
$this->items['wcf.acp.option.mail_admin_address.description'] = 'Die Administrator-Adresse ist Ansprechpartner für allgemeine Belange der Community. Sie wird beispielsweise als Empfänger- und Antwort-Adresse für System-E-Mails und als Standard-Kontakt im Kontaktformular verwendet. Die Administrator-Adresse sollte auf ein Postfach zeigen, das E-Mails empfangen kann und regelmäßig überprüft wird.';
$this->items['wcf.acp.option.mail_from_address'] = 'Absender-Adresse';
$this->items['wcf.acp.option.mail_from_address.description'] = 'Absender-Adresse für automatisch generierte E-Mails';
$this->items['wcf.acp.option.mail_from_name'] = 'Absender-Name';
$this->items['wcf.acp.option.mail_from_name.description'] = 'Absender-Name für automatisch generierte E-Mails';
$this->items['wcf.acp.option.mail_send_method'] = 'Versandmethode';
$this->items['wcf.acp.option.mail_send_method.debug'] = 'Debug (mbox)';
$this->items['wcf.acp.option.mail_send_method.debugFolder'] = 'Debug (Ordner mit .eml-Dateien)';
$this->items['wcf.acp.option.mail_send_method.php'] = 'PHP';
$this->items['wcf.acp.option.mail_send_method.smtp'] = 'SMTP (empfohlen)';
$this->items['wcf.acp.option.mail_signature'] = 'Signatur (Text)';
$this->items['wcf.acp.option.mail_signature.description'] = 'Die Signatur wird an jede automatisch generierte E-Mail angehängt.';
$this->items['wcf.acp.option.mail_signature_html'] = 'Signatur (HTML)';
$this->items['wcf.acp.option.mail_signature_html.description'] = 'Die Signatur für die HTML-Version der versendeten E-Mails. Wenn keine HTML-Variante angegeben ist, dann wird die Text-Signatur verwendet.';
$this->items['wcf.acp.option.mail_smtp_host'] = 'SMTP-Server';
$this->items['wcf.acp.option.mail_smtp_host.description'] = 'Bei SMTP-Port 465 muss zusätzlich der Präfix <kbd>ssl://</kbd> angegeben werden, etwa <kbd>ssl://mail.example.com</kbd> statt nur <kbd>mail.example.com</kbd>.';
$this->items['wcf.acp.option.mail_smtp_port'] = 'SMTP-Port';
$this->items['wcf.acp.option.mail_smtp_starttls'] = 'SMTP-Verschlüsselung (STARTTLS)';
$this->items['wcf.acp.option.mail_smtp_starttls.none'] = 'Deaktivieren';
$this->items['wcf.acp.option.mail_smtp_starttls.encrypt'] = 'Erzwingen';
$this->items['wcf.acp.option.mail_smtp_starttls.description'] = 'Diese Einstellung steuert die Verwendung von „STARTTLS“. {if LANGUAGE_USE_INFORMAL_VARIANT}Deaktiviere{else}Deaktivieren Sie{/if} diese Option, wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} E-Mails über SSL (Port 465) {if LANGUAGE_USE_INFORMAL_VARIANT}versendest{else}versenden{/if}!';
$this->dynamicItems['wcf.acp.option.mail_smtp_starttls.description'] = 'Diese Einstellung steuert die Verwendung von „STARTTLS“. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deaktiviere<?php } else { ?>Deaktivieren Sie<?php } ?> diese Option, wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> E-Mails über SSL (Port 465) <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>versendest<?php } else { ?>versenden<?php } ?>!';
$this->items['wcf.acp.option.mail_smtp_user'] = 'SMTP-Benutzer';
$this->items['wcf.acp.option.mail_smtp_password'] = 'SMTP-Kennwort';
$this->items['wcf.acp.option.mail_use_f_param'] = '„-f“ Parameter verwenden';
$this->items['wcf.acp.option.mail_use_f_param.description'] = 'Der „-f“-Parameter sorgt bei der PHP-Versandmethode dafür, dass der korrekte Absender gesetzt wird. Diese Einstellung wird möglicherweise nicht von jedem Server unterstützt. {if LANGUAGE_USE_INFORMAL_VARIANT}Versuche{else}Versuchen Sie{/if} in diesem Falle die Option zu deaktivieren.';
$this->dynamicItems['wcf.acp.option.mail_use_f_param.description'] = 'Der „-f“-Parameter sorgt bei der PHP-Versandmethode dafür, dass der korrekte Absender gesetzt wird. Diese Einstellung wird möglicherweise nicht von jedem Server unterstützt. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Versuche<?php } else { ?>Versuchen Sie<?php } ?> in diesem Falle die Option zu deaktivieren.';
$this->items['wcf.acp.option.meta_description'] = 'Meta Description';
$this->items['wcf.acp.option.og_image'] = 'Standardwert „Open Graph“-Bild';
$this->items['wcf.acp.option.og_image.description'] = 'Pfad zur Bilddatei, die beim Verlinken von Inhalten auf Facebook, X und anderen „Social Media“-Seiten standardmäßig eingebunden wird.';
$this->items['wcf.acp.option.page_description'] = 'Seitenbeschreibung';
$this->items['wcf.acp.option.page_title'] = 'Titel der Seite';
$this->items['wcf.acp.option.proxy_server_http'] = 'Proxy-Server (HTTP)';
$this->items['wcf.acp.option.timezone'] = 'Zeitzone';
$this->items['wcf.acp.option.timezone.description'] = 'Standard-Zeitzone {if LANGUAGE_USE_INFORMAL_VARIANT}deiner{else}Ihrer{/if} Seite';
$this->dynamicItems['wcf.acp.option.timezone.description'] = 'Standard-Zeitzone <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deiner<?php } else { ?>Ihrer<?php } ?> Seite';
$this->items['wcf.acp.option.ip_address_search_engine'] = 'Suchmaschine für IP-Adressen';
$this->items['wcf.acp.option.ip_address_search_engine.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} hier die URL an, die für das Suchen von IP-Adressen hinterlegt werden soll. <span class="inlineCode">%s</span> wird durch die IP-Adresse ersetzt. Wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du dieses Feld leer lässt{else}Sie dieses Feld leer lassen{/if}, wird automatisch auf www.google.com verlinkt.';
$this->dynamicItems['wcf.acp.option.ip_address_search_engine.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> hier die URL an, die für das Suchen von IP-Adressen hinterlegt werden soll. <span class="inlineCode">%s</span> wird durch die IP-Adresse ersetzt. Wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du dieses Feld leer lässt<?php } else { ?>Sie dieses Feld leer lassen<?php } ?>, wird automatisch auf www.google.com verlinkt.';
$this->items['wcf.acp.option.user_online_timeout'] = 'Timeout für Benutzer-Online';
$this->items['wcf.acp.option.user_online_timeout.description'] = 'Zeit in Sekunden, in der der Benutzer trotz Inaktivität als online markiert werden soll.';
$this->items['wcf.acp.option.offline'] = 'Wartungsmodus aktivieren';
$this->items['wcf.acp.option.offline.description'] = 'Deaktiviert alle installierten Apps (z.B. für Wartungsarbeiten).';
$this->items['wcf.acp.option.offline_message'] = 'Wartungshinweis';
$this->items['wcf.acp.option.offline_message.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} hier eine Meldung ein, die angezeigt wird, solange sich die Seite im Wartungsmodus befindet.';
$this->dynamicItems['wcf.acp.option.offline_message.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> hier eine Meldung ein, die angezeigt wird, solange sich die Seite im Wartungsmodus befindet.';
$this->items['wcf.acp.option.offline_message_allow_html'] = 'HTML-Code im Hinweistext verwenden';
$this->items['wcf.acp.option.offline_message_allow_html.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Aktiviere{else}Aktivieren Sie{/if} diese Option, wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} HTML-Code im Hinweistext verwenden {if LANGUAGE_USE_INFORMAL_VARIANT}möchtest{else}möchten{/if}.';
$this->dynamicItems['wcf.acp.option.offline_message_allow_html.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Aktiviere<?php } else { ?>Aktivieren Sie<?php } ?> diese Option, wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> HTML-Code im Hinweistext verwenden <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>möchtest<?php } else { ?>möchten<?php } ?>.';
$this->items['wcf.acp.option.show_version_number'] = 'Versionsnummer der Software im Copyright-Hinweis anzeigen';
$this->items['wcf.acp.option.enable_debug_mode'] = 'Debug-Modus aktivieren';
$this->items['wcf.acp.option.enable_debug_mode.description'] = 'Aktiviert ausführliche Fehlerberichte. Diese Option sollte im Live-Betrieb abgeschaltet werden.';
$this->items['wcf.acp.option.enable_production_debug_mode'] = 'Problemanalyse im Live-Betrieb';
$this->items['wcf.acp.option.enable_production_debug_mode.description'] = 'Hängt die aktuelle URL an Datenbankabfragen an, um diese im Log des Datenbankservers einfacher identifizieren zu können.';
$this->items['wcf.acp.option.external_link_target_blank'] = 'Externe Links in neuem Fenster öffnen';
$this->items['wcf.acp.option.external_link_target_blank.description'] = 'Setzt das Attribut „target="_blank"“ auf externe Links und weist den Browser dadurch an, einen aufgerufenen Link in einem neuen Browser-Fenster zu öffnen.';
$this->items['wcf.acp.option.enable_benchmark'] = 'Benchmark aktivieren';
$this->items['wcf.acp.option.enable_benchmark.description'] = 'Erfasst zusätzliche Daten zur Ressourcennutzung von Komponenten. Diese Option sollte im Live-Betrieb abgeschaltet werden.';
$this->items['wcf.acp.option.category.general.system.packageServer'] = 'Paket-Server';
$this->items['wcf.acp.option.package_server_auth_code'] = 'Authentifizierungs-Code';
$this->items['wcf.acp.option.package_server_auth_code.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deinen{else}Ihren{/if} Authentifizierungs-Code {if LANGUAGE_USE_INFORMAL_VARIANT}findest du{else}finden Sie{/if} in {if LANGUAGE_USE_INFORMAL_VARIANT}deinem{else}Ihrem{/if} Kundenkonto auf woltlab.com.';
$this->dynamicItems['wcf.acp.option.package_server_auth_code.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deinen<?php } else { ?>Ihren<?php } ?> Authentifizierungs-Code <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>findest du<?php } else { ?>finden Sie<?php } ?> in <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deinem<?php } else { ?>Ihrem<?php } ?> Kundenkonto auf woltlab.com.';
$this->items['wcf.acp.option.category.security.antispam.recaptcha'] = 'reCAPTCHA';
$this->items['wcf.acp.option.recaptcha_publickey'] = 'Websiteschlüssel (reCAPTCHA, Version 2)';
$this->items['wcf.acp.option.recaptcha_publickey.description'] = 'Einen eigenen Websiteschlüssel für die Nutzung der reCAPTCHA-Funktion {if LANGUAGE_USE_INFORMAL_VARIANT}kannst du{else}können Sie{/if} auf der Website von <a href="https://www.google.com/recaptcha/admin" class="externalURL">reCAPTCHA</a> beantragen.';
$this->dynamicItems['wcf.acp.option.recaptcha_publickey.description'] = 'Einen eigenen Websiteschlüssel für die Nutzung der reCAPTCHA-Funktion <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst du<?php } else { ?>können Sie<?php } ?> auf der Website von <a href="https://www.google.com/recaptcha/admin" class="externalURL">reCAPTCHA</a> beantragen.';
$this->items['wcf.acp.option.recaptcha_privatekey'] = 'Geheimer Schlüssel (reCAPTCHA, Version 2)';
$this->items['wcf.acp.option.recaptcha_publickey_invisible'] = 'Websiteschlüssel (Unsichtbares reCAPTCHA)';
$this->items['wcf.acp.option.recaptcha_publickey_invisible.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Trage{else}Tragen Sie{/if} hier, <strong>zusätzlich</strong> zu den obigen Schlüsseln, Schlüssel für das unsichtbare reCAPTCHA ein, wenn {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} diese Variante nutzen {if LANGUAGE_USE_INFORMAL_VARIANT}möchtest{else}möchten{/if}.';
$this->dynamicItems['wcf.acp.option.recaptcha_publickey_invisible.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Trage<?php } else { ?>Tragen Sie<?php } ?> hier, <strong>zusätzlich</strong> zu den obigen Schlüsseln, Schlüssel für das unsichtbare reCAPTCHA ein, wenn <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> diese Variante nutzen <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>möchtest<?php } else { ?>möchten<?php } ?>.';
$this->items['wcf.acp.option.recaptcha_privatekey_invisible'] = 'Geheimer Schlüssel (Unsichtbares reCAPTCHA)';
$this->items['wcf.acp.option.category.message.attachment'] = 'Dateianhänge';
$this->items['wcf.acp.option.attachment_retain_dimensions'] = 'Seitenverhältnis beim Erzeugen von Vorschaugrafiken beibehalten';
$this->items['wcf.acp.option.attachment_thumbnail_height'] = 'Höhe der Vorschaugrafiken';
$this->items['wcf.acp.option.attachment_thumbnail_width'] = 'Breite der Vorschaugrafiken';
$this->items['wcf.acp.option.category.message.attachment.autoscale'] = 'Automatische Bildskalierung';
$this->items['wcf.acp.option.attachment_image_autoscale'] = 'Bildskalierung durch den Webbrowser aktivieren';
$this->items['wcf.acp.option.attachment_image_autoscale.description'] = 'Wenn diese Option aktiviert ist, werden angehangene Bilder vor dem Upload im Webbrowser skaliert, falls diese die maximalen Dimensionen oder das Dateigrößenlimit überschreiten.';
$this->items['wcf.acp.option.attachment_image_autoscale_max_width'] = 'Maximal erlaubte Breite einer Grafik';
$this->items['wcf.acp.option.attachment_image_autoscale_max_height'] = 'Maximal erlaubte Höhe einer Grafik';
$this->items['wcf.acp.option.attachment_image_autoscale_quality'] = 'Qualitätsstufe';
$this->items['wcf.acp.option.attachment_image_autoscale_quality.description'] = 'Bestimmt die Qualität des skalierten Bildes.';
$this->items['wcf.acp.option.attachment_image_autoscale_file_type'] = 'Dateityp';
$this->items['wcf.acp.option.attachment_image_autoscale_file_type.jpeg'] = 'WebP (verlustbehaftet, erzeugt kleine Dateien)';
$this->items['wcf.acp.option.attachment_image_autoscale_file_type.keep'] = 'Dateityp beibehalten';
$this->items['wcf.acp.option.module_smiley'] = 'Smileys';
$this->items['wcf.acp.option.category.message.censorship'] = 'Zensur-Funktion';
$this->items['wcf.acp.option.censored_words'] = 'Zu zensierende Wörter';
$this->items['wcf.acp.option.censored_words.description'] = 'Sollte bei der Erstellung einer Nachricht eines dieser Wörter verwendet werden, so wird die Erstellung verweigert.<br>
<em>{if LANGUAGE_USE_INFORMAL_VARIANT}Verwende{else}Verwenden Sie{/if} „*“, um Wortteile zu finden: „wolt*“ findet auch „woltlab“</em><br>
<em>{if LANGUAGE_USE_INFORMAL_VARIANT}Verwende{else}Verwenden Sie{/if} „~“, um Worttrennungen zu finden: „wolt~“ findet auch „wolt-lab“</em>';
$this->dynamicItems['wcf.acp.option.censored_words.description'] = 'Sollte bei der Erstellung einer Nachricht eines dieser Wörter verwendet werden, so wird die Erstellung verweigert.<br>
<em><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Verwende<?php } else { ?>Verwenden Sie<?php } ?> „*“, um Wortteile zu finden: „wolt*“ findet auch „woltlab“</em><br>
<em><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Verwende<?php } else { ?>Verwenden Sie<?php } ?> „~“, um Worttrennungen zu finden: „wolt~“ findet auch „wolt-lab“</em>';
$this->items['wcf.acp.option.category.message.general.share'] = 'Teilen';
$this->items['wcf.acp.option.enable_share_buttons'] = 'Buttons zum Teilen von Inhalten anzeigen';
$this->items['wcf.acp.option.category.message.general.edit'] = 'Bearbeitungen';
$this->items['wcf.acp.option.module_edit_history'] = 'Bearbeitungsverlauf aktivieren';
$this->items['wcf.acp.option.module_edit_history.description'] = 'Speichert die alten Versionen von Benutzerinhalten.';
$this->items['wcf.acp.option.edit_history_expiration'] = 'Speicherzeit';
$this->items['wcf.acp.option.edit_history_expiration.description'] = 'Zeitraum, nachdem alte Einträge aus dem Bearbeitungsverlauf entfernt werden [0, um die Entfernung gänzlich zu deaktivieren]';
$this->items['wcf.acp.option.github_public_key'] = 'GitHub Client ID';
$this->items['wcf.acp.option.github_public_key.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst deine{else}Sie können Ihre{/if} Client ID und {if LANGUAGE_USE_INFORMAL_VARIANT}dein{else}Ihr{/if} Client Secret bei <a href="https://github.com/settings/developers" class="externalURL">GitHub</a> anfordern. Die Callback URL ist: {link controller="GithubAuth" forceFrontend=true}{/link}';
$this->dynamicItems['wcf.acp.option.github_public_key.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst deine<?php } else { ?>Sie können Ihre<?php } ?> Client ID und <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dein<?php } else { ?>Ihr<?php } ?> Client Secret bei <a href="https://github.com/settings/developers" class="externalURL">GitHub</a> anfordern. Die Callback URL ist: <?php $this->tagStack[] = [\'link\', [\'controller\' => "GithubAuth", \'forceFrontend\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
$this->items['wcf.acp.option.github_private_key'] = 'GitHub Client Secret';
$this->items['wcf.acp.option.twitter_public_key'] = 'X API key';
$this->items['wcf.acp.option.twitter_public_key.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst deinen{else}Sie können Ihren{/if} API key und {if LANGUAGE_USE_INFORMAL_VARIANT}dein{else}Ihr{/if} API secret bei <a href="https://developer.twitter.com/en/portal/projects-and-apps" class="externalURL">X</a> anfordern. Die Callback URL ist: {link controller="TwitterAuth" forceFrontend=true}{/link}';
$this->dynamicItems['wcf.acp.option.twitter_public_key.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst deinen<?php } else { ?>Sie können Ihren<?php } ?> API key und <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dein<?php } else { ?>Ihr<?php } ?> API secret bei <a href="https://developer.twitter.com/en/portal/projects-and-apps" class="externalURL">X</a> anfordern. Die Callback URL ist: <?php $this->tagStack[] = [\'link\', [\'controller\' => "TwitterAuth", \'forceFrontend\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
$this->items['wcf.acp.option.twitter_private_key'] = 'X API secret';
$this->items['wcf.acp.option.facebook_public_key'] = 'Facebook APP-ID';
$this->items['wcf.acp.option.facebook_public_key.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst deine{else}Sie können Ihre{/if} APP-ID und {if LANGUAGE_USE_INFORMAL_VARIANT}deinen{else}Ihren{/if} Anwendungs-Geheimcode bei <a href="https://developers.facebook.com/apps" class="externalURL">Facebook</a> anfordern. Die OAuth redirect URI ist: {link controller="FacebookAuth" forceFrontend=true}{/link}';
$this->dynamicItems['wcf.acp.option.facebook_public_key.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst deine<?php } else { ?>Sie können Ihre<?php } ?> APP-ID und <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deinen<?php } else { ?>Ihren<?php } ?> Anwendungs-Geheimcode bei <a href="https://developers.facebook.com/apps" class="externalURL">Facebook</a> anfordern. Die OAuth redirect URI ist: <?php $this->tagStack[] = [\'link\', [\'controller\' => "FacebookAuth", \'forceFrontend\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
$this->items['wcf.acp.option.facebook_private_key'] = 'Facebook Anwendungs-Geheimcode';
$this->items['wcf.acp.option.google_public_key'] = 'Google Client ID';
$this->items['wcf.acp.option.google_public_key.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst deine{else}Sie können Ihre{/if} Client ID und {if LANGUAGE_USE_INFORMAL_VARIANT}dein{else}Ihr{/if} Client Secret bei <a href="https://console.cloud.google.com/apis/credentials" class="externalURL">Google</a> anfordern. Die Redirect-URI ist: {link controller="GoogleAuth" forceFrontend=true}{/link}';
$this->dynamicItems['wcf.acp.option.google_public_key.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst deine<?php } else { ?>Sie können Ihre<?php } ?> Client ID und <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dein<?php } else { ?>Ihr<?php } ?> Client Secret bei <a href="https://console.cloud.google.com/apis/credentials" class="externalURL">Google</a> anfordern. Die Redirect-URI ist: <?php $this->tagStack[] = [\'link\', [\'controller\' => "GoogleAuth", \'forceFrontend\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>';
$this->items['wcf.acp.option.google_private_key'] = 'Google Client Secret';
$this->items['wcf.acp.option.category.dashboard'] = 'Dashboard';
$this->items['wcf.acp.option.category.dashboard.content'] = 'Inhaltsbereich';
$this->items['wcf.acp.option.category.dashboard.sidebar'] = 'Seitenleiste';
$this->items['wcf.acp.option.category.user.profile'] = 'Profil';
$this->items['wcf.acp.option.category.user.avatar'] = 'Avatar';
$this->items['wcf.acp.option.category.user.signature'] = 'Signatur';
$this->items['wcf.acp.option.category.user.title'] = 'Benutzertitel';
$this->items['wcf.acp.option.category.user.cleanup'] = 'Aufräumaktionen';
$this->items['wcf.acp.option.category.user.list'] = 'Mitgliederlisten';
$this->items['wcf.acp.option.category.user.list.members'] = 'Mitgliederliste';
$this->items['wcf.acp.option.category.user.list.online'] = '„Benutzer online“-Liste';
$this->items['wcf.acp.option.category.user.register'] = 'Registrierung';
$this->items['wcf.acp.option.category.user.password'] = 'Kennwort';
$this->items['wcf.acp.option.category.user.ban'] = 'Filter';
$this->items['wcf.acp.option.category.user.3rdPartyAuth'] = 'Authentifizierung über Drittanbieter';
$this->items['wcf.acp.option.module_users_online'] = '„Benutzer online“-Anzeige';
$this->items['wcf.acp.option.module_user_rank'] = 'Benutzerränge';
$this->items['wcf.acp.option.module_user_signature'] = 'Signaturen';
$this->items['wcf.acp.option.module_team_page'] = 'Team-Seite';
$this->items['wcf.acp.option.password_min_score'] = 'Sicherheitslevel';
$this->items['wcf.acp.option.password_min_score.description'] = '„Score“-Wert der <a href="https://github.com/dropbox/zxcvbn" class="externalURL">zxcvbn-Bibliothek</a>, den Kennwörter mindestens erreichen müssen.';
$this->items['wcf.acp.option.password_min_score.0'] = '0: Deaktiviert';
$this->items['wcf.acp.option.password_min_score.1'] = '1: Gering (Eine Million Versuche)';
$this->items['wcf.acp.option.password_min_score.2'] = '2: Gut (100 Millionen Versuche)';
$this->items['wcf.acp.option.password_min_score.3'] = '3: Stark (10 Milliarden Versuche)';
$this->items['wcf.acp.option.register_forbidden_usernames'] = 'Reservierte Namen';
$this->items['wcf.acp.option.register_forbidden_usernames.description'] = 'Namen, die nicht als Benutzername verwendet werden dürfen.';
$this->items['wcf.acp.option.register_forbidden_emails'] = 'Reservierte E-Mail-Adressen';
$this->items['wcf.acp.option.register_forbidden_emails.description'] = 'E-Mail-Adressen, die nicht bei der Registrierung verwendet werden dürfen.';
$this->items['wcf.acp.option.register_allowed_emails'] = 'Erlaubte E-Mail-Adressen';
$this->items['wcf.acp.option.register_allowed_emails.description'] = 'E-Mail-Adressen, die ausschließlich bei der Registrierung verwendet werden dürfen.';
$this->items['wcf.acp.option.register_username_min_length'] = 'Minimale Benutzernamenlänge';
$this->items['wcf.acp.option.register_username_max_length'] = 'Maximale Benutzernamenlänge';
$this->items['wcf.acp.option.register_username_force_ascii'] = 'Zeichenbeschränkung in Benutzernamen';
$this->items['wcf.acp.option.register_username_force_ascii.description'] = 'Die Zeichenbeschränkung in Benutzernamen schränkt die zulässigen Zeichen in Benutzernamen ein, die vom Benutzer selbst gewählt werden. Die Prüfung greift nicht bei Änderungen durch einen Administrator. Das Komma ist in Benutzernamen aus technischen Gründen generell unzulässig.
Die Beschränkung auf ASCII-Zeichen erlaubt in Benutzernamen lediglich lateinische Buchstaben, Ziffern und einfache Sonderzeichen. Umlaute, erweiterte Sonderzeichen und Emoji sind nicht zulässig. Die Beschränkung irreführender Kombinationen von Schriftsystemen verbietet Benutzernamen, die aus Zeichen mehrerer und optisch ähnlicher Schriftsysteme bestehen. Beispielsweise ist es nicht zulässig, Zeichen aus dem lateinischen Alphabet mit Zeichen aus dem kyrillischen Alphabet in einem Benutzernamen zu kombinieren.';
$this->items['wcf.acp.option.register_username_force_ascii.disabled'] = 'Keine Beschränkung';
$this->items['wcf.acp.option.register_username_force_ascii.ascii'] = 'Beschränkung auf ASCII-Zeichen';
$this->items['wcf.acp.option.register_username_force_ascii.suspicious'] = 'Irreführende Kombinationen von Schriftsystemen beschränken';
$this->items['wcf.acp.option.register_min_user_age'] = 'Mindestalter';
$this->items['wcf.acp.option.register_min_user_age.description'] = 'Eine Angabe hier führt dazu, dass das Geburtsdatum während der Registrierung abgefragt und zum Pflichtfeld wird.';
$this->items['wcf.acp.option.register_disabled'] = 'Registrierung deaktivieren';
$this->items['wcf.acp.option.register_disabled.description'] = 'Schaltet die Registrierung für neue Benutzer gänzlich ab. Neue Benutzer können nur noch manuell durch den Administrator angelegt werden.';
$this->items['wcf.acp.option.register_enable_disclaimer'] = 'Nutzungsbedingungen aktivieren';
$this->items['wcf.acp.option.register_enable_disclaimer.description'] = 'Die Nutzungsbedingungen müssen durch den Benutzer vor der Registrierung akzeptiert werden.';
$this->items['wcf.acp.option.register_activation_method'] = 'Aktivierungsmethode';
$this->items['wcf.acp.option.register_activation_method.byAdmin'] = 'Aktivierung erfolgt durch Administrator';
$this->items['wcf.acp.option.register_activation_method.byUser'] = 'Benutzer aktiviert sich durch E-Mail-Bestätigung';
$this->items['wcf.acp.option.register_activation_method.byUserAndAdmin'] = 'Aktivierung erfolgt durch Administrator nach erfolgreicher E-Mail-Bestätigung';
$this->items['wcf.acp.option.register_activation_method.disabled'] = 'Keine Aktivierung notwendig';
$this->items['wcf.acp.option.signature_max_image_height'] = 'Maximale Höhe von Signatur-Bildern';
$this->items['wcf.acp.option.sitemap_index_time_frame'] = 'Zeitfenster der Indexierung';
$this->items['wcf.acp.option.sitemap_index_time_frame.description'] = 'Maximales Alter der Objekte, um in die Sitemap aufgenommen zu werden [0, um das Zeitfenster zu deaktivieren].';
$this->items['wcf.acp.option.user_title_max_length'] = 'Maximale Länge des Benutzertitels';
$this->items['wcf.acp.option.user_forbidden_titles'] = 'Reservierte Benutzertitel';
$this->items['wcf.acp.option.user_forbidden_titles.description'] = 'Benutzertitel, die nicht verwendet werden dürfen.';
$this->items['wcf.acp.option.profile_show_old_username'] = 'Alten Namen anzeigen';
$this->items['wcf.acp.option.profile_show_old_username.description'] = 'Zeitraum in dem bei Änderungen des Benutzernamens zusätzlich der alte Benutzername im Profil angezeigt wird.';
$this->items['wcf.acp.option.members_list_users_per_page'] = 'Mitglieder pro Seite';
$this->items['wcf.acp.option.members_list_default_sort_field'] = 'Standard-Sortierung';
$this->items['wcf.acp.option.members_list_default_sort_field.description'] = '';
$this->items['wcf.acp.option.members_list_default_sort_order'] = 'Standard-Reihenfolge';
$this->items['wcf.acp.option.members_list_default_sort_order.description'] = '';
$this->items['wcf.acp.option.users_online_show_guests'] = 'Unregistrierte Benutzer auflisten';
$this->items['wcf.acp.option.users_online_show_robots'] = 'Suchmaschinen-Roboter auflisten';
$this->items['wcf.acp.option.users_online_default_sort_field'] = 'Standard-Sortierung';
$this->items['wcf.acp.option.users_online_default_sort_field.description'] = '';
$this->items['wcf.acp.option.users_online_default_sort_order'] = 'Standard-Reihenfolge';
$this->items['wcf.acp.option.users_online_default_sort_order.description'] = '';
$this->items['wcf.acp.option.users_online_page_refresh'] = 'Seite automatisch neu laden';
$this->items['wcf.acp.option.users_online_page_refresh.description'] = 'Zeitraum nachdem die Seite automatisch neu geladen wird. [0, um Neuladen abzuschalten]';
$this->items['wcf.acp.option.user_cleanup_notification_lifetime'] = 'Benachrichtigungen';
$this->items['wcf.acp.option.user_cleanup_notification_lifetime.description'] = 'Zeitraum nach dem Benachrichtigungen automatisch verworfen werden.';
$this->items['wcf.acp.option.user_cleanup_activity_event_lifetime'] = 'Letzte Aktivitäten';
$this->items['wcf.acp.option.user_cleanup_activity_event_lifetime.description'] = 'Zeitraum nach dem letzte Aktivitäten automatisch verworfen werden.';
$this->items['wcf.acp.option.user_cleanup_profile_visitor_lifetime'] = 'Profil-Besucher';
$this->items['wcf.acp.option.user_cleanup_profile_visitor_lifetime.description'] = 'Zeitraum nach dem Profil-Besucher automatisch verworfen werden.';
$this->items['wcf.acp.option.category.message.general.likes'] = 'Reaktions-System';
$this->items['wcf.acp.option.module_like'] = 'Reaktions-System';
$this->items['wcf.acp.option.like_show_summary'] = 'Zusammenfassung anzeigen';
$this->items['wcf.acp.option.module_user_profile_wall'] = 'Benutzerprofil-Pinnwand';
$this->items['wcf.acp.option.category.message.sidebar'] = 'Seitenleiste';
$this->items['wcf.acp.option.message_sidebar_enable_online_status'] = 'Online-Status der Autoren anzeigen';
$this->items['wcf.acp.option.message_sidebar_enable_likes_received'] = 'Erhaltene Reaktionen der Autoren anzeigen';
$this->items['wcf.acp.option.message_sidebar_enable_activity_points'] = 'Aktivitätspunkte der Autoren anzeigen';
$this->items['wcf.acp.option.message_sidebar_enable_trophy_points'] = 'Anzahl der Trophäen der Autoren anzeigen';
$this->items['wcf.acp.option.message_sidebar_user_options'] = 'Ausgewählte Profilfelder der Autoren anzeigen';
$this->items['wcf.acp.option.module_tagging'] = 'Tagging';
$this->items['wcf.acp.option.module_tagging.description'] = 'Aktiviert die Funktion für das Taggen von Inhalten.';
$this->items['wcf.acp.option.tagging_max_tag_length'] = 'Maximale Tag-Länge';
$this->items['wcf.acp.option.message_max_quote_depth'] = 'Maximale Zitat-Tiefe';
$this->items['wcf.acp.option.message_max_quote_depth.description'] = 'Der Wert „1“ erlaubt nur direkte Zitate, aber keine Zitate in Zitaten. Bei „2“ oder mehr dürfen Zitate selbst Zitate enthalten bis zur angegebenen Tiefe. Mit dem Wert „0“ wird diese Funktion deaktiviert und es können beliebig oft Zitate ineinander verschachtelt werden.';
$this->items['wcf.acp.option.category.message.search'] = 'Suchfunktion';
$this->items['wcf.acp.option.search_results_per_page'] = 'Ergebnisse pro Seite';
$this->items['wcf.acp.option.search_default_sort_field'] = 'Standardsortierung';
$this->items['wcf.acp.option.search_default_sort_field.description'] = '';
$this->items['wcf.acp.option.search_default_sort_order'] = 'Standardreihenfolge';
$this->items['wcf.acp.option.search_default_sort_order.description'] = '';
$this->items['wcf.acp.option.search_max_combined_tags'] = 'Maximale Anzahl Tags pro Suche';
$this->items['wcf.acp.option.category.message.general.poll'] = 'Umfragen';
$this->items['wcf.acp.option.module_poll'] = 'Umfragen';
$this->items['wcf.acp.option.poll_max_options'] = 'Maximale Anzahl an Antworten';
$this->items['wcf.acp.option.poll_full_width'] = 'Umfrage über die gesamte Breite darstellen';
$this->items['wcf.acp.option.error.validationFailed'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} einen ungültigen Inhalt eingegeben.';
$this->dynamicItems['wcf.acp.option.error.validationFailed'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> einen ungültigen Inhalt eingegeben.';
$this->items['wcf.acp.option.module_members_list'] = 'Mitgliederliste';
$this->items['wcf.acp.option.footer_code'] = 'Footer-Code';
$this->items['wcf.acp.option.footer_code.description'] = 'Der hier angegebene Code wird im Fußbereich jeder Seite ausgegeben. Der Footer-Code eignet sich z.B. sehr gut für die Einbindung von Diensten wie „Google Analytics“ oder „Matomo“.';
$this->items['wcf.acp.option.profile_enable_visitors'] = 'Profil-Besucher anzeigen';
$this->items['wcf.acp.option.url_title_component_replacement'] = 'URL-Ersetzungen';
$this->items['wcf.acp.option.url_title_component_replacement.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} den in URLs enthaltenen Titel durch eigene Ersetzungen verändern. Dies kann z.B. zum Ersetzen von Umlauten oder zum Expandieren von Abkürzungen genutzt werden.<br>
Beispiele:<br>
WBB=WoltLab Burning Board<br>
GmbH=Gesellschaft mit beschränkter Haftung';
$this->dynamicItems['wcf.acp.option.url_title_component_replacement.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst<?php } else { ?>Sie können<?php } ?> den in URLs enthaltenen Titel durch eigene Ersetzungen verändern. Dies kann z.B. zum Ersetzen von Umlauten oder zum Expandieren von Abkürzungen genutzt werden.<br>
Beispiele:<br>
WBB=WoltLab Burning Board<br>
GmbH=Gesellschaft mit beschränkter Haftung';
$this->items['wcf.acp.option.users_online_enable_legend'] = 'Legende der Benutzergruppen anzeigen';
$this->items['wcf.acp.option.category.general.system.googleMaps'] = 'Google Maps';
$this->items['wcf.acp.option.google_maps_zoom'] = 'Karten-Zoom';
$this->items['wcf.acp.option.google_maps_zoom.description'] = 'Standard-Einstellung des Karten-Zooms';
$this->items['wcf.acp.option.google_maps_default_latitude'] = 'Standard-Kartenposition (Breitengrad)';
$this->items['wcf.acp.option.google_maps_default_longitude'] = 'Standard-Kartenposition (Längengrad)';
$this->items['wcf.acp.option.show_update_notice_frontend'] = 'Hinweis bei neuen Updates für Pakete im Frontend anzeigen';
$this->items['wcf.acp.option.url_omit_index_php'] = 'Link-Umschreibungen aktivieren';
$this->items['wcf.acp.option.url_omit_index_php.button.runTestAgain'] = 'Test erneut durchführen';
$this->items['wcf.acp.option.url_omit_index_php.description'] = 'Wandelt Links in eine vereinfachte Form um, aus „https://example.com/index.php?thread/1-dies-ist-ein-test/“ wird „http://example.com/thread/1-dies-ist-ein-test/“ und vergleichbar. <strong>Achtung</strong>: Die Aktivierung der Link-Umschreibungen erfordert Rewrite-Unterstützung in {if LANGUAGE_USE_INFORMAL_VARIANT}deinem{else}Ihrem{/if} Webserver sowie eine entsprechende Konfiguration. Fehlerhafte Einstellungen können hier dazu führen, dass Links nicht mehr aufrufbar sind.<br>Eine Anleitung zur Einrichtung {if LANGUAGE_USE_INFORMAL_VARIANT}deines{else}Ihres{/if} Webservers {if LANGUAGE_USE_INFORMAL_VARIANT}findest du{else}finden Sie{/if} im Handbuch: <a href="https://manual.woltlab.com/de/url-rewrites/" class="externalURL">Konfiguration von benutzerfreundlichen URLs (SEO-URLs)</a>';
$this->dynamicItems['wcf.acp.option.url_omit_index_php.description'] = 'Wandelt Links in eine vereinfachte Form um, aus „https://example.com/index.php?thread/1-dies-ist-ein-test/“ wird „http://example.com/thread/1-dies-ist-ein-test/“ und vergleichbar. <strong>Achtung</strong>: Die Aktivierung der Link-Umschreibungen erfordert Rewrite-Unterstützung in <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deinem<?php } else { ?>Ihrem<?php } ?> Webserver sowie eine entsprechende Konfiguration. Fehlerhafte Einstellungen können hier dazu führen, dass Links nicht mehr aufrufbar sind.<br>Eine Anleitung zur Einrichtung <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deines<?php } else { ?>Ihres<?php } ?> Webservers <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>findest du<?php } else { ?>finden Sie<?php } ?> im Handbuch: <a href="https://manual.woltlab.com/de/url-rewrites/" class="externalURL">Konfiguration von benutzerfreundlichen URLs (SEO-URLs)</a>';
$this->items['wcf.acp.option.url_omit_index_php.test.failure'] = 'Test fehlgeschlagen';
$this->items['wcf.acp.option.url_omit_index_php.test.failure.description'] = 'Die Rewrite-Unterstützung des Webservers fehlt oder wurde nicht korrekt konfiguriert.<br>
<br>
Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}befolge{else}befolgen Sie{/if} die Anleitung zur <a href="https://manual.woltlab.com/de/url-rewrites/" class="externalURL">Konfiguration von benutzerfreundlichen URLs (SEO-URLs)</a> oder {if LANGUAGE_USE_INFORMAL_VARIANT}wende dich an deinen{else}wenden Sie sich an Ihren{/if} Anbieter, um Unterstützung bei der Einrichtung zu erhalten.';
$this->dynamicItems['wcf.acp.option.url_omit_index_php.test.failure.description'] = 'Die Rewrite-Unterstützung des Webservers fehlt oder wurde nicht korrekt konfiguriert.<br>
<br>
Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>befolge<?php } else { ?>befolgen Sie<?php } ?> die Anleitung zur <a href="https://manual.woltlab.com/de/url-rewrites/" class="externalURL">Konfiguration von benutzerfreundlichen URLs (SEO-URLs)</a> oder <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>wende dich an deinen<?php } else { ?>wenden Sie sich an Ihren<?php } ?> Anbieter, um Unterstützung bei der Einrichtung zu erhalten.';
$this->items['wcf.acp.option.url_omit_index_php.test.running'] = 'Test läuft …';
$this->items['wcf.acp.option.url_omit_index_php.test.status'] = 'Testergebnis';
$this->items['wcf.acp.option.url_omit_index_php.test.status.failure'] = 'Fehlgeschlagen';
$this->items['wcf.acp.option.url_omit_index_php.test.status.success'] = 'Erfolgreich';
$this->items['wcf.acp.option.url_omit_index_php.test.success'] = 'Test erfolgreich';
$this->items['wcf.acp.option.module_wcf_ad'] = 'Werbung';
$this->items['wcf.acp.option.module_wcf_ad.description'] = 'Aktiviert die <a href="{link controller=\'AdList\'}{/link}">Verwaltung von Werbe-Anzeigen</a>.';
$this->dynamicItems['wcf.acp.option.module_wcf_ad.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Aktiviert die <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'AdList\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Verwaltung von Werbe-Anzeigen</a>.';
$this->items['wcf.acp.option.captcha_type'] = 'Captcha-Art';
$this->items['wcf.acp.option.register_use_captcha'] = 'Captcha in Registrierung aktivieren';
$this->items['wcf.acp.option.lost_password_use_captcha'] = 'Captcha in „Kennwort vergessen“ aktivieren';
$this->items['wcf.acp.option.category.security.antispam.captcha'] = 'Captchas';
$this->items['wcf.acp.option.category.security.general.authentication'] = 'Benutzer-Authentifikation';
$this->items['wcf.acp.option.enable_user_authentication_failure'] = 'Fehlgeschlagene Anmeldeversuche protokollieren';
$this->items['wcf.acp.option.user_authentication_failure_timeout'] = 'Zeitraum der Überwachung';
$this->items['wcf.acp.option.user_authentication_failure_timeout.description'] = 'Zeitraum aus dem fehlgeschlagene Anmeldeversuche für unten genannte Maßnahmen berücksichtigt werden.';
$this->items['wcf.acp.option.user_authentication_failure_ip_captcha'] = 'Captcha bei Anmeldung (IP)';
$this->items['wcf.acp.option.user_authentication_failure_ip_captcha.description'] = 'Wird die angegebene Anzahl von fehlgeschlagenen Anmeldeversuchen von einer IP-Adresse überschritten, muss für jeden weiteren Versuch ein Captcha ausgefüllt werden.';
$this->items['wcf.acp.option.user_authentication_failure_ip_block'] = 'Blockierung der Anmeldung';
$this->items['wcf.acp.option.user_authentication_failure_ip_block.description'] = 'Wird die angegebene Anzahl von fehlgeschlagenen Anmeldeversuchen von einer IP-Adresse überschritten, wird die Anmeldung für diese IP-Adresse vorübergehend vollständig blockiert.';
$this->items['wcf.acp.option.user_authentication_failure_user_captcha'] = 'Captcha bei Anmeldung (Benutzer)';
$this->items['wcf.acp.option.user_authentication_failure_user_captcha.description'] = 'Wird die angegebene Anzahl von fehlgeschlagenen Anmeldeversuchen für ein spezifisches Benutzerkonto überschritten, muss für jeden weiteren Versuch ein Captcha ausgefüllt werden.';
$this->items['wcf.acp.option.user_authentication_failure_expiration'] = 'Löschung von alten Protokolleinträgen';
$this->items['wcf.acp.option.user_authentication_failure_expiration.description'] = 'Legt fest nach welchem Zeitraum protokollierte Anmeldeversuche gelöscht werden.';
$this->items['wcf.acp.option.signature_secret'] = 'Geheimer Schlüssel';
$this->items['wcf.acp.option.signature_secret.description'] = 'Ein geheimer Schlüssel, welcher zur Überprüfung von übertragenen Daten bestimmter Funktionen dient. Dieser Schlüssel ist vertraulich zu behandeln! Der Schlüssel wurde bei der Installation zufällig generiert und sollte nur in Ausnahmefällen geändert werden. <strong>Achtung</strong>: Dieser Schlüssel muss mindestens 15 Zeichen lang sein.';
$this->items['wcf.acp.option.search_engine'] = 'Suche';
$this->items['wcf.acp.option.search_engine.mysql'] = 'MySQL FULLTEXT (Standard)';
$this->items['wcf.acp.option.enable_pluginstore_widget'] = 'Empfohlene Plugins anzeigen';
$this->items['wcf.acp.option.enable_pluginstore_widget.description'] = 'Aktiviert die Anzeige empfohlener Produkte aus dem WoltLab® Plugin-Store auf der Startseite der Administrationsoberfläche.';
$this->items['wcf.acp.option.category.general.payment'] = 'Zahlungsoptionen';
$this->items['wcf.acp.option.available_payment_methods'] = 'Unterstützte Zahlungsanbieter';
$this->items['wcf.acp.option.paypal_email_address'] = 'PayPal-E-Mail-Adresse';
$this->items['wcf.acp.option.paypal_email_address.description'] = 'Für die Abwicklung von PayPal-Zahlungen wird ein PayPal-Konto mit aktivierter sofortiger Zahlungsbestätigung (IPN) benötigt.<br>
Als Benachrichtigungs-URL in der Konfiguration der sofortigen Zahlungsbestätigungen nutzen Sie dabei bitte folgende Adresse: <kbd>{link controller=\'PaypalCallback\' forceFrontend=true}{/link}</kbd>.';
$this->dynamicItems['wcf.acp.option.paypal_email_address.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Für die Abwicklung von PayPal-Zahlungen wird ein PayPal-Konto mit aktivierter sofortiger Zahlungsbestätigung (IPN) benötigt.<br>
Als Benachrichtigungs-URL in der Konfiguration der sofortigen Zahlungsbestätigungen nutzen Sie dabei bitte folgende Adresse: <kbd><?php $this->tagStack[] = [\'link\', [\'controller\' => \'PaypalCallback\', \'forceFrontend\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?></kbd>.';
$this->items['wcf.acp.option.module_paid_subscription'] = 'Bezahlte Mitgliedschaften aktivieren';
$this->items['wcf.acp.option.module_paid_subscription.description'] = 'Aktiviert die <a href="{link controller=\'PaidSubscriptionList\'}{/link}">Verwaltung der bezahlten Mitgliedschaften</a>.';
$this->dynamicItems['wcf.acp.option.module_paid_subscription.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Aktiviert die <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'PaidSubscriptionList\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Verwaltung der bezahlten Mitgliedschaften</a>.';
$this->items['wcf.acp.option.paid_subscription_enable_tos_confirmation'] = 'Benutzer müssen vor dem Kauf Nutzungsbedingungen akzeptieren';
$this->items['wcf.acp.option.paid_subscription_tos_url'] = 'URL zu Nutzungsbedingungen';
$this->items['wcf.acp.option.category.general.payment.paidSubscription'] = 'Bezahlte Mitgliedschaften';
$this->items['wcf.acp.option.google_maps_api_key'] = 'Browser-API-Schlüssel';
$this->items['wcf.acp.option.google_maps_api_key.description'] = 'Google stellt <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" class="externalURL">hier</a> eine ausführliche Anleitung bereit, wie {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} einen API-Schlüssel erstellen {if LANGUAGE_USE_INFORMAL_VARIANT}kannst{else}können{/if}.';
$this->dynamicItems['wcf.acp.option.google_maps_api_key.description'] = 'Google stellt <a href="https://developers.google.com/maps/documentation/javascript/get-api-key" class="externalURL">hier</a> eine ausführliche Anleitung bereit, wie <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> einen API-Schlüssel erstellen <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>kannst<?php } else { ?>können<?php } ?>.';
$this->items['wcf.acp.option.suffix.chars'] = 'Zeichen';
$this->items['wcf.acp.option.suffix.days'] = 'Tage';
$this->items['wcf.acp.option.suffix.hours'] = 'Stunden';
$this->items['wcf.acp.option.suffix.minutes'] = 'Minuten';
$this->items['wcf.acp.option.suffix.percent'] = '%';
$this->items['wcf.acp.option.suffix.pixel'] = 'Pixel';
$this->items['wcf.acp.option.suffix.seconds'] = 'Sekunden';
$this->items['wcf.acp.option.suffix.years'] = 'Jahre';
$this->items['wcf.acp.option.type.boolean.never'] = 'Nie';
$this->items['wcf.acp.option.type.boolean.no'] = 'Nein';
$this->items['wcf.acp.option.type.boolean.yes'] = 'Ja';
$this->items['wcf.acp.option.category.cms'] = 'CMS';
$this->items['wcf.acp.option.category.cms.article'] = 'Artikel';
$this->items['wcf.acp.option.category.cms.media'] = 'Medien';
$this->items['wcf.acp.option.articles_per_page'] = 'Artikel pro Seite';
$this->items['wcf.acp.option.article_enable_comments_default_value'] = 'Kommentare aktivieren [Vorgabewert]';
$this->items['wcf.acp.option.article_enable_like'] = 'Reaktionen aktivieren';
$this->items['wcf.acp.option.article_related_articles'] = 'Anzahl verwandter Artikel';
$this->items['wcf.acp.option.article_related_articles_match_threshold'] = 'Übereinstimmung von verwandten Artikeln';
$this->items['wcf.acp.option.article_related_articles_match_threshold.description'] = 'Menge an Tags, die für eine Erkennung als verwandter Artikel übereinstimmen müssen.';
$this->items['wcf.acp.option.article_show_about_author'] = '„Über den Autor“ anzeigen';
$this->items['wcf.acp.option.category.message.general.image'] = 'Bilder';
$this->items['wcf.acp.option.category.message.general.imageProxy'] = 'Zwischenspeicherung von externen Bildern';
$this->items['wcf.acp.option.module_article'] = 'Artikel';
$this->items['wcf.acp.option.message_force_secure_images'] = 'Nur sichere Bilder in Nachrichten erlauben';
$this->items['wcf.acp.option.message_force_secure_images.description'] = 'Bilder dürfen nur über das verschlüsselte „https“-Protokoll eingebunden werden. Bereits in bestehenden Nachrichten hinterlegte Bilder werden zwangsweise auf dieses Protokoll umgeschrieben.';
$this->items['wcf.acp.option.module_image_proxy'] = 'Zwischenspeicherung von externen Bildern aktivieren („Image-Proxy“)';
$this->items['wcf.acp.option.image_proxy_expiration'] = 'Maximale Speicherzeit';
$this->items['wcf.acp.option.image_proxy_insecure_only'] = 'Nur Bilder aus unverschlüsselten Quellen zwischenspeichern';
$this->items['wcf.acp.option.image_proxy_enable_prune'] = 'Zwischengespeicherte Bilder regelmäßig löschen';
$this->items['wcf.acp.option.image_proxy_host_whitelist'] = 'Ausnahmen von der Zwischenspeicherung';
$this->items['wcf.acp.option.image_proxy_host_whitelist.description'] = 'Die aufgeführten Domains werden von der Zwischenspeicherung ausgenommen, die eigene Domain ist implizit enthalten. Der Abgleich erfolgt auf Basis der strikten Übereinstimmung, optional können Subdomains mit einem Platzhalter berücksichtigt werden: <kbd>*.example.com</kbd> umfasst sowohl <kbd>example.com</kbd> als auch Subdomains wie <kbd>foo.example.com</kbd> oder <kbd>www.example.com</kbd>.';
$this->items['wcf.acp.option.share_buttons_providers'] = 'Anbieter zum Teilen von Inhalten';
$this->items['wcf.acp.option.show_style_changer'] = 'Stil-Auswahl anzeigen';
$this->items['wcf.acp.option.language_use_informal_variant'] = 'Informelle Anrede verwenden';
$this->items['wcf.acp.option.category.cms.media.thumbnail'] = 'Vorschaugrafiken';
$this->items['wcf.acp.option.media_large_thumbnail_height'] = 'Höhe der großen Vorschaugrafiken';
$this->items['wcf.acp.option.media_large_thumbnail_retain_dimensions'] = 'Seitenverhältnis beim Erzeugen von großen Vorschaugrafiken beibehalten';
$this->items['wcf.acp.option.media_large_thumbnail_width'] = 'Breite der großen Vorschaugrafiken';
$this->items['wcf.acp.option.media_medium_thumbnail_height'] = 'Höhe der mittleren Vorschaugrafiken';
$this->items['wcf.acp.option.media_medium_thumbnail_retain_dimensions'] = 'Seitenverhältnis beim Erzeugen von mittleren Vorschaugrafiken beibehalten';
$this->items['wcf.acp.option.media_medium_thumbnail_width'] = 'Breite der mittleren Vorschaugrafiken';
$this->items['wcf.acp.option.media_small_thumbnail_height'] = 'Höhe der kleinen Vorschaugrafiken';
$this->items['wcf.acp.option.media_small_thumbnail_retain_dimensions'] = 'Seitenverhältnis beim Erzeugen von kleinen Vorschaugrafiken beibehalten';
$this->items['wcf.acp.option.media_small_thumbnail_width'] = 'Breite der kleinen Vorschaugrafiken';
$this->items['wcf.acp.option.article_sort_order'] = 'Sortierungsreihenfolge';
$this->items['wcf.acp.option.article_sort_order.description'] = 'Standard-Reihenfolge für die Liste der Artikel.';
$this->items['wcf.acp.option.use_page_title_on_landing_page'] = 'Titel der Seite als Überschrift auf Startseite anzeigen';
$this->items['wcf.acp.option.head_code'] = 'Head-Code';
$this->items['wcf.acp.option.head_code.description'] = 'Der hier angegebene Code wird im Head-Tag jeder Seite ausgegeben. Der Head-Code eignet sich z.B. sehr gut für die Einbindung von zusätzlichen Meta-Tags.';
$this->items['wcf.acp.option.avatar_default_type'] = 'Standard Avatar-Typ';
$this->items['wcf.acp.option.avatar_default_type.initials'] = 'Initialen';
$this->items['wcf.acp.option.avatar_default_type.silhouette'] = 'Silhouette';
$this->items['wcf.acp.option.enable_ad_rotation'] = 'Werbung abwechselnd anzeigen';
$this->items['wcf.acp.option.enable_ad_rotation.description'] = 'Sollte einer Position mehr als eine Werbung zugewiesen sein, so wird bei jedem Aufruf eine zufällige Werbung angezeigt. Bei Deaktivierung dieser Option werden alle Werbungen parallel angezeigt.';
$this->items['wcf.acp.option.visitor_use_tiny_build'] = 'Seitenbeschleunigung für Gäste aktivieren';
$this->items['wcf.acp.option.visitor_use_tiny_build.description'] = 'Aktiviert einen besonderen Modus in dem Gästen und Suchmaschinen stark reduzierte JavaScript-Dateien ausgeliefert werden, um das Laden als auch den Seitenaufbau zu beschleunigen.<br><strong>Warnung:</strong> Dieser Modus arbeitet sehr restriktiv und untersagt unter anderem jeglichen Schreibzugriff, bitte überprüfe{if !LANGUAGE_USE_INFORMAL_VARIANT}n Sie{/if}, ob alle installierten Plugins mit diesem Modus kompatibel sind.';
$this->dynamicItems['wcf.acp.option.visitor_use_tiny_build.description'] = 'Aktiviert einen besonderen Modus in dem Gästen und Suchmaschinen stark reduzierte JavaScript-Dateien ausgeliefert werden, um das Laden als auch den Seitenaufbau zu beschleunigen.<br><strong>Warnung:</strong> Dieser Modus arbeitet sehr restriktiv und untersagt unter anderem jeglichen Schreibzugriff, bitte überprüfe<?php if ( ! LANGUAGE_USE_INFORMAL_VARIANT) { ?>n Sie<?php } ?>, ob alle installierten Plugins mit diesem Modus kompatibel sind.';
$this->items['wcf.acp.option.fb_share_app_id'] = 'Facebook App ID';
$this->items['wcf.acp.option.fb_share_app_id.description'] = 'Die App ID kann direkt über das <a href="https://developers.facebook.com/apps/" class="externalURL">App-Dashboard angefordert werden</a>, und wird für die Open Graph-Tags zum Teilen verwendet.';
$this->items['wcf.acp.option.enable_polling'] = 'Hintergrund-Aktualisierung von Benachrichtigungen aktivieren';
$this->items['wcf.acp.option.enable_polling.description'] = 'Neue Benachrichtigungen werden in periodischen Abständen automatisch abgerufen. Das Aktualisierungs-Intervall beträgt 5 Minuten und wird bei Inaktivität schrittweise auf 15 Minuten angehoben.';
$this->items['wcf.acp.option.module_contact_form'] = 'Kontaktformular aktivieren';
$this->items['wcf.acp.option.module_contact_form.description'] = 'Aktiviert das Kontaktformular, nach Aktivierung können Sie die <a href="{link controller=\'ContactSettings\'}{/link}">Eingabefelder und Empfänger</a> individuell konfigurieren.';
$this->dynamicItems['wcf.acp.option.module_contact_form.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Aktiviert das Kontaktformular, nach Aktivierung können Sie die <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'ContactSettings\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Eingabefelder und Empfänger</a> individuell konfigurieren.';
$this->items['wcf.acp.option.module_trophy'] = 'Trophäen';
$this->items['wcf.acp.option.category.module.development'] = 'Entwicklung';
$this->items['wcf.acp.option.category.module.development.notice'] = 'Diese Optionen werden exklusiv für die Entwicklung und Fehlersuche verwendet, und sind nicht für den produktiven Einsatz geeignet.';
$this->items['wcf.acp.option.enable_developer_tools'] = 'Entwickler-Werkzeuge aktivieren';
$this->items['wcf.acp.option.enable_developer_tools.description'] = 'Aktiviert spezielle Werkzeuge die für die Plugin-Entwicklung verwendet werden. Diese Option sollte im Live-Betrieb abgeschaltet werden.';
$this->items['wcf.acp.option.force_login'] = 'Anmeldung erzwingen';
$this->items['wcf.acp.option.force_login.description'] = 'Besucher werden aufgefordert sich anzumelden, um auf die Inhalte zugreifen zu können.';
$this->items['wcf.acp.option.page_logo_link_to_app_default'] = 'Seitenlogo verlinkt auf die Startseite der aktiven App';
$this->items['wcf.acp.option.page_logo_link_to_app_default.description'] = 'Deaktiviere{if !LANGUAGE_USE_INFORMAL_VARIANT}n Sie{/if} diese Option, damit das Logo stets auf die globale Startseite verlinkt. Die Deaktivierung entspricht dem Verhalten in früheren Versionen.';
$this->dynamicItems['wcf.acp.option.page_logo_link_to_app_default.description'] = 'Deaktiviere<?php if ( ! LANGUAGE_USE_INFORMAL_VARIANT) { ?>n Sie<?php } ?> diese Option, damit das Logo stets auf die globale Startseite verlinkt. Die Deaktivierung entspricht dem Verhalten in früheren Versionen.';
$this->items['wcf.acp.option.image_allow_external_source'] = 'Bilder von externen Seiten erlauben';
$this->items['wcf.acp.option.image_external_source_whitelist'] = 'Erlaubte Bilder von externen Seiten';
$this->items['wcf.acp.option.image_external_source_whitelist.description'] = 'Die aufgeführten Domains sind von der Blockade ausgenommen. Der Abgleich erfolgt auf Basis der strikten Übereinstimmung, optional können Subdomains mit einem Platzhalter berücksichtigt werden: <kbd>*.example.com</kbd> umfasst sowohl <kbd>example.com</kbd> als auch Subdomains wie <kbd>foo.example.com</kbd> oder <kbd>www.example.com</kbd>.';
$this->items['wcf.acp.option.message_enable_toc'] = 'Inhaltsverzeichnisse aktivieren';
$this->items['wcf.acp.option.search_enable_articles'] = 'Artikel sind durchsuchbar';
$this->items['wcf.acp.option.search_enable_pages'] = 'Seiten sind durchsuchbar';
$this->items['wcf.acp.option.message_sidebar_enable_articles'] = 'Artikelanzahl der Autoren anzeigen';
$this->items['wcf.acp.option.message_public_highlighters'] = 'Auswählbare Syntax-Highlighter';
$this->items['wcf.acp.option.message_public_highlighters.description'] = 'Die gewählten Syntax-Highlighter stehen dem Nutzer unmittelbar im Editor zur Verfügung. Die anderen Highlighter sind weiterhin verfügbar, der Nutzer muss jedoch den internen Namen kennen.';
$this->items['wcf.acp.option.log_missing_language_items'] = 'Fehlende Sprachvariablen protokollieren';
$this->items['wcf.acp.option.log_missing_language_items.description'] = 'Die fehlenden Sprachvariablen können unter <a href="{link controller=\'DevtoolsMissingLanguageItemList\'}{/link}">Fehlende Texte</a> eingesehen werden.';
$this->dynamicItems['wcf.acp.option.log_missing_language_items.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Die fehlenden Sprachvariablen können unter <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'DevtoolsMissingLanguageItemList\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Fehlende Texte</a> eingesehen werden.';
$this->items['wcf.acp.option.category.general.system.ipAddress'] = 'IP-Adressen';
$this->items['wcf.acp.option.prune_ip_address'] = 'Speicherzeit für IP-Adressen';
$this->items['wcf.acp.option.prune_ip_address.description'] = 'Zeitraum, nachdem alte IP-Adressen automatisch gelöscht werden. [0, um die Löschung zu deaktivieren]';
$this->items['wcf.acp.option.breadcrumbs_home_use_page_title'] = 'Titel der Seite für die Startseite in den Breadcrumbs verwenden';
$this->items['wcf.acp.option.category.message.contactForm'] = 'Kontaktformular';
$this->items['wcf.acp.option.contact_form_enable_attachments'] = 'Dateianhänge im Kontaktformular aktivieren';
$this->items['wcf.acp.option.contact_form_prune_attachments'] = 'Dateianhänge automatisch entfernen';
$this->items['wcf.acp.option.contact_form_prune_attachments.description'] = 'Alte Dateianhänge werden nach Ablauf der Frist automatisch gelöscht. [0, um die Löschung zu deaktivieren]';
$this->items['wcf.acp.option.category.security.blacklist.sfs'] = 'Stop Forum Spam';
$this->items['wcf.acp.option.category.security.blacklist.sfs.description'] = 'Datenschutzkonforme Überprüfung auf Basis einer lokalen Kopie der StopForumSpam.com-Datenbestände.';
$this->items['wcf.acp.option.blacklist_sfs_enable'] = 'Abgleich mit Stop Forum Spam aktivieren';
$this->items['wcf.acp.option.blacklist_sfs_enable.description'] = 'Die lokale Datenbank enthält Informationen zur Häufigkeit, mit der ein Eintrag als Spammer gemeldet wurde.<br>
<strong>Hinweis: Es werden zu keinem Zeitpunkt Daten an Drittseiten übertragen.</strong><br>
<br>
Die Datenbestände werden sorgfältig gepflegt, aber es ist nicht ausgeschlossen, dass manche Einträge nicht korrekt oder veraltet sind. Zu diesem Zweck existieren unterschiedliche Abstufungen, wie die jeweiligen Übereinstimmungen zu werten sind. Die empfohlenen Einstellungen basieren auf jahrelangen Erfahrungswerten und Veränderungen sollten daher nur mit Bedacht getätigt werden.
<ul class="nativeList">
	<li><strong>Nicht überprüfen</strong> – Dieses Feld wird nicht abgeglichen.</li>
	<li><strong>Top 10%</strong> – Nur die 10% am häufigsten gemeldeten Treffer werden gewertet.</li>
	<li><strong>Mehrfach gemeldet</strong> – Es muss mehr als eine Meldung geben.</li>
	<li><strong>Einfacher Treffer reicht aus</strong> – Die Anzahl der Meldungen wird nicht berücksichtigt, jede Übereinstimmung reicht aus. Nicht empfohlen.</li>
</ul>';
$this->items['wcf.acp.option.blacklist_sfs_enable.skip'] = 'Nicht überprüfen';
$this->items['wcf.acp.option.blacklist_sfs_enable.90percentile'] = 'Top 10%';
$this->items['wcf.acp.option.blacklist_sfs_enable.moreThanOnce'] = 'Mehrfach gemeldet';
$this->items['wcf.acp.option.blacklist_sfs_enable.simpleMatch'] = 'Einfacher Treffer reicht aus';
$this->items['wcf.acp.option.blacklist_sfs_username'] = 'Benutzername';
$this->items['wcf.acp.option.blacklist_sfs_username.description'] = 'Erfahrungsgemäß ein <strong>sehr unzuverlässiges Kriterium</strong> zur Erkennung. Empfohlene Einstellung: <strong>Nicht überprüfen</strong>.';
$this->items['wcf.acp.option.blacklist_sfs_email_address'] = 'E-Mail-Adresse';
$this->items['wcf.acp.option.blacklist_sfs_email_address.description'] = 'E-Mail-Adressen sind einzigartig und stellen eine solide Basis dar. Empfohlene Einstellung: <strong>Mehrfach gemeldet</strong>.';
$this->items['wcf.acp.option.blacklist_sfs_ip_address'] = 'IP-Adresse';
$this->items['wcf.acp.option.blacklist_sfs_ip_address.description'] = 'IP-Adressen sind insbesondere durch die dynamische Vergabe (z. B. Privatanschlüsse oder Mobilfunk) nur bedingt verlässlich. Empfohlene Einstellung: <strong>Top 10%</strong>.';
$this->items['wcf.acp.option.register_antispam_action'] = 'Aktion bei Spam-Erkennung';
$this->items['wcf.acp.option.register_antispam_action.block'] = 'Registrierung blockieren';
$this->items['wcf.acp.option.register_antispam_action.description'] = 'Es besteht immer das Risiko einer fehlerhaften Spam-Erkennung, daher wird die Einstellung <strong>Registrierung erfordert manuelle Freischaltung</strong> ausdrücklich empfohlen.';
$this->items['wcf.acp.option.register_antispam_action.disable'] = 'Registrierung erfordert manuelle Freischaltung';
$this->items['wcf.acp.option.message_enable_user_consent'] = 'Inhalte von externen Anbietern erst nach Zustimmung anzeigen';
$this->items['wcf.acp.option.modification_log_expiration'] = 'Speicherzeit für Änderungen';
$this->items['wcf.acp.option.modification_log_expiration.description'] = 'Zeitraum, nachdem alte Änderungen aus dem Änderungsprotokoll entfernt werden [0, um die Entfernung gänzlich zu deaktivieren]';
$this->items['wcf.acp.option.internal_hostnames'] = 'Zusätzliche interne Domains';
$this->items['wcf.acp.option.internal_hostnames.description'] = 'Die aufgeführten Domains werden, neben den Domains der installierten Apps, als interne Domains angesehen. Der Abgleich erfolgt auf Basis der strikten Übereinstimmung, optional können Subdomains mit einem Platzhalter berücksichtigt werden: <kbd>*.example.com</kbd> umfasst sowohl <kbd>example.com</kbd> als auch Subdomains wie <kbd>foo.example.com</kbd> oder <kbd>www.example.com</kbd>';
$this->items['wcf.acp.option.type.lineBreakSeparatedText.placeholder'] = 'Neuen Eintrag hinzufügen';
$this->items['wcf.acp.option.type.lineBreakSeparatedText.error.duplicate'] = 'Der Eintrag <strong>{$item}</strong> existiert bereits.';
$this->dynamicItems['wcf.acp.option.type.lineBreakSeparatedText.error.duplicate'] = 'Der Eintrag <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'item\']);?></strong> existiert bereits.';
$this->items['wcf.acp.option.type.lineBreakSeparatedText.clearList.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} alle Einträge wirklich löschen?';
$this->dynamicItems['wcf.acp.option.type.lineBreakSeparatedText.clearList.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> alle Einträge wirklich löschen?';
$this->items['wcf.acp.option.category.message.general.unfurl'] = 'Rich Embeds';
$this->items['wcf.acp.option.module_url_unfurling'] = 'Rich Embeds aktivieren';
$this->items['wcf.acp.option.module_url_unfurling.description'] = 'Erzeugt eine Vorschau mit Titel, Beschreibung und Bild für externe Links in Nachrichten.';
$this->items['wcf.acp.option.category.message.general.formatting'] = 'Textformatierung';
$this->items['wcf.acp.option.formatting_remove_color'] = 'Schriftfarbe entfernen';
$this->items['wcf.acp.option.formatting_remove_color.description'] = 'Verhindert die Verwendung von abweichenden Schriftfarben und entfernt diese bei der Anzeige bereits bestehender Nachrichten.';
$this->items['wcf.acp.option.formatting_remove_font'] = 'Schriftart entfernen';
$this->items['wcf.acp.option.formatting_remove_font.description'] = 'Verhindert die Verwendung von abweichenden Schriftarten und entfernt diese bei der Anzeige bereits bestehender Nachrichten.';
$this->items['wcf.acp.option.formatting_remove_size'] = 'Schriftgröße entfernen';
$this->items['wcf.acp.option.formatting_remove_size.description'] = 'Verhindert die Verwendung von abweichenden Schriftgrößen und entfernt diese bei der Anzeige bereits bestehender Nachrichten.';
