<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.acp.search
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.acp.search.noResults'] = 'Keine Treffer';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.menuItem'] = 'Administrationsmenü';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.option'] = 'Optionen';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.package'] = 'Pakete';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.user'] = 'Benutzer';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.userGroupOption'] = 'Berechtigungen';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.page'] = 'Seiten';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.article'] = 'Artikel';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.box'] = 'Boxen';
$this->items['wcf.acp.search.provider.com.woltlab.wcf.trophy'] = 'Trophäen';
$this->items['wcf.acp.search.result.subtitle'] = '{implode from=$pieces item=piece glue=\' » \'}{$piece|phrase}{/implode}';
$this->dynamicItems['wcf.acp.search.result.subtitle'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?><?php
$_length4b7a7e2dfd80a11edceee8ab1e0d10618c580c57 = count($this->v[\'pieces\']);
$_i4b7a7e2dfd80a11edceee8ab1e0d10618c580c57 = 0;
$_item4b7a7e2dfd80a11edceee8ab1e0d10618c580c57 = $this->v[\'piece\'] ?? null;
$_key4b7a7e2dfd80a11edceee8ab1e0d10618c580c57 =  null;
foreach ($this->v[\'pieces\'] as $this->v[\'piece\']) { ?><?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([$this->v[\'piece\']], $this));?><?php
if (++$_i4b7a7e2dfd80a11edceee8ab1e0d10618c580c57 < $_length4b7a7e2dfd80a11edceee8ab1e0d10618c580c57) { echo \' » \'; }
}
unset($this->v[\'piece\']);$this->v[\'piece\'] = $_item4b7a7e2dfd80a11edceee8ab1e0d10618c580c57;
unset($_length4b7a7e2dfd80a11edceee8ab1e0d10618c580c57, $_i4b7a7e2dfd80a11edceee8ab1e0d10618c580c57);
unset($_item4b7a7e2dfd80a11edceee8ab1e0d10618c580c57, $_key4b7a7e2dfd80a11edceee8ab1e0d10618c580c57);
?>';
