<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.global.form
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.global.form.boolean.no'] = 'Nein';
$this->items['wcf.global.form.boolean.yes'] = 'Ja';
$this->items['wcf.global.form.data'] = 'Allgemeine Daten';
$this->items['wcf.global.form.error'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} Angaben sind ungültig. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}überprüfe{else}überprüfen Sie{/if} die markierten Eingabefelder.';
$this->dynamicItems['wcf.global.form.error'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> Angaben sind ungültig. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>überprüfe<?php } else { ?>überprüfen Sie<?php } ?> die markierten Eingabefelder.';
$this->items['wcf.global.form.error.empty'] = 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}fülle{else}füllen Sie{/if} dieses Eingabefeld aus.';
$this->dynamicItems['wcf.global.form.error.empty'] = 'Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>fülle<?php } else { ?>füllen Sie<?php } ?> dieses Eingabefeld aus.';
$this->items['wcf.global.form.error.greaterThan'] = 'Der eingegebene Wert muss größer sein als {#$greaterThan}.';
$this->dynamicItems['wcf.global.form.error.greaterThan'] = 'Der eingegebene Wert muss größer sein als <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'greaterThan\']);?>.';
$this->items['wcf.global.form.error.lessThan'] = 'Der eingegebene Wert muss kleiner sein als {#$lessThan}.';
$this->dynamicItems['wcf.global.form.error.lessThan'] = 'Der eingegebene Wert muss kleiner sein als <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'lessThan\']);?>.';
$this->items['wcf.global.form.error.multilingual'] = 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}fülle{else}füllen Sie{/if} dieses Eingabefeld für jede Sprache aus.';
$this->dynamicItems['wcf.global.form.error.multilingual'] = 'Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>fülle<?php } else { ?>füllen Sie<?php } ?> dieses Eingabefeld für jede Sprache aus.';
$this->items['wcf.global.form.error.noValidSelection'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Wähle{else}Wählen Sie{/if} eine der angebotenen Optionen aus.';
$this->dynamicItems['wcf.global.form.error.noValidSelection'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Wähle<?php } else { ?>Wählen Sie<?php } ?> eine der angebotenen Optionen aus.';
$this->items['wcf.global.form.error.securityToken'] = 'Die Gültigkeit der Anfrage konnte aufgrund eines fehlerhaften XSRF-Tokens nicht verifiziert werden. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}sende{else}senden Sie{/if} das Formular erneut ab.';
$this->dynamicItems['wcf.global.form.error.securityToken'] = 'Die Gültigkeit der Anfrage konnte aufgrund eines fehlerhaften XSRF-Tokens nicht verifiziert werden. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>sende<?php } else { ?>senden Sie<?php } ?> das Formular erneut ab.';
$this->items['wcf.global.form.input.maxItems'] = 'Maximale Anzahl erreicht';
$this->items['wcf.global.form.required'] = 'Benötigte Angaben';
$this->items['wcf.global.form.password.button.hide'] = 'Kennwort verbergen';
$this->items['wcf.global.form.password.button.show'] = 'Kennwort anzeigen';
