<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.page
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.page.pageNo'] = 'Seite {#$pageNo}';
$this->dynamicItems['wcf.page.pageNo'] = 'Seite <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'pageNo\']);?>';
$this->items['wcf.page.pagination'] = 'Seiten-Navigation';
$this->items['wcf.page.offline'] = 'Die Seite befindet sich zurzeit {if OFFLINE_MESSAGE != \'\'}aus folgenden Gründen im Wartungsmodus:{else}im Wartungsmodus.{/if}';
$this->dynamicItems['wcf.page.offline'] = 'Die Seite befindet sich zurzeit <?php if (OFFLINE_MESSAGE != \'\') { ?>aus folgenden Gründen im Wartungsmodus:<?php } else { ?>im Wartungsmodus.<?php } ?>';
$this->items['wcf.page.mainMenu'] = 'Navigation';
$this->items['wcf.page.pagePosition'] = 'Seite {#$pageNo} von {#$pages}';
$this->dynamicItems['wcf.page.pagePosition'] = 'Seite <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'pageNo\']);?> von <?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'pages\']);?>';
$this->items['wcf.page.javascriptDisabled'] = 'In {if LANGUAGE_USE_INFORMAL_VARIANT}deinem{else}Ihrem{/if} Webbrowser ist JavaScript deaktiviert. Um alle Funktionen dieser Website nutzen zu können, muss JavaScript aktiviert sein.';
$this->dynamicItems['wcf.page.javascriptDisabled'] = 'In <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deinem<?php } else { ?>Ihrem<?php } ?> Webbrowser ist JavaScript deaktiviert. Um alle Funktionen dieser Website nutzen zu können, muss JavaScript aktiviert sein.';
$this->items['wcf.page.requestedPage'] = 'Aufgerufene Seite';
$this->items['wcf.page.copyright'] = '<a href="https://www.woltlab.com/de/" rel="nofollow"{if EXTERNAL_LINK_TARGET_BLANK} target="_blank"{/if}>Community-Software: <strong>WoltLab Suite&trade;{if SHOW_VERSION_NUMBER} {@WCF_VERSION}{/if}</strong></a>';
$this->dynamicItems['wcf.page.copyright'] = '<a href="https://www.woltlab.com/de/" rel="nofollow"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank"<?php } ?>>Community-Software: <strong>WoltLab Suite&trade;<?php if (SHOW_VERSION_NUMBER) { ?> <?=WCF_VERSION;?><?php } ?></strong></a>';
$this->items['wcf.page.onlineLocation.com.woltlab.wcf.Article'] = 'Artikel <a href="{$article->getLink()}">{$article->getTitle()}</a>';
$this->dynamicItems['wcf.page.onlineLocation.com.woltlab.wcf.Article'] = 'Artikel <a href="<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'article\']->getLink());?>"><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'article\']->getTitle());?></a>';
$this->items['wcf.page.onlineLocation.com.woltlab.wcf.CategoryArticleList'] = 'Artikel-Kategorie <a href="{$category->getLink()}">{$category->getTitle()}</a>';
$this->dynamicItems['wcf.page.onlineLocation.com.woltlab.wcf.CategoryArticleList'] = 'Artikel-Kategorie <a href="<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'category\']->getLink());?>"><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'category\']->getTitle());?></a>';
$this->items['wcf.page.onlineLocation.com.woltlab.wcf.User'] = 'Benutzerprofil von <a href="{link controller=\'User\' object=$user}{/link}" class="userLink" data-object-id="{$user->userID}">{$user->username}</a>';
$this->dynamicItems['wcf.page.onlineLocation.com.woltlab.wcf.User'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Benutzerprofil von <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'User\', \'object\' => $this->v[\'user\']]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>" class="userLink" data-object-id="<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->userID);?>"><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'user\']->username);?></a>';
$this->items['wcf.page.availableUpdates'] = 'Es sind <a href="{link controller=\'PackageUpdate\' isACP=true}{/link}">Aktualisierungen für installierte Pakete</a> verfügbar.';
$this->dynamicItems['wcf.page.availableUpdates'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Es sind <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'PackageUpdate\', \'isACP\' => true]];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Aktualisierungen für installierte Pakete</a> verfügbar.';
$this->items['wcf.page.error.permissionDenied'] = 'Der Zutritt zu dieser Seite ist {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} leider verwehrt. {if LANGUAGE_USE_INFORMAL_VARIANT}Du besitzt{else}Sie besitzen{/if} nicht die notwendigen Zugriffsrechte, um diese Seite aufrufen zu können.';
$this->dynamicItems['wcf.page.error.permissionDenied'] = 'Der Zutritt zu dieser Seite ist <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> leider verwehrt. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du besitzt<?php } else { ?>Sie besitzen<?php } ?> nicht die notwendigen Zugriffsrechte, um diese Seite aufrufen zu können.';
$this->items['wcf.page.error.permissionDenied.title'] = 'Zugriff verweigert';
$this->items['wcf.page.error.illegalLink'] = 'Die von {if LANGUAGE_USE_INFORMAL_VARIANT}dir{else}Ihnen{/if} angeforderte Seite wurde nicht gefunden. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}überprüfe{else}überprüfen Sie{/if} die Adresse oder {if LANGUAGE_USE_INFORMAL_VARIANT}geh{else}gehen Sie{/if} zurück auf die Startseite.';
$this->dynamicItems['wcf.page.error.illegalLink'] = 'Die von <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>dir<?php } else { ?>Ihnen<?php } ?> angeforderte Seite wurde nicht gefunden. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>überprüfe<?php } else { ?>überprüfen Sie<?php } ?> die Adresse oder <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>geh<?php } else { ?>gehen Sie<?php } ?> zurück auf die Startseite.';
$this->items['wcf.page.error.illegalLink.title'] = 'Seite nicht gefunden';
$this->items['wcf.page.error.backward'] = 'Zurück zur vorherigen Seite';
$this->items['wcf.page.error.insufficientPermissions'] = 'Unzureichende Berechtigungen';
$this->items['wcf.page.error.loginAvailable'] = 'Diese Seite bzw. dieser Bereich steht möglicherweise nur angemeldeten Benutzern zur Verfügung.';
$this->items['wcf.page.error.flood'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du hast{else}Sie haben{/if} zu viele Aktionen dieser Art ausgeführt. Die Funktion wurde daher aus Sicherheitsgründen temporär deaktiviert. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}versuche{else}versuchen Sie{/if} es später erneut.';
$this->dynamicItems['wcf.page.error.flood'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du hast<?php } else { ?>Sie haben<?php } ?> zu viele Aktionen dieser Art ausgeführt. Die Funktion wurde daher aus Sicherheitsgründen temporär deaktiviert. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>versuche<?php } else { ?>versuchen Sie<?php } ?> es später erneut.';
$this->items['wcf.page.jumpTo'] = 'Gehe zu Seite';
$this->items['wcf.page.jumpTo.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} einen Wert zwischen „1“ und „{$pages}“ ein.';
$this->dynamicItems['wcf.page.jumpTo.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> einen Wert zwischen „1“ und „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'pages\']);?>“ ein.';
$this->items['wcf.page.jumpTo.pageNo'] = 'Seitenzahl';
$this->items['wcf.page.redirect.title'] = 'Weiterleitung';
$this->items['wcf.page.redirect.url'] = 'Falls die automatische Weiterleitung nicht funktioniert, {if LANGUAGE_USE_INFORMAL_VARIANT}klicke{else}klicken Sie{/if} bitte hier!';
$this->dynamicItems['wcf.page.redirect.url'] = 'Falls die automatische Weiterleitung nicht funktioniert, <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>klicke<?php } else { ?>klicken Sie<?php } ?> bitte hier!';
$this->items['wcf.page.pageObjectID'] = 'Objekt-ID';
$this->items['wcf.page.pageObjectID.com.woltlab.wcf.Article'] = 'ID des Artikels';
$this->items['wcf.page.pageObjectID.com.woltlab.wcf.CategoryArticleList'] = 'ID der Kategorie';
$this->items['wcf.page.pageObjectID.com.woltlab.wcf.User'] = 'ID des Benutzers';
$this->items['wcf.page.pageObjectID.search'] = 'ID suchen';
$this->items['wcf.page.pageObjectID.search.com.woltlab.wcf.Article'] = 'Artikeltitel durchsuchen';
$this->items['wcf.page.pageObjectID.search.com.woltlab.wcf.CategoryArticleList'] = 'Kategorietitel durchsuchen';
$this->items['wcf.page.pageObjectID.search.com.woltlab.wcf.User'] = 'Benutzernamen durchsuchen';
$this->items['wcf.page.pageObjectID.search.noResults'] = 'Es wurden keine Ergebnisse gefunden.';
$this->items['wcf.page.pageObjectID.search.results'] = 'Suchergebnisse';
$this->items['wcf.page.pageObjectID.search.terms'] = 'Durchsuchen';
$this->items['wcf.page.search'] = 'Seiten durchsuchen';
$this->items['wcf.page.search.error.noResults'] = 'Es wurden keine Ergebnisse gefunden.';
$this->items['wcf.page.search.error.tooShort'] = 'Der Suchbegriff ist zu kurz.';
$this->items['wcf.page.search.name'] = 'Seitennamen durchsuchen';
$this->items['wcf.page.search.results'] = 'Suchergebnisse';
$this->items['wcf.page.comment'] = 'Seiten-Kommentar';
$this->items['wcf.page.commentResponse'] = 'Antwort auf Seiten-Kommentar';
$this->items['wcf.page.recentActivity.pageComment'] = '<strong>{$author}</strong> hat einen Kommentar auf der Seite <strong>{$page->getTitle()}</strong> geschrieben.';
$this->dynamicItems['wcf.page.recentActivity.pageComment'] = '<strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'author\']);?></strong> hat einen Kommentar auf der Seite <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'page\']->getTitle());?></strong> geschrieben.';
$this->items['wcf.page.recentActivity.pageCommentResponse'] = '<strong>{$author}</strong> hat auf einen Kommentar von <strong>{$commentAuthor}</strong> auf der Seite <strong>{$page->getTitle()}</strong> geantwortet.';
$this->dynamicItems['wcf.page.recentActivity.pageCommentResponse'] = '<strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'author\']);?></strong> hat auf einen Kommentar von <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'commentAuthor\']);?></strong> auf der Seite <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'page\']->getTitle());?></strong> geantwortet.';
$this->items['wcf.page.sidebar.left'] = 'Linke Seitenleiste';
$this->items['wcf.page.sidebar.right'] = 'Rechte Seitenleiste';
$this->items['wcf.page.breadcrumb'] = 'Verlaufsnavigation';
$this->items['wcf.page.requestedPage.condition.reverseLogic'] = '„Aufgerufene Seite“-Auswahl umkehren';
$this->items['wcf.page.requestedPage.condition.reverseLogic.description'] = 'Wenn ausgewählt, darf die aufgerufene Seite <strong>keine</strong> der unter „Aufgerufene Seite“ ausgewählten Seiten sein.';
$this->items['wcf.page.box.edit'] = 'Box bearbeiten';
$this->items['wcf.page.menu.outstandingItems'] = '({#$menuItemNode->getOutstandingItems()} {if $menuItemNode->getOutstandingItems() == 1}neuer Eintrag{else}neue Einträge{/if})';
$this->dynamicItems['wcf.page.menu.outstandingItems'] = '(<?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'menuItemNode\']->getOutstandingItems());?> <?php if ($this->v[\'menuItemNode\']->getOutstandingItems() == 1) { ?>neuer Eintrag<?php } else { ?>neue Einträge<?php } ?>)';
$this->items['wcf.page.guestTokenDialog.title'] = 'Verifizierung erforderlich';
