<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.acp.index
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.acp.index.inRescueMode'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du rufst{else}Sie rufen{/if} diese Installation über eine abweichende Domain auf, etwa aufgrund eines Umzuges. Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}korrigiere{else}korrigieren Sie{/if} die Einstellungen unter <a href="{link controller=\'ApplicationManagement\'}{/link}">Apps verwalten</a>.';
$this->dynamicItems['wcf.acp.index.inRescueMode'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du rufst<?php } else { ?>Sie rufen<?php } ?> diese Installation über eine abweichende Domain auf, etwa aufgrund eines Umzuges. Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>korrigiere<?php } else { ?>korrigieren Sie<?php } ?> die Einstellungen unter <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'ApplicationManagement\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Apps verwalten</a>.';
$this->items['wcf.acp.index.setup.notice'] = 'Die Installation wird in wenigen Augenblicken automatisch gestartet, bitte {if LANGUAGE_USE_INFORMAL_VARIANT}lade{else}laden Sie{/if} diese Seite nicht neu.';
$this->dynamicItems['wcf.acp.index.setup.notice'] = 'Die Installation wird in wenigen Augenblicken automatisch gestartet, bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>lade<?php } else { ?>laden Sie<?php } ?> diese Seite nicht neu.';
$this->items['wcf.acp.index.setup.title'] = 'Bitte warten';
$this->items['wcf.acp.index.woltlab.website'] = 'Website';
$this->items['wcf.acp.index.woltlab.manual'] = 'Handbuch';
$this->items['wcf.acp.index.woltlab.forums'] = 'Supportforum';
$this->items['wcf.acp.index.woltlab.tickets'] = 'Ticket-Support';
$this->items['wcf.acp.index.woltlab.pluginStore'] = 'Plugin-Store';
$this->items['wcf.acp.index.missingLanguageItems'] = 'Es wurden fehlende Sprachvariablen protokolliert (zuletzt: {@$missingLanguageItemsMTime|time}). {if LANGUAGE_USE_INFORMAL_VARIANT}Überprüfe{else}Überprüfen Sie{/if} die <a href="{link controller=\'DevtoolsMissingLanguageItemList\'}{/link}">Liste der fehlenden Texte</a> für weitere Informationen.';
$this->dynamicItems['wcf.acp.index.missingLanguageItems'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Es wurden fehlende Sprachvariablen protokolliert (zuletzt: <?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\TimeModifierTemplatePlugin\']->execute([$this->v[\'missingLanguageItemsMTime\']], $this);?>). <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Überprüfe<?php } else { ?>Überprüfen Sie<?php } ?> die <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'DevtoolsMissingLanguageItemList\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Liste der fehlenden Texte</a> für weitere Informationen.';
$this->items['wcf.acp.index.systemIdMismatch'] = 'Die Systemumgebung hat sich verändert. Es wird empfohlen, eine <a href="{link controller=\'SystemCheck\'}{/link}">Systemüberprüfung</a> durchzuführen.';
$this->dynamicItems['wcf.acp.index.systemIdMismatch'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Die Systemumgebung hat sich verändert. Es wird empfohlen, eine <a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'SystemCheck\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Systemüberprüfung</a> durchzuführen.';
$this->items['wcf.acp.index.cacheSanityCheckFailed'] = 'Die eingestellte Cache-Methode („{CACHE_SOURCE_TYPE}“) funktioniert nicht richtig.';
$this->dynamicItems['wcf.acp.index.cacheSanityCheckFailed'] = 'Die eingestellte Cache-Methode („<?=wcf\\util\\StringUtil::encodeHTML(CACHE_SOURCE_TYPE);?>“) funktioniert nicht richtig.';
$this->items['wcf.acp.index.insecureContext'] = 'Die Seite wird nicht über HTTPS aufgerufen. Wichtige Funktionen stehen dadurch nicht zur Verfügung, die für die korrekte Funktionsweise der Software erforderlich sind.';
