<?php /* cache: wcf_TemplateListenerCodeCacheBuilder-3b2bc432f38f0c61fd07e4eb9ceed01ca0bb5a9f (generated at Thu, 08 Jan 2026 08:26:30 +0000) DO NOT EDIT THIS FILE */ return <<<'EOT'
a:1:{s:11:"categoryAdd";a:1:{s:10:"dataFields";a:1:{i:0;s:106:"{if $objectType->objectType == "com.woltlab.wcf.article.category"}{include file='__articleSortField'}{/if}";}}}
EOT;
