<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.global
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.global.button.add'] = 'Hinzufügen';
$this->items['wcf.global.button.back'] = '&laquo; Zurück';
$this->items['wcf.global.button.cancel'] = 'Abbrechen';
$this->items['wcf.global.button.close'] = 'Schließen';
$this->items['wcf.global.button.collapsible'] = 'Auf- und Zuklappen';
$this->items['wcf.global.button.delete'] = 'Löschen';
$this->items['wcf.global.button.disable'] = 'Deaktivieren';
$this->items['wcf.global.button.disabledI18n'] = 'einsprachig';
$this->items['wcf.global.button.edit'] = 'Bearbeiten';
$this->items['wcf.global.button.enable'] = 'Aktivieren';
$this->items['wcf.global.button.fullscreen'] = 'Vollbildmodus';
$this->items['wcf.global.button.hide'] = 'Ausblenden';
$this->items['wcf.global.button.insert'] = 'Einfügen';
$this->items['wcf.global.button.list'] = 'Auflistung';
$this->items['wcf.global.button.more'] = 'Mehr';
$this->items['wcf.global.button.next'] = 'Weiter »';
$this->items['wcf.global.button.preview'] = 'Vorschau';
$this->items['wcf.global.button.refresh'] = 'Aktualisieren';
$this->items['wcf.global.button.reply'] = 'Antworten';
$this->items['wcf.global.button.reset'] = 'Zurücksetzen';
$this->items['wcf.global.button.restore'] = 'Wiederherstellen';
$this->items['wcf.global.button.rss'] = 'RSS-Feed';
$this->items['wcf.global.button.save'] = 'Speichern';
$this->items['wcf.global.button.saveSorting'] = 'Sortierung speichern';
$this->items['wcf.global.button.search'] = 'Suchen';
$this->items['wcf.global.button.submit'] = 'Absenden';
$this->items['wcf.global.button.trash'] = 'In den Papierkorb verschieben';
$this->items['wcf.global.button.upload'] = 'Hochladen';
$this->items['wcf.global.button.readMore'] = 'Weiterlesen';
$this->items['wcf.global.button.resetFilter'] = 'Filter zurücksetzen';
$this->items['wcf.global.button.replace'] = 'Ersetzen';
$this->items['wcf.global.category'] = 'Kategorie';
$this->items['wcf.global.categories'] = 'Kategorien';
$this->items['wcf.global.comments'] = 'Kommentare';
$this->items['wcf.global.confirmation.cancel'] = 'Abbrechen';
$this->items['wcf.global.confirmation.confirm'] = 'OK';
$this->items['wcf.global.confirmation.title'] = 'Bestätigung erforderlich';
$this->items['wcf.global.date'] = 'Datum';
$this->items['wcf.global.decimalPoint'] = ',';
$this->items['wcf.global.description'] = 'Beschreibung';
$this->items['wcf.global.error.ajax.network'] = '<p>Ein Verbindungsaufbau zum Server war nicht möglich, bitte überprüfen Sie Ihre Internetverbindung.</p><p><br></p><p>Fehlermeldung von Ihrem Browser: „{$message}“</p>';
$this->items['wcf.global.error.timeout'] = 'Keine Antwort vom Server erhalten, Anfrage wurde abgebrochen.';
$this->items['wcf.global.error.title'] = 'Fehlermeldung';
$this->items['wcf.global.exception.explanation'] = '<p class="exceptionSubtitle">Was ist passiert?</p>
<p class="exceptionText">Leider ist es bei der Verarbeitung zu einem Fehler gekommen und die Ausführung wurde abgebrochen. Falls möglich, leiten Sie bitte den oben stehenden Fehlercode an den Administrator weiter.</p>
<p class="exceptionText">&nbsp;</p> <!-- required to ensure spacing after copy & paste -->
<p class="exceptionText">
	Administratoren können die vollständige Fehlermeldung mit Hilfe dieses Codes in der Administrationsoberfläche unter „Protokoll » Fehler“ einsehen.
	Zusätzlich wurden die Informationen in die Protokolldatei <span class="exceptionInlineCodeWrapper"><span class="exceptionInlineCode">{$logFile}</span></span> geschrieben und können beispielsweise mit Hilfe eines FTP-Programms abgerufen werden.
</p>
<p class="exceptionText">&nbsp;</p> <!-- required to ensure spacing after copy & paste -->
<p class="exceptionText">Hinweis: Der Fehlercode wird zufällig generiert, erlaubt keinen Rückschluss auf die Ursache und ist daher für Dritte nutzlos.</p>';
$this->items['wcf.global.exception.title'] = 'Ein Fehler ist aufgetreten';
$this->items['wcf.global.exception.subtitle'] = 'Interner Fehlercode: <span class="exceptionInlineCodeWrapper"><span class="exceptionInlineCode">{$exceptionID}</span></span>';
$this->items['wcf.global.filter.button.clear'] = 'Filter löschen';
$this->items['wcf.global.filter.button.visibility'] = 'Ansicht filtern';
$this->items['wcf.global.filter.error.noMatches'] = 'Keine Übereinstimmungen gefunden.';
$this->items['wcf.global.filter.placeholder'] = 'Nach Name filtern';
$this->items['wcf.global.filter.visibility.activeOnly'] = 'Nur markierte Einträge anzeigen';
$this->items['wcf.global.filter.visibility.highlightActive'] = 'Aktive Einträge hervorheben';
$this->items['wcf.global.filter.visibility.showAll'] = 'Alles anzeigen';
$this->items['wcf.global.success'] = 'Die Aktion wurde erfolgreich ausgeführt.';
$this->items['wcf.global.success.add'] = 'Der Eintrag wurde gespeichert.';
$this->items['wcf.global.success.add.editCreatedObject'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} jetzt einen weiteren erstellen oder den <a href="{$objectEditLink}">zuvor erstellten Eintrag bearbeiten</a>.';
$this->items['wcf.global.success.edit'] = 'Die Änderungen wurden gespeichert.';
$this->items['wcf.global.language.noSelection'] = 'Keine Auswahl';
$this->items['wcf.global.loading'] = 'Lädt …';
$this->items['wcf.global.name'] = 'Name';
$this->items['wcf.global.objectID'] = 'ID';
$this->items['wcf.global.page.next'] = 'Nächste Seite';
$this->items['wcf.global.page.pagination'] = 'Navigation';
$this->items['wcf.global.page.previous'] = 'Vorherige Seite';
$this->items['wcf.global.pageDirection'] = 'ltr';
$this->items['wcf.global.scrollDown'] = 'Zum Seitenende';
$this->items['wcf.global.scrollUp'] = 'Zum Seitenanfang';
$this->items['wcf.global.search.enterSearchTerm'] = 'Suchbegriff eingeben';
$this->items['wcf.global.showOrder'] = 'Reihenfolge';
$this->items['wcf.global.sortOrder.ascending'] = 'aufsteigend';
$this->items['wcf.global.sortOrder.descending'] = 'absteigend';
$this->items['wcf.global.state.closed'] = 'Geschlossen';
$this->items['wcf.global.state.trashed'] = 'Im Papierkorb';
$this->items['wcf.global.subject'] = 'Betreff';
$this->items['wcf.global.thousandsSeparator'] = '.';
$this->items['wcf.global.title'] = 'Titel';
$this->items['wcf.global.jumpToPage'] = 'Zur Seite';
$this->items['wcf.global.preview'] = 'Vorschau';
$this->items['wcf.global.multiSelect'] = 'Mehrfache Markierungen sind durch zusätzliches Drücken der Taste „Strg/Ctrl“ (Windows) oder „Befehl/Command“ (Mac OS) möglich.';
$this->items['wcf.global.noDeclaration'] = 'Keine Angabe';
$this->items['wcf.global.defaultValue'] = 'Standard';
$this->items['wcf.global.noSelection'] = '(Keine Auswahl)';
$this->items['wcf.global.acp'] = 'Administrationsoberfläche';
$this->items['wcf.global.acp.short'] = 'Administration';
$this->items['wcf.global.worker.completed'] = 'Aufgabe abgeschlossen';
$this->items['wcf.global.worker.executing'] = 'Aufgaben werden ausgeführt …';
$this->items['wcf.global.filter'] = 'Filter';
$this->items['wcf.global.noItems'] = 'Es wurden keine Einträge gefunden.';
$this->items['wcf.global.button.showAll'] = 'Alle anzeigen';
$this->items['wcf.global.reason'] = 'Begründung';
$this->items['wcf.global.reason.optional'] = 'Begründung (optional)';
$this->items['wcf.global.settings'] = 'Einstellungen';
$this->items['wcf.global.bulkProcessing.warning'] = 'Die Massenbearbeitung führt die unten ausgewählte Aktion <strong>ohne zusätzliche Sicherheitsabfrage</strong> aus!';
$this->items['wcf.global.search'] = 'Suche';
$this->items['wcf.global.select'] = 'Auswählen';
$this->items['wcf.global.sorting'] = 'Sortierung';
$this->items['wcf.global.fontAwesome.selectIcon'] = 'Icon auswählen';
$this->items['wcf.global.button.hideNavigation'] = 'Navigation verbergen';
$this->items['wcf.global.button.showNavigation'] = 'Navigation anzeigen';
$this->items['wcf.global.button.hideSidebar'] = 'Sidebar verbergen';
$this->items['wcf.global.button.showSidebar'] = 'Sidebar anzeigen';
$this->items['wcf.global.button.showSidebarLeft'] = 'Linke Sidebar';
$this->items['wcf.global.button.showMenu'] = 'Menü anzeigen';
$this->items['wcf.global.button.hideMenu'] = 'Menü verbergen';
$this->items['wcf.global.button.markAsRead'] = 'Als gelesen markieren';
$this->items['wcf.global.button.markAllAsRead'] = 'Alle als gelesen markieren';
$this->items['wcf.global.rss.copy'] = 'Link kopieren';
$this->items['wcf.global.rss.copy.success'] = 'Der Link wurde erfolgreich kopiert.';
$this->items['wcf.global.rss.accessToken.info'] = 'Der Link zum anonymen RSS-Feed enthält nur Inhalte, auf die Gäste Zugriff haben. Der Link zum personalisierten RSS-Feed enthält alle Inhalte, auf die {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} Zugriff {if LANGUAGE_USE_INFORMAL_VARIANT}hast{else}haben{/if}.';
$this->items['wcf.global.rss.withAccessToken'] = 'Personalisierter RSS-Feed';
$this->items['wcf.global.rss.withoutAccessToken'] = 'Anonymer RSS-Feed';
$this->items['wcf.global.incompatiblePhpVersion'] = 'Fehlerhafte Server-Konfiguration: Die eingesetzte Version von „PHP” ist nicht kompatibel, ein Betrieb ist nicht möglich. Es wird mindestens PHP in Version 8.1 benötigt, unterstützt werden die Versionen bis PHP 8.3. Für den Einsatz höherer PHP-Versionen muss die Software auf eine aktuelle Version umgestellt werden.';
