<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.acp.firstTimeSetup
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.acp.firstTimeSetup.license'] = 'Erstmalige Einrichtung: Lizenz';
$this->items['wcf.acp.firstTimeSetup.license.credentials'] = 'Lizenzdaten';
$this->items['wcf.acp.firstTimeSetup.license.credentials.customerArea'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du findest{else}Sie finden{/if} die Lizenz- und Seriennummer im <a href="https://www.woltlab.com/license-list/" class="externalURL">Kundenbereich auf woltlab.com</a>.';
$this->dynamicItems['wcf.acp.firstTimeSetup.license.credentials.customerArea'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du findest<?php } else { ?>Sie finden<?php } ?> die Lizenz- und Seriennummer im <a href="https://www.woltlab.com/license-list/" class="externalURL">Kundenbereich auf woltlab.com</a>.';
$this->items['wcf.acp.firstTimeSetup.license.credentials.error.failedConnect'] = 'Es konnte keine ausgehende Verbindung zur Überprüfung der Lizenzdaten aufgebaut werden.';
$this->items['wcf.acp.firstTimeSetup.license.credentials.error.failedValidation'] = 'Die Gültigkeit der Lizenzdaten konnte nicht bestätigt werden.';
$this->items['wcf.acp.firstTimeSetup.license.noCredentials'] = 'Schritt überspringen (nicht empfohlen)';
$this->items['wcf.acp.firstTimeSetup.license.noCredentialsConfirm'] = 'Ohne Eingabe der Lizenzdaten fortfahren';
$this->items['wcf.acp.firstTimeSetup.license.explanation'] = '<p>Die Eingabe von Lizenzdaten ist zur Installation und zur Aktualisierung der gekauften WoltLab Suite™-Apps sowie der Installation von erworbenen Produkten aus dem offiziellen Plugin-Store erforderlich.</p>';
$this->items['wcf.acp.firstTimeSetup.license.noCredentialsConfirm.description'] = 'Die Eingabe der Lizenzdaten wird empfohlen. Falls noch keine Internetverbindung zu unseren Paket-Servern zur Verfügung steht oder Sie noch keine Lizenzdaten besitzen, können Sie die Eingabe überspringen. Lizenzdaten können jederzeit hinterlegt werden, um die gekauften WoltLab Suite™-Apps zu installieren.';
$this->items['wcf.acp.firstTimeSetup.options'] = 'Erstmalige Einrichtung: Allgemeine Einstellungen';
$this->items['wcf.acp.firstTimeSetup.options.description'] = 'Personalisieren Sie Ihre Community, indem Sie einen Namen und optional eine Beschreibung vergeben. Während der Installation haben wir versucht, die Zeitzone automatisch zu erkennen. Es ist jetzt {TIME_NOW|plainTime}. Wählen Sie die korrekte Zeitzone, falls die Uhrzeit nicht korrekt ist.';
$this->dynamicItems['wcf.acp.firstTimeSetup.options.description'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin;
}
?>Personalisieren Sie Ihre Community, indem Sie einen Namen und optional eine Beschreibung vergeben. Während der Installation haben wir versucht, die Zeitzone automatisch zu erkennen. Es ist jetzt <?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\']->execute([TIME_NOW], $this));?>. Wählen Sie die korrekte Zeitzone, falls die Uhrzeit nicht korrekt ist.';
$this->items['wcf.acp.firstTimeSetup.optionsEmail'] = 'Erstmalige Einrichtung: E-Mail-Einstellungen';
$this->items['wcf.acp.firstTimeSetup.optionsEmail.description'] = 'Konfigurieren Sie jetzt die von Ihrer Community genutzten E-Mail-Adressen. Der Versand erfolgt standardmäßig direkt durch PHP, nach Abschluss der Ersteinrichtung haben Sie die Möglichkeit in den Optionen einen SMTP-Server zu hinterlegen.';
$this->items['wcf.acp.firstTimeSetup.completed'] = 'Erstmalige Einrichtung abgeschlossen';
$this->items['wcf.acp.firstTimeSetup.completed.nextSteps'] = 'Die nächsten Schritte';
$this->items['wcf.acp.firstTimeSetup.completed.apps.description'] = 'Erweitern Sie Ihre Community um offizielle Apps und Erweiterungen von WoltLab. Mit wenigen Klicks können Sie Ihre Community um ein Forum, Kalender, Galerie, Blog oder Dateiverwaltung erweitern.';
$this->items['wcf.acp.firstTimeSetup.completed.apps.title'] = 'WoltLab Apps und Erweiterungen installieren';
$this->items['wcf.acp.firstTimeSetup.completed.manual.description'] = 'Im Handbuch finden Sie hilfreiche Anleitungen und Beschreibungen der verschiedenen Funktionen von WoltLab Suite.';
$this->items['wcf.acp.firstTimeSetup.completed.manual.title'] = 'Handbuch für WoltLab Suite';
$this->items['wcf.acp.firstTimeSetup.completed.pluginstore.description'] = 'Im offiziellen Plugin-Store finden Sie viele nützliche Erweiterungen, um Ihre Seite auf Ihre Bedürfnisse zuzuschneiden. Alle angebotenen Erweiterungen werden vorab von WoltLab auf Sicherheit und Stabilität geprüft.';
$this->items['wcf.acp.firstTimeSetup.completed.pluginstore.title'] = 'Erweiterungen und Stile im Plugin-Store';
$this->items['wcf.acp.firstTimeSetup.completed.support.description'] = 'Sie haben Fragen zu einzelnen Funktionen oder haben Probleme bei der Einrichtung Ihrer Installation? Über das Ticket-System im Kundenbereich erhalten Sie Hilfestellung durch unsere Kundenbetreuung.';
$this->items['wcf.acp.firstTimeSetup.completed.support.title'] = 'Ticket-Support für Fragen und Probleme';
