<?php
/**
* WoltLab Suite
* language: de
* encoding: UTF-8
* category: wcf.acp.package
* generated at Thu, 08 Jan 2026 08:26:35 +0000
* 
* DO NOT EDIT THIS FILE
*/
$this->items['wcf.acp.package.application.installed'] = 'Installierte Apps';
$this->items['wcf.acp.package.application.title'] = 'Apps';
$this->items['wcf.acp.package.author'] = 'Entwickler';
$this->items['wcf.acp.package.availableVersions'] = 'Verfügbare Versionen';
$this->items['wcf.acp.package.button.info'] = 'Informationen';
$this->items['wcf.acp.package.button.installPackage'] = 'Paket installieren';
$this->items['wcf.acp.package.button.uninstall'] = 'Deinstallieren';
$this->items['wcf.acp.package.button.update'] = 'Aktualisieren';
$this->items['wcf.acp.package.dependencies.dependent'] = 'Abhängige Pakete';
$this->items['wcf.acp.package.dependencies.dependent.description'] = 'Pakete, die dieses Paket zwingend für den Betrieb benötigen';
$this->items['wcf.acp.package.dependencies.required'] = 'Benötigte Pakete';
$this->items['wcf.acp.package.dependencies.required.description'] = 'Pakete, die zwingend für den Betrieb dieses Paketes benötigt werden';
$this->items['wcf.acp.package.dependencies.title'] = 'Abhängigkeiten';
$this->items['wcf.acp.package.description'] = 'Beschreibung';
$this->items['wcf.acp.package.error.cli.installIsApplication'] = 'Apps können per CLI nicht installiert werden.';
$this->items['wcf.acp.package.error.exceedsPhpLimit'] = 'Die Datei ist größer als das PHP-Limit „upload_max_filesize“ und/oder „post_max_size“.';
$this->items['wcf.acp.package.error.noUniqueAbbreviation'] = 'Es ist bereits eine App installiert, die die gleiche Abkürzung besitzt.';
$this->items['wcf.acp.package.error.noValidPackage'] = 'Das angegebene Archiv ist kein gültiges Paket: {@$validationException->getMessage()}';
$this->dynamicItems['wcf.acp.package.error.noValidPackage'] = 'Das angegebene Archiv ist kein gültiges Paket: <?=$this->v[\'validationException\']->getMessage();?>';
$this->items['wcf.acp.package.error.sql.createTable'] = 'Existierende Tabellen überschreiben';
$this->items['wcf.acp.package.error.sql.createTable.description'] = 'Die oben genannten Tabellen existieren bereits und werden beim Fortfahren der Installation überschrieben. Alle Daten dieser Tabellen gehen unwiderruflich verloren.';
$this->items['wcf.acp.package.error.sql.dropTable'] = 'Existierende Tabellen löschen';
$this->items['wcf.acp.package.error.sql.dropTable.description'] = 'Die oben genannten Tabellen existieren bereits und werden beim Fortfahren der Installation entfernt. Alle Daten dieser Tabellen gehen unwiderruflich verloren.';
$this->items['wcf.acp.package.error.uniqueAlreadyInstalled'] = 'Dieses Paket ist bereits installiert und kann nicht mehrfach installiert werden.';
$this->items['wcf.acp.package.error.noValidInstall'] = 'Das angegebene Paket lässt keine Neuinstallation zu.';
$this->items['wcf.acp.package.error.noValidUpdate'] = 'Paket „{$package->getName()}“ kann mit dem angegebenen Archiv nicht aktualisiert werden.';
$this->dynamicItems['wcf.acp.package.error.noValidUpdate'] = 'Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']->getName());?>“ kann mit dem angegebenen Archiv nicht aktualisiert werden.';
$this->items['wcf.acp.package.error.majorUpgrade'] = 'Das Paket aktualisiert die Installation auf eine neue Major-Version. Aus Stabilitätsgründen können Major-Upgrades ausschließlich über die Paketserver durchgeführt werden. Detaillierte Informationen zur Durchführung des Upgrades finden sich <a href="https://manual.woltlab.com/de/updates/" class="externalURL">in unserem Handbuch</a>.';
$this->items['wcf.acp.package.error.incompatibleStoreProduct'] = 'Das zu installierende Paket ist nicht kompatibel. {if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} nur Pakete installieren, die als kompatibel mit WoltLab Suite {literal}{$versionNumber}{/literal} angegeben werden.';
$this->dynamicItems['wcf.acp.package.error.incompatibleStoreProduct'] = 'Das zu installierende Paket ist nicht kompatibel. <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst<?php } else { ?>Sie können<?php } ?> nur Pakete installieren, die als kompatibel mit WoltLab Suite {$versionNumber} angegeben werden.';
$this->items['wcf.acp.package.identifier'] = 'Bezeichner';
$this->items['wcf.acp.package.information.properties'] = 'Eigenschaften';
$this->items['wcf.acp.package.information.title'] = 'Informationen';
$this->items['wcf.acp.package.installDate'] = 'Installationsdatum';
$this->items['wcf.acp.package.installation.packageStatus'] = 'Status';
$this->items['wcf.acp.package.installation.packageStatus.delivered'] = 'vom Paket bereitgestellt';
$this->items['wcf.acp.package.installation.packageStatus.installed'] = 'bereits installiert';
$this->items['wcf.acp.package.installation.packageStatus.invalidDeliveredPackage'] = 'falsches Paket bereitgestellt ({$package.deliveredPackage})';
$this->dynamicItems['wcf.acp.package.installation.packageStatus.invalidDeliveredPackage'] = 'falsches Paket bereitgestellt (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\'][\'deliveredPackage\']);?>)';
$this->items['wcf.acp.package.installation.packageStatus.missing'] = 'fehlt';
$this->items['wcf.acp.package.installation.packageStatus.missingVersion'] = 'fehlende Paket-Version ({if $package.existingVersion|isset}installierte Version: {$package.existingVersion}{else}bereitgestellte Version: {$package.deliveredVersion}{/if})';
$this->dynamicItems['wcf.acp.package.installation.packageStatus.missingVersion'] = 'fehlende Paket-Version (<?php if (isset($this->v[\'package\'][\'existingVersion\'])) { ?>installierte Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\'][\'existingVersion\']);?><?php } else { ?>bereitgestellte Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\'][\'deliveredVersion\']);?><?php } ?>)';
$this->items['wcf.acp.package.installation.rollback'] = 'Installation rückgängig machen';
$this->items['wcf.acp.package.installation.step.install'] = '„{$packageName}“ wird installiert …';
$this->dynamicItems['wcf.acp.package.installation.step.install'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ wird installiert …';
$this->items['wcf.acp.package.installation.step.install.success'] = 'Installation abgeschlossen';
$this->items['wcf.acp.package.installation.step.update'] = '„{$packageName}“ wird aktualisiert …';
$this->dynamicItems['wcf.acp.package.installation.step.update'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ wird aktualisiert …';
$this->items['wcf.acp.package.installation.step.update.success'] = 'Aktualisierung abgeschlossen';
$this->items['wcf.acp.package.installedVersion'] = 'Installierte Version';
$this->items['wcf.acp.package.install.confirmMessage'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} das Paket <span class="confirmationObject">{@$package->getName()}</span> wirklich installieren?';
$this->dynamicItems['wcf.acp.package.install.confirmMessage'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> das Paket <span class="confirmationObject"><?=$this->v[\'package\']->getName();?></span> wirklich installieren?';
$this->items['wcf.acp.package.install.error.excludedPackages'] = 'Dieses Paket kann aufgrund der folgenden bereits installierten Pakete nicht installiert werden:';
$this->items['wcf.acp.package.install.error.excludedPackages.excludedPackage'] = '„{$excludedPackage}“ ({$excludedPackage->package}){if $excludedPackage->excludedPackageVersion} (ausgeschlossene Version: {$excludedPackage->excludedPackageVersion}, installierte Version: {$excludedPackage->packageVersion}){/if}';
$this->dynamicItems['wcf.acp.package.install.error.excludedPackages.excludedPackage'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\']);?>“ (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\']->package);?>)<?php if ($this->v[\'excludedPackage\']->excludedPackageVersion) { ?> (ausgeschlossene Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\']->excludedPackageVersion);?>, installierte Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\']->packageVersion);?>)<?php } ?>';
$this->items['wcf.acp.package.install.error.excludingPackages'] = 'Die folgenden bereits installierten Pakete schließen eine Installation dieses Pakets aus:';
$this->items['wcf.acp.package.install.error.excludingPackages.excludingPackage'] = '„{$excludingPackage}“ ({$excludingPackage->package}){if $excludingPackage->excludedPackageVersion} (ausgeschlossene Version: {$excludingPackage->excludedPackageVersion}){/if}';
$this->dynamicItems['wcf.acp.package.install.error.excludingPackages.excludingPackage'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludingPackage\']);?>“ (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludingPackage\']->package);?>)<?php if ($this->v[\'excludingPackage\']->excludedPackageVersion) { ?> (ausgeschlossene Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludingPackage\']->excludedPackageVersion);?>)<?php } ?>';
$this->items['wcf.acp.package.install.error.missingRequirements'] = 'Die Abhängigkeiten dieses Paketes konnten nicht aufgelöst werden.';
$this->items['wcf.acp.package.install.installingImportedStyle'] = 'Bei der hochgeladenen Datei handelt es sich um ein Paket, welches einen Stil enthält.';
$this->items['wcf.acp.package.install.optionalPackage.missingRequirements'] = 'Installation nicht möglich, nicht alle benötigten Pakete sind installiert.';
$this->items['wcf.acp.package.install.step.prepare'] = 'Installation wird vorbereitet …';
$this->items['wcf.acp.package.install.title'] = 'Paket-Installation';
$this->items['wcf.acp.package.installation.requiredVersion'] = 'Benötigte Version';
$this->items['wcf.acp.package.license'] = 'Lizenz';
$this->items['wcf.acp.package.list'] = 'Paketliste';
$this->items['wcf.acp.package.name'] = 'Paket';
$this->items['wcf.acp.package.packageDate'] = 'Erstellungsdatum';
$this->items['wcf.acp.package.packageDir.notAvailable'] = 'Das angegebene Verzeichnis enthält bereits eine App.';
$this->items['wcf.acp.package.plugin.installed'] = 'Installierte Pakete';
$this->items['wcf.acp.package.plugin.title'] = 'Erweiterungen';
$this->items['wcf.acp.package.search'] = 'Paket suchen';
$this->items['wcf.acp.package.search.package'] = 'Paketbezeichner';
$this->items['wcf.acp.package.search.package.description'] = 'Suche nach einem bestimmten Paketbezeichner, z.B. „com.woltlab.wcf“';
$this->items['wcf.acp.package.search.packageDescription'] = 'Paketbeschreibung';
$this->items['wcf.acp.package.search.packageName'] = 'Paketname';
$this->items['wcf.acp.package.search.resultList'] = 'Suchergebnisse';
$this->items['wcf.acp.package.searchForUpdates'] = 'Updates suchen';
$this->items['wcf.acp.package.searchForUpdates.benchmark'] = 'Bitte {if LANGUAGE_USE_INFORMAL_VARIANT}deaktiviere{else}deaktivieren Sie{/if} den Benchmark, bevor {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} nach Updates {if LANGUAGE_USE_INFORMAL_VARIANT}suchst{else}suchen{/if}.';
$this->dynamicItems['wcf.acp.package.searchForUpdates.benchmark'] = 'Bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deaktiviere<?php } else { ?>deaktivieren Sie<?php } ?> den Benchmark, bevor <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> nach Updates <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>suchst<?php } else { ?>suchen<?php } ?>.';
$this->items['wcf.acp.package.searchForUpdates.noResults'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Dein{else}Ihr{/if} System ist auf dem aktuellen Stand, es wurden keine ausstehenden Updates gefunden.';
$this->dynamicItems['wcf.acp.package.searchForUpdates.noResults'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Dein<?php } else { ?>Ihr<?php } ?> System ist auf dem aktuellen Stand, es wurden keine ausstehenden Updates gefunden.';
$this->items['wcf.acp.package.source.upload'] = 'Paket hochladen';
$this->items['wcf.acp.package.source.upload.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} eine Paketdatei von {if LANGUAGE_USE_INFORMAL_VARIANT}deinem{else}Ihrem{/if} lokalen Rechner an.';
$this->dynamicItems['wcf.acp.package.source.upload.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> eine Paketdatei von <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>deinem<?php } else { ?>Ihrem<?php } ?> lokalen Rechner an.';
$this->items['wcf.acp.package.startInstall'] = 'Paket installieren';
$this->items['wcf.acp.package.startUpdate'] = 'Paket „{@$package->getName()}“ aktualisieren';
$this->dynamicItems['wcf.acp.package.startUpdate'] = 'Paket „<?=$this->v[\'package\']->getName();?>“ aktualisieren';
$this->items['wcf.acp.package.type.application'] = 'App';
$this->items['wcf.acp.package.type.plugin'] = 'Erweiterung';
$this->items['wcf.acp.package.uninstallation.confirm'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Willst du{else}Wollen Sie{/if} das Paket <span class="confirmationObject">{@$package->getName()}</span> wirklich deinstallieren?';
$this->dynamicItems['wcf.acp.package.uninstallation.confirm'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Willst du<?php } else { ?>Wollen Sie<?php } ?> das Paket <span class="confirmationObject"><?=$this->v[\'package\']->getName();?></span> wirklich deinstallieren?';
$this->items['wcf.acp.package.uninstallation.step.success'] = 'Deinstallation abgeschlossen';
$this->items['wcf.acp.package.uninstallation.step.uninstall'] = 'Paket „{$queue->packageName}“ wird deinstalliert …';
$this->dynamicItems['wcf.acp.package.uninstallation.step.uninstall'] = 'Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'queue\']->packageName);?>“ wird deinstalliert …';
$this->items['wcf.acp.package.uninstallation.title'] = 'Deinstallation';
$this->items['wcf.acp.package.uninstallation.step.prepare'] = 'Deinstallation wird vorbereitet …';
$this->items['wcf.acp.package.updateDate'] = 'Aktualisierungsdatum';
$this->items['wcf.acp.package.update.credentials'] = 'Zugangsdaten';
$this->items['wcf.acp.package.update.credentials.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} Lizenz- und Seriennummer {if LANGUAGE_USE_INFORMAL_VARIANT}findest du{else}finden Sie{/if} im <a class="externalURL" href="https://www.woltlab.com/license-list/"{if EXTERNAL_LINK_TARGET_BLANK} target="_blank"{/if}>Kundenbereich auf woltlab.com</a>.';
$this->dynamicItems['wcf.acp.package.update.credentials.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> Lizenz- und Seriennummer <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>findest du<?php } else { ?>finden Sie<?php } ?> im <a class="externalURL" href="https://www.woltlab.com/license-list/"<?php if (EXTERNAL_LINK_TARGET_BLANK) { ?> target="_blank"<?php } ?>>Kundenbereich auf woltlab.com</a>.';
$this->items['wcf.acp.package.update.error.listNotFound'] = 'Die Paketliste konnte nicht abgerufen werden';
$this->items['wcf.acp.package.update.error.outstandingUpdates'] = 'Bitte installiere{if !LANGUAGE_USE_INFORMAL_VARIANT}n Sie{/if} zuerst alle ausstehenden Updates, bevor {if LANGUAGE_USE_INFORMAL_VARIANT}du{else}Sie{/if} auf eine neue Version {if LANGUAGE_USE_INFORMAL_VARIANT}umsteigst{else}umsteigen{/if}.';
$this->dynamicItems['wcf.acp.package.update.error.outstandingUpdates'] = 'Bitte installiere<?php if ( ! LANGUAGE_USE_INFORMAL_VARIANT) { ?>n Sie<?php } ?> zuerst alle ausstehenden Updates, bevor <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>du<?php } else { ?>Sie<?php } ?> auf eine neue Version <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>umsteigst<?php } else { ?>umsteigen<?php } ?>.';
$this->items['wcf.acp.package.update.errorCode.401'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Deine{else}Ihre{/if} Angaben sind ungültig, bitte {if LANGUAGE_USE_INFORMAL_VARIANT}überprüfe{else}überprüfen Sie{/if} {if $updateServer->requiresLicense()}Lizenz- und Seriennummer{else}Benutzername und Kennwort{/if}.';
$this->dynamicItems['wcf.acp.package.update.errorCode.401'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Deine<?php } else { ?>Ihre<?php } ?> Angaben sind ungültig, bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>überprüfe<?php } else { ?>überprüfen Sie<?php } ?> <?php if ($this->v[\'updateServer\']->requiresLicense()) { ?>Lizenz- und Seriennummer<?php } else { ?>Benutzername und Kennwort<?php } ?>.';
$this->items['wcf.acp.package.update.errorCode.402'] = '{if $updateServer->requiresLicense()}Lizenz- und Seriennummer{else}Benutzername und Kennwort{/if} wurden vom Server akzeptiert, aber es handelt sich um ein kommerzielles Produkt, auf das diese Zugangsdaten keinen Zugriff haben.';
$this->dynamicItems['wcf.acp.package.update.errorCode.402'] = '<?php if ($this->v[\'updateServer\']->requiresLicense()) { ?>Lizenz- und Seriennummer<?php } else { ?>Benutzername und Kennwort<?php } ?> wurden vom Server akzeptiert, aber es handelt sich um ein kommerzielles Produkt, auf das diese Zugangsdaten keinen Zugriff haben.';
$this->items['wcf.acp.package.update.errorCode.403'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Du bist{else}Sie sind{/if} nicht berechtigt, auf dieses Paket zuzugreifen.';
$this->dynamicItems['wcf.acp.package.update.errorCode.403'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du bist<?php } else { ?>Sie sind<?php } ?> nicht berechtigt, auf dieses Paket zuzugreifen.';
$this->items['wcf.acp.package.update.authInsufficient'] = 'Die eingegebenen Zugangsdaten sind korrekt, aber berechtigen nicht zum Download dieses Pakets.';
$this->items['wcf.acp.package.update.licenseNo'] = 'Lizenznummer';
$this->items['wcf.acp.package.update.password'] = 'Kennwort';
$this->items['wcf.acp.package.update.saveCredentials'] = 'Zugangsdaten speichern';
$this->items['wcf.acp.package.update.serialNo'] = 'Seriennummer';
$this->items['wcf.acp.package.update.server'] = 'Paket-Server';
$this->items['wcf.acp.package.update.server.message'] = 'Servermeldung';
$this->items['wcf.acp.package.update.server.url'] = 'URL';
$this->items['wcf.acp.package.update.title'] = 'Paket-Aktualisierung';
$this->items['wcf.acp.package.update.availableUpdates'] = 'Verfügbare Updates';
$this->items['wcf.acp.package.update.unauthorized'] = 'Authentifizierung erforderlich';
$this->items['wcf.acp.package.update.username'] = 'Benutzername';
$this->items['wcf.acp.package.update.step.prepare'] = 'Aktualisierung wird vorbereitet …';
$this->items['wcf.acp.package.update.excludedPackages'] = 'Konflikt';
$this->items['wcf.acp.package.update.excludedPackages.excluded'] = 'Installierte Pakete';
$this->items['wcf.acp.package.update.excludedPackages.excluded.description'] = 'Die folgenden installierten Pakete sind mit den zu installierenden Versionen nicht kompatibel';
$this->items['wcf.acp.package.update.excludedPackages.excluded.package'] = '„{$excludedPackage[existingPackageName]}“ in Version „{$excludedPackage[existingPackageVersion]}“ verhindert eine {if $excludedPackage[action] == \'update\'}Aktualisierung{else}Installation{/if} von „{$excludedPackage[packageName]}“ {if $excludedPackage[action] == \'update\'}auf{else}in{/if} Version „{$excludedPackage[packageVersion]}“';
$this->dynamicItems['wcf.acp.package.update.excludedPackages.excluded.package'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'existingPackageName\']);?>“ in Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'existingPackageVersion\']);?>“ verhindert eine <?php if ($this->v[\'excludedPackage\'][\'action\'] == \'update\') { ?>Aktualisierung<?php } else { ?>Installation<?php } ?> von „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageName\']);?>“ <?php if ($this->v[\'excludedPackage\'][\'action\'] == \'update\') { ?>auf<?php } else { ?>in<?php } ?> Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageVersion\']);?>“';
$this->items['wcf.acp.package.update.excludedPackages.excluding'] = 'Zu installierende Pakete';
$this->items['wcf.acp.package.update.excludedPackages.excluding.description'] = 'Die folgenden zu installierenden Pakete sind mit installierten Paketen nicht kompatibel';
$this->items['wcf.acp.package.update.excludedPackages.excluding.package'] = '„{$excludedPackage[packageName]}“ in Version „{$excludedPackage[packageVersion]}“ ist mit dem bereits installieren Paket „{$excludedPackage[existingPackageName]}“ nicht kompatibel';
$this->dynamicItems['wcf.acp.package.update.excludedPackages.excluding.package'] = '„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageName\']);?>“ in Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'packageVersion\']);?>“ ist mit dem bereits installieren Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'excludedPackage\'][\'existingPackageName\']);?>“ nicht kompatibel';
$this->items['wcf.acp.package.update.path.incoherent'] = 'Das Update erfordert eine Aktualisierung des Paketes „{$packageName}“ (installierte Version: {$currentVersion}) auf Version {$newVersion}, es wurden aber keine passenden Updates gefunden.';
$this->dynamicItems['wcf.acp.package.update.path.incoherent'] = 'Das Update erfordert eine Aktualisierung des Paketes „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ (installierte Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'currentVersion\']);?>) auf Version <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'newVersion\']);?>, es wurden aber keine passenden Updates gefunden.';
$this->items['wcf.acp.package.update.path.unknown'] = 'Das Update erfordert eine Aktualisierung des Paketes „{$packageName}“ (installierte Version: {$currentVersion}) auf Version {$newVersion}, es wurden aber keine verfügbaren Updates gefunden. Möglicherweise fehlt der passende Paket-Server?';
$this->dynamicItems['wcf.acp.package.update.path.unknown'] = 'Das Update erfordert eine Aktualisierung des Paketes „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ (installierte Version: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'currentVersion\']);?>) auf Version <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'newVersion\']);?>, es wurden aber keine verfügbaren Updates gefunden. Möglicherweise fehlt der passende Paket-Server?';
$this->items['wcf.acp.package.update.purchaseRequired'] = 'Kostenpflichtiges Paket';
$this->items['wcf.acp.package.update.purchaseRequired.button.purchase'] = 'Im Plugin-Store anzeigen';
$this->items['wcf.acp.package.update.purchaseRequired.description'] = 'Das Paket „{$packageName}“ ist kostenpflichtig und muss zuvor im Plugin-Store erworben werden.';
$this->dynamicItems['wcf.acp.package.update.purchaseRequired.description'] = 'Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ ist kostenpflichtig und muss zuvor im Plugin-Store erworben werden.';
$this->items['wcf.acp.package.update.paidUpgrade'] = 'Kostenpflichtiges Update';
$this->items['wcf.acp.package.update.paidUpgrade.description'] = 'Das Update für das Paket „{$packageName}“ ist kostenpflichtig und muss zuvor im Plugin-Store erworben werden.';
$this->dynamicItems['wcf.acp.package.update.paidUpgrade.description'] = 'Das Update für das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ ist kostenpflichtig und muss zuvor im Plugin-Store erworben werden.';
$this->items['wcf.acp.package.update.installUpdate'] = 'Dieses Update installieren';
$this->items['wcf.acp.package.update.upgrade'] = 'Dieses Paket wird aktualisiert.';
$this->items['wcf.acp.package.update.newVersion'] = '{$currentVersion} → <span class="packageUpdateNewVersion">{$newVersion}</span>';
$this->dynamicItems['wcf.acp.package.update.newVersion'] = '<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'currentVersion\']);?> → <span class="packageUpdateNewVersion"><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'newVersion\']);?></span>';
$this->items['wcf.acp.package.version'] = 'Version';
$this->items['wcf.acp.package.packageDir.input'] = 'Installationsverzeichnis';
$this->items['wcf.acp.package.upload'] = 'Paket hochladen';
$this->items['wcf.acp.package.optionalPackages'] = 'Optionale Pakete';
$this->items['wcf.acp.package.optionalPackages.description'] = 'Es stehen folgende optionale Pakete zur Auswahl:';
$this->items['wcf.acp.package.search.error.noMatches'] = 'Es wurden keine Pakete gefunden.';
$this->items['wcf.acp.package.url'] = 'Website';
$this->items['wcf.acp.package.error.uploadFailed'] = 'Das Hochladen der ausgewählten Datei ist fehlgeschlagen.';
$this->items['wcf.acp.package.updates'] = 'Aktualisierungen';
$this->items['wcf.acp.package.error.downloadFailed'] = 'Das Herunterladen des Paketes{if $__downloadPackage|isset} „{$__downloadPackage}“{/if} ist fehlgeschlagen.';
$this->dynamicItems['wcf.acp.package.error.downloadFailed'] = 'Das Herunterladen des Paketes<?php if (isset($this->v[\'__downloadPackage\'])) { ?> „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'__downloadPackage\']);?>“<?php } ?> ist fehlgeschlagen.';
$this->items['wcf.acp.package.newVersion'] = 'Neue Version';
$this->items['wcf.acp.package.validation'] = 'Prüfungsergebnis';
$this->items['wcf.acp.package.validation.errorCode.1'] = 'Die Datei „{$archive}“{if !$targetArchive|empty} im Archiv „{$targetArchive}“{/if} konnte nicht gefunden werden.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.1'] = 'Die Datei „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'archive\']);?>“<?php if ( ! empty($this->v[\'targetArchive\'])) { ?> im Archiv „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'targetArchive\']);?>“<?php } ?> konnte nicht gefunden werden.';
$this->items['wcf.acp.package.validation.errorCode.2'] = 'Das Paket „{$archive}“ enthält die notwendige „package.xml“ nicht.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.2'] = 'Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'archive\']);?>“ enthält die notwendige „package.xml“ nicht.';
$this->items['wcf.acp.package.validation.errorCode.3'] = 'Der Paketbezeichner „{$packageName}“ entspricht nicht den Vorgaben und ist ungültig.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.3'] = 'Der Paketbezeichner „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ entspricht nicht den Vorgaben und ist ungültig.';
$this->items['wcf.acp.package.validation.errorCode.4'] = 'Die Paketversion „{$packageVersion}“ entspricht nicht den Vorgaben und ist ungültig.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.4'] = 'Die Paketversion „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageVersion\']);?>“ entspricht nicht den Vorgaben und ist ungültig.';
$this->items['wcf.acp.package.validation.errorCode.5'] = 'Das Paket „{$packageName}“ enthält keine gültigen Installations-Anweisungen.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.5'] = 'Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ enthält keine gültigen Installations-Anweisungen.';
$this->items['wcf.acp.package.validation.errorCode.6'] = 'Das Paket „{$packageName|phrase}“ (installierte Version: „{$packageVersion}“) soll auf Version „{$deliveredPackageVersion}“ aktualisiert werden, ein Update wird jedoch nicht unterstützt.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.6'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([$this->v[\'packageName\']], $this));?>“ (installierte Version: „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageVersion\']);?>“) soll auf Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'deliveredPackageVersion\']);?>“ aktualisiert werden, ein Update wird jedoch nicht unterstützt.';
$this->items['wcf.acp.package.validation.errorCode.7'] = 'Die folgenden installierten Pakete schließen die Installation aufgrund von Inkompatibilitäten aus: <ul class="nativeList">{foreach from=$packages item=package}<li>„{$package}“ ({$package->package})</li>{/foreach}</ul>';
$this->dynamicItems['wcf.acp.package.validation.errorCode.7'] = 'Die folgenden installierten Pakete schließen die Installation aufgrund von Inkompatibilitäten aus: <ul class="nativeList"><?php
$_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3 = $this->v[\'packages\'];
$this->foreachVars[\'528ca38eb27de8cca9bce9d637cb6217c5277eb3\'] = [];
$this->foreachVars[\'528ca38eb27de8cca9bce9d637cb6217c5277eb3\'][\'item\'] = $this->v[\'package\'] ?? null;
if ((is_countable($_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3) && count($_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3) > 0) || (!is_countable($_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3) && $_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3)) {
foreach ($_foreach_528ca38eb27de8cca9bce9d637cb6217c5277eb3 as $this->v[\'package\']) {
?><li>„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']);?>“ (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']->package);?>)</li><?php }
unset($this->v[\'package\']);$this->v[\'package\'] = $this->foreachVars[\'528ca38eb27de8cca9bce9d637cb6217c5277eb3\'][\'item\'];
unset($this->foreachVars[\'528ca38eb27de8cca9bce9d637cb6217c5277eb3\']);
 } ?></ul>';
$this->items['wcf.acp.package.validation.errorCode.8'] = 'Dieses Paket ist inkompatibel mit den folgenden, installierten Paketen: <ul class="nativeList">{foreach from=$packages item=package}<li>„{$package}“ ({$package->package})</li>{/foreach}</ul>';
$this->dynamicItems['wcf.acp.package.validation.errorCode.8'] = 'Dieses Paket ist inkompatibel mit den folgenden, installierten Paketen: <ul class="nativeList"><?php
$_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd = $this->v[\'packages\'];
$this->foreachVars[\'d2f5466a712f1269ea9182abeac5c0ab099b45bd\'] = [];
$this->foreachVars[\'d2f5466a712f1269ea9182abeac5c0ab099b45bd\'][\'item\'] = $this->v[\'package\'] ?? null;
if ((is_countable($_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd) && count($_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd) > 0) || (!is_countable($_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd) && $_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd)) {
foreach ($_foreach_d2f5466a712f1269ea9182abeac5c0ab099b45bd as $this->v[\'package\']) {
?><li>„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']);?>“ (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']->package);?>)</li><?php }
unset($this->v[\'package\']);$this->v[\'package\'] = $this->foreachVars[\'d2f5466a712f1269ea9182abeac5c0ab099b45bd\'][\'item\'];
unset($this->foreachVars[\'d2f5466a712f1269ea9182abeac5c0ab099b45bd\']);
 } ?></ul>';
$this->items['wcf.acp.package.validation.errorCode.9'] = 'Die Installation erfordert das Paket „{$packageName}“ in Version „{$packageVersion}“ oder höher, das mitgelieferte Paket trägt aber die Versionsnummer „{$deliveredPackageVersion}“.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.9'] = 'Die Installation erfordert das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ in Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageVersion\']);?>“ oder höher, das mitgelieferte Paket trägt aber die Versionsnummer „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'deliveredPackageVersion\']);?>“.';
$this->items['wcf.acp.package.validation.errorCode.10'] = 'Benötigt das Paket {if $package === null}„{$packageName}“{else}„{$package}“{/if} in Version „{$packageVersion}“ oder höher, {if $package === null}dies ist aber weder installiert noch wird es mitgeliefert.{else}es ist aber nur Version „{$package->packageVersion}“ installiert.{/if}';
$this->dynamicItems['wcf.acp.package.validation.errorCode.10'] = 'Benötigt das Paket <?php if ($this->v[\'package\'] === null) { ?>„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“<?php } else { ?>„<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']);?>“<?php } ?> in Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageVersion\']);?>“ oder höher, <?php if ($this->v[\'package\'] === null) { ?>dies ist aber weder installiert noch wird es mitgeliefert.<?php } else { ?>es ist aber nur Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'package\']->packageVersion);?>“ installiert.<?php } ?>';
$this->items['wcf.acp.package.validation.errorCode.11'] = 'Die {if $type == \'install\'}Installations{else}Update{/if}-Anweisungen geben für das Package Installation Plugin „{$pip}“ die Datei „{$value}“ an, diese ist jedoch nicht im Archiv enthalten. Mögliche Ursachen:<ul class="nativeList"><li>Die Datei wurde dem Archiv nicht hinzugefügt</li><li>Die Datei existiert, jedoch sind der Dateiname und die Angabe in den Anweisungen abweichend (Tippfehler)</li></ul>';
$this->dynamicItems['wcf.acp.package.validation.errorCode.11'] = 'Die <?php if ($this->v[\'type\'] == \'install\') { ?>Installations<?php } else { ?>Update<?php } ?>-Anweisungen geben für das Package Installation Plugin „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'pip\']);?>“ die Datei „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'value\']);?>“ an, diese ist jedoch nicht im Archiv enthalten. Mögliche Ursachen:<ul class="nativeList"><li>Die Datei wurde dem Archiv nicht hinzugefügt</li><li>Die Datei existiert, jedoch sind der Dateiname und die Angabe in den Anweisungen abweichend (Tippfehler)</li></ul>';
$this->items['wcf.acp.package.validation.errorCode.12'] = 'Das Paket „{$packageName|phrase}“ ist bereits in Version „{$packageVersion}“ installiert.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.12'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin;
}
?>Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PhraseModifierTemplatePlugin\']->execute([$this->v[\'packageName\']], $this));?>“ ist bereits in Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageVersion\']);?>“ installiert.';
$this->items['wcf.acp.package.validation.errorCode.13'] = 'Die API-Version „{$version}“ ist ungültig.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.13'] = 'Die API-Version „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?>“ ist ungültig.';
$this->items['wcf.acp.package.validation.errorCode.14'] = 'Das Paket wurde für eine ältere Version von WoltLab Suite entwickelt und ist nicht kompatibel.';
$this->items['wcf.acp.package.validation.errorCode.15'] = 'Das Paket verfügt über keine Angaben zur API-Kompatibilität, eine Installation mit aktivierten Entwickler-Werkzeugen ist daher nicht möglich.';
$this->items['wcf.acp.package.validation.errorCode.16'] = 'Neben der &lt;void/&gt;-Anweisung werden weitere Package Installation Plugins angegeben.';
$this->items['wcf.acp.package.validation.errorCode.17'] = 'Die &lt;void/&gt;-Anweisung ist in den Installations-Anweisungen unzulässig.';
$this->items['wcf.acp.package.validation.errorCode.18'] = 'Die bereits installierte App „{$application->getPackage()->package}“ verwendet die gleiche App-Abkürzung.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.18'] = 'Die bereits installierte App „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'application\']->getPackage()->package);?>“ verwendet die gleiche App-Abkürzung.';
$this->items['wcf.acp.package.validation.errorCode.19'] = 'Die Versionsnummer „{$version}“ des inkompatiblen Paketes „{$packageName}“ ist ungültig.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.19'] = 'Die Versionsnummer „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?>“ des inkompatiblen Paketes „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ ist ungültig.';
$this->items['wcf.acp.package.validation.errorCode.20'] = 'Das Paket „{$packageName}“ definiert sich selbst als inkompatibel.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.20'] = 'Das Paket „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ definiert sich selbst als inkompatibel.';
$this->items['wcf.acp.package.validation.errorCode.21'] = 'Es ist keine Abhängigkeit auf „com.woltlab.wcf“ definiert.';
$this->items['wcf.acp.package.validation.errorCode.22'] = 'Das Paket „com.woltlab.wcf“ muss mindestens in Version 5.4.22 vorausgesetzt werden.';
$this->items['wcf.acp.package.validation.errorCode.23'] = 'Die Versionsnummer „{$version}“ des benötigten Paketes „{$packageName}“ ist ungültig.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.23'] = 'Die Versionsnummer „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?>“ des benötigten Paketes „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?>“ ist ungültig.';
$this->items['wcf.acp.package.validation.errorCode.24'] = 'Die &lt;packageinformation&gt; enthalten das unbekannte Element „{$tag}“.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.24'] = 'Die &lt;packageinformation&gt; enthalten das unbekannte Element „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'tag\']);?>“.';
$this->items['wcf.acp.package.validation.errorCode.25'] = 'Die &lt;authorinformation&gt; enthalten das unbekannte Element „{$tag}“.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.25'] = 'Die &lt;authorinformation&gt; enthalten das unbekannte Element „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'tag\']);?>“.';
$this->items['wcf.acp.package.validation.errorCode.26'] = 'Es wurden keine (gültigen) &lt;authorinformation&gt; hinterlegt.';
$this->items['wcf.acp.package.validation.errorCode.27'] = 'Es wurde kein (gültiger) &lt;packagename&gt; hinterlegt.';
$this->items['wcf.acp.package.validation.errorCode.28'] = 'Die &lt;packageinformation&gt; enthalten das doppelte Element „{$tag}“.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.28'] = 'Die &lt;packageinformation&gt; enthalten das doppelte Element „<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'tag\']);?>“.';
$this->items['wcf.acp.package.validation.errorCode.29'] = 'Es wurde keine Paketversion angegeben.';
$this->items['wcf.acp.package.validation.errorCode.30'] = 'Es wurde keine Paketdatum angegeben.';
$this->items['wcf.acp.package.validation.errorCode.31'] = 'Die Datei „package.xml“ ist ungültig{if $libxmlOutput}: {$libxmlOutput}{/if}.';
$this->dynamicItems['wcf.acp.package.validation.errorCode.31'] = 'Die Datei „package.xml“ ist ungültig<?php if ($this->v[\'libxmlOutput\']) { ?>: <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'libxmlOutput\']);?><?php } ?>.';
$this->items['wcf.acp.package.validation.failed'] = 'Das hochgeladene Paket kann nicht installiert werden, bitte {if LANGUAGE_USE_INFORMAL_VARIANT}beachte{else}beachten Sie{/if} das unten stehende Prüfungsergebnis.';
$this->dynamicItems['wcf.acp.package.validation.failed'] = 'Das hochgeladene Paket kann nicht installiert werden, bitte <?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>beachte<?php } else { ?>beachten Sie<?php } ?> das unten stehende Prüfungsergebnis.';
$this->items['wcf.acp.package.evaluation.expired'] = 'Die Testphase von <strong>{$packageName}</strong> ist abgelaufen. {if $pluginStoreFileID || $isWoltLab}<br>{if LANGUAGE_USE_INFORMAL_VARIANT}Du kannst{else}Sie können{/if} die aktuelle Version sicher und bequem <strong>{if $pluginStoreFileID}<a href="https://pluginstore.woltlab.com/file/{$pluginStoreFileID}/">im WoltLab Plugin-Store</a>{else}<a href="https://www.woltlab.com/de/kaufen/">auf WoltLab.com</a>{/if}</strong> erwerben.{/if}';
$this->dynamicItems['wcf.acp.package.evaluation.expired'] = 'Die Testphase von <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'packageName\']);?></strong> ist abgelaufen. <?php if ($this->v[\'pluginStoreFileID\'] || $this->v[\'isWoltLab\']) { ?><br><?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Du kannst<?php } else { ?>Sie können<?php } ?> die aktuelle Version sicher und bequem <strong><?php if ($this->v[\'pluginStoreFileID\']) { ?><a href="https://pluginstore.woltlab.com/file/<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'pluginStoreFileID\']);?>/">im WoltLab Plugin-Store</a><?php } else { ?><a href="https://www.woltlab.com/de/kaufen/">auf WoltLab.com</a><?php } ?></strong> erwerben.<?php } ?>';
$this->items['wcf.acp.package.evaluation.pending'] = 'Bei den folgenden installierten Apps handelt es sich um Testversionen, die am <strong>{$evaluationEndDate|plainTime}</strong> ({@$evaluationEndDate|dateDiff:TIME_NOW:true}) ablaufen. Mit Ablauf der Frist deaktiviert sich die App automatisch, es ist dann notwendig diese auf die endgültige Version zu aktualisieren, um den legalen Betrieb fortzusetzen.
<ul class="nativeList">
	{foreach from=$pendingApps item=pendingApp}
		<li>{$pendingApp}</li>
	{/foreach}
</ul>
{if LANGUAGE_USE_INFORMAL_VARIANT}Solltest du{else}Sollten Sie{/if} die <strong>Lizenz für die jeweilige App bereits erworben</strong> haben, so reicht es aus, alle kommenden Updates zu installieren. <strong>Die Testversion wird in diesem Fall automatisch in die Vollversion umgewandelt.</strong>';
$this->dynamicItems['wcf.acp.package.evaluation.pending'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin;
}
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\DateDiffModifierTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateDiffModifierTemplatePlugin\'] = new wcf\\system\\template\\plugin\\DateDiffModifierTemplatePlugin;
}
?>Bei den folgenden installierten Apps handelt es sich um Testversionen, die am <strong><?=wcf\\util\\StringUtil::encodeHTML($this->pluginObjects[\'wcf\\system\\template\\plugin\\PlainTimeModifierTemplatePlugin\']->execute([$this->v[\'evaluationEndDate\']], $this));?></strong> (<?=$this->pluginObjects[\'wcf\\system\\template\\plugin\\DateDiffModifierTemplatePlugin\']->execute([$this->v[\'evaluationEndDate\'],TIME_NOW,true], $this);?>) ablaufen. Mit Ablauf der Frist deaktiviert sich die App automatisch, es ist dann notwendig diese auf die endgültige Version zu aktualisieren, um den legalen Betrieb fortzusetzen.
<ul class="nativeList">
	<?php
$_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07 = $this->v[\'pendingApps\'];
$this->foreachVars[\'7e4c3276698e89e89339e4293ed2631d24b81a07\'] = [];
$this->foreachVars[\'7e4c3276698e89e89339e4293ed2631d24b81a07\'][\'item\'] = $this->v[\'pendingApp\'] ?? null;
if ((is_countable($_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07) && count($_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07) > 0) || (!is_countable($_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07) && $_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07)) {
foreach ($_foreach_7e4c3276698e89e89339e4293ed2631d24b81a07 as $this->v[\'pendingApp\']) {
?>
		<li><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'pendingApp\']);?></li>
	<?php }
unset($this->v[\'pendingApp\']);$this->v[\'pendingApp\'] = $this->foreachVars[\'7e4c3276698e89e89339e4293ed2631d24b81a07\'][\'item\'];
unset($this->foreachVars[\'7e4c3276698e89e89339e4293ed2631d24b81a07\']);
 } ?>
</ul>
<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Solltest du<?php } else { ?>Sollten Sie<?php } ?> die <strong>Lizenz für die jeweilige App bereits erworben</strong> haben, so reicht es aus, alle kommenden Updates zu installieren. <strong>Die Testversion wird in diesem Fall automatisch in die Vollversion umgewandelt.</strong>';
$this->items['wcf.acp.package.search.input'] = 'Suchbegriff eingeben';
$this->items['wcf.acp.package.search.input.description'] = 'Es wird nach Teilübereinstimmungen des Paketnamens, dessen Beschreibung sowie dem internen Bezeichner gesucht.';
$this->items['wcf.acp.package.search.status.idle'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Gib{else}Geben Sie{/if} mindestens drei Buchstaben ein, um die Suche zu starten.';
$this->dynamicItems['wcf.acp.package.search.status.idle'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Gib<?php } else { ?>Geben Sie<?php } ?> mindestens drei Buchstaben ein, um die Suche zu starten.';
$this->items['wcf.acp.package.search.status.loading'] = 'Suche läuft …';
$this->items['wcf.acp.package.search.status.noResults'] = 'Die Suche ergab keine Treffer.';
$this->items['wcf.acp.package.search.status.refreshDatabase'] = 'Die Paketlisten werden aktualisiert …';
$this->items['wcf.acp.package.search.result.official'] = '{if $count === 0}Keine{elseif $count === 1}Ein{else}{#$count}{/if} Treffer in offiziellen WoltLab®-Paketen';
$this->dynamicItems['wcf.acp.package.search.result.official'] = '<?php if ($this->v[\'count\'] === 0) { ?>Keine<?php } elseif ($this->v[\'count\'] === 1) { ?>Ein<?php } else { ?><?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'count\']);?><?php } ?> Treffer in offiziellen WoltLab®-Paketen';
$this->items['wcf.acp.package.search.result.thirdParty'] = '{if $count === 0}Keine{elseif $count === 1}Ein{else}{#$count}{/if} Treffer in Paketquellen von Drittanbietern';
$this->dynamicItems['wcf.acp.package.search.result.thirdParty'] = '<?php if ($this->v[\'count\'] === 0) { ?>Keine<?php } elseif ($this->v[\'count\'] === 1) { ?>Ein<?php } else { ?><?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'count\']);?><?php } ?> Treffer in Paketquellen von Drittanbietern';
$this->items['wcf.acp.package.search.result.trusted'] = '{if $count === 0}Keine{elseif $count === 1}Ein{else}{#$count}{/if} Treffer in offiziellen Paketquellen';
$this->dynamicItems['wcf.acp.package.search.result.trusted'] = '<?php if ($this->v[\'count\'] === 0) { ?>Keine<?php } elseif ($this->v[\'count\'] === 1) { ?>Ein<?php } else { ?><?=wcf\\util\\StringUtil::formatNumeric((float)$this->v[\'count\']);?><?php } ?> Treffer in offiziellen Paketquellen';
$this->items['wcf.acp.package.error.databaseChange'] = 'Das Datenbanklayout konnte aufgrund folgender Fehler nicht aktualisiert werden:
{implode from=$errors item=error glue=\' \'}
	{if $error[type] === \'unregisteredTableDrop\'}
		Die unbekannte Tabelle {$error[tableName]} kann nicht gelöscht werden.
	{else if $error[type] === \'foreignTableDrop\'}
		Die Tabelle {$error[tableName]} gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	{else if $error[type] === \'unregisteredTableChange\'}
		Die unbekannte Tabelle {$error[tableName]} kann nicht verändert werden.
	{else if $error[type] === \'foreignColumnDrop\'}
		Die Spalte {$error[tableName]}.{$error[columnName]} gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	{else if $error[type] === \'foreignColumnChange\'}
		Die Spalte {$error[tableName]}.{$error[columnName]} gehört zu einem anderen Paket und kann deshalb nicht verändert werden.
	{else if $error[type] === \'renameNonexistingColumn\'}
		Die Spalte {$error[tableName]}.{$error[columnName]} existiert nicht und kann deshalb nicht umbenannt werden.
	{else if $error[type] === \'foreignIndexDrop\'}
		Der Index {$error[tableName]} ({$error[columnNames]}) gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	{else if $error[type] === \'nonexistingColumnInIndex\'}
		Der Index {$error[tableName]} ({$error[columnNames]}) enthält die nicht existierende Spalte {$error[columnName]}.
	{else if $error[type] === \'nullColumnInPrimaryIndex\'}
		Der Primärindex {$error[tableName]} ({$error[columnNames]}) enthält die Spalte {$error[columnName]}, deren Werte NULL sein können.
	{else if $error[type] === \'foreignForeignKeyDrop\'}
		Der Fremdschlüssel {$error[tableName]} ({$error[columnNames]}) gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	{else if $error[type] === \'unknownTableInForeignKey\'}
		Der Fremdschlüssel {$error[tableName]} ({$error[columnNames]}) referenziert eine unbekannte Tabelle {$error[referencedTableName]}.
	{else if $error[type] === \'missingFkSuffixInForeignKey\'}
		Der Name des Fremdschlüssels {$error[name]} hat kein \'_fk\'-Suffix.
	{else if $error[type] === \'duplicateColumnInIndex\'}
		Der Index {$error[tableName]} ({$error[columnNames]}) enthält doppelte Spalten.
	{else if $error[type] === \'primaryNotCalledPrimary\'}
		Der Primärindex {$error[tableName]} ({$error[columnNames]}) heißt nicht \'PRIMARY\'.
	{else}
		Unbekannter Fehler.
	{/if}
{/implode}';
$this->dynamicItems['wcf.acp.package.error.databaseChange'] = 'Das Datenbanklayout konnte aufgrund folgender Fehler nicht aktualisiert werden:
<?php
$_length7d601d51d88a76d612d0bddc2ead5f3da0ee6130 = count($this->v[\'errors\']);
$_i7d601d51d88a76d612d0bddc2ead5f3da0ee6130 = 0;
$_item7d601d51d88a76d612d0bddc2ead5f3da0ee6130 = $this->v[\'error\'] ?? null;
$_key7d601d51d88a76d612d0bddc2ead5f3da0ee6130 =  null;
foreach ($this->v[\'errors\'] as $this->v[\'error\']) { ?>
	<?php if ($this->v[\'error\'][\'type\'] === \'unregisteredTableDrop\') { ?>
		Die unbekannte Tabelle <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> kann nicht gelöscht werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'foreignTableDrop\') { ?>
		Die Tabelle <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'unregisteredTableChange\') { ?>
		Die unbekannte Tabelle <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> kann nicht verändert werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'foreignColumnDrop\') { ?>
		Die Spalte <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?>.<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnName\']);?> gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'foreignColumnChange\') { ?>
		Die Spalte <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?>.<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnName\']);?> gehört zu einem anderen Paket und kann deshalb nicht verändert werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'renameNonexistingColumn\') { ?>
		Die Spalte <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?>.<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnName\']);?> existiert nicht und kann deshalb nicht umbenannt werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'foreignIndexDrop\') { ?>
		Der Index <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'nonexistingColumnInIndex\') { ?>
		Der Index <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) enthält die nicht existierende Spalte <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnName\']);?>.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'nullColumnInPrimaryIndex\') { ?>
		Der Primärindex <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) enthält die Spalte <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnName\']);?>, deren Werte NULL sein können.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'foreignForeignKeyDrop\') { ?>
		Der Fremdschlüssel <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) gehört zu einem anderen Paket und kann deshalb nicht gelöscht werden.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'unknownTableInForeignKey\') { ?>
		Der Fremdschlüssel <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) referenziert eine unbekannte Tabelle <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'referencedTableName\']);?>.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'missingFkSuffixInForeignKey\') { ?>
		Der Name des Fremdschlüssels <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'name\']);?> hat kein \'_fk\'-Suffix.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'duplicateColumnInIndex\') { ?>
		Der Index <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) enthält doppelte Spalten.
	<?php } elseif ($this->v[\'error\'][\'type\'] === \'primaryNotCalledPrimary\') { ?>
		Der Primärindex <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'tableName\']);?> (<?=wcf\\util\\StringUtil::encodeHTML($this->v[\'error\'][\'columnNames\']);?>) heißt nicht \'PRIMARY\'.
	<?php } else { ?>
		Unbekannter Fehler.
	<?php } ?>
<?php
if (++$_i7d601d51d88a76d612d0bddc2ead5f3da0ee6130 < $_length7d601d51d88a76d612d0bddc2ead5f3da0ee6130) { echo \' \'; }
}
unset($this->v[\'error\']);$this->v[\'error\'] = $_item7d601d51d88a76d612d0bddc2ead5f3da0ee6130;
unset($_length7d601d51d88a76d612d0bddc2ead5f3da0ee6130, $_i7d601d51d88a76d612d0bddc2ead5f3da0ee6130);
unset($_item7d601d51d88a76d612d0bddc2ead5f3da0ee6130, $_key7d601d51d88a76d612d0bddc2ead5f3da0ee6130);
?>';
$this->items['wcf.acp.package.application.isTainted'] = 'Die App{if $taintedApplication|isset} <strong>{$taintedApplication->getPackage()->getTitle()}</strong>{/if} ist nicht vollständig installiert. Für eine weitere Verwendung der App ist eine Deinstallation mit anschließender Neuinstallation von Nöten.';
$this->dynamicItems['wcf.acp.package.application.isTainted'] = 'Die App<?php if (isset($this->v[\'taintedApplication\'])) { ?> <strong><?=wcf\\util\\StringUtil::encodeHTML($this->v[\'taintedApplication\']->getPackage()->getTitle());?></strong><?php } ?> ist nicht vollständig installiert. Für eine weitere Verwendung der App ist eine Deinstallation mit anschließender Neuinstallation von Nöten.';
$this->items['wcf.acp.package.enableUpgradeOverride'] = 'Aktualisierung auf WoltLab Suite {$version}';
$this->dynamicItems['wcf.acp.package.enableUpgradeOverride'] = 'Aktualisierung auf WoltLab Suite <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?>';
$this->items['wcf.acp.package.enableUpgradeOverride.enable'] = 'Upgrade auf die neue Version freigeben';
$this->items['wcf.acp.package.enableUpgradeOverride.issues'] = 'Die folgenden Probleme verhindern aktuell eine Aktualisierung:';
$this->items['wcf.acp.package.enableUpgradeOverride.success'] = 'Die Überprüfung war erfolgreich, alle Systemvoraussetzungen für die Durchführung des Upgrades sind erfüllt.';
$this->items['wcf.acp.package.availableUpgradeVersion'] = 'Die neue WoltLab Suite {$version} steht zur Installation bereit. Eine Anleitung zur Durchführung des Upgrades steht im <a href="https://manual.woltlab.com/de/updates/#update-von-woltlab-suite-55-auf-60" class="externalURL">Handbuch</a> zur Verfügung.<br>
<br>
<a href="{link controller=\'PackageEnableUpgradeOverride\' application=\'wcf\'}{/link}">Systemvoraussetzungen prüfen, um das Upgrade freizugeben</a>';
$this->dynamicItems['wcf.acp.package.availableUpgradeVersion'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Die neue WoltLab Suite <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?> steht zur Installation bereit. Eine Anleitung zur Durchführung des Upgrades steht im <a href="https://manual.woltlab.com/de/updates/#update-von-woltlab-suite-55-auf-60" class="externalURL">Handbuch</a> zur Verfügung.<br>
<br>
<a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'PackageEnableUpgradeOverride\', \'application\' => \'wcf\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Systemvoraussetzungen prüfen, um das Upgrade freizugeben</a>';
$this->items['wcf.acp.package.upgradeOverrideEnabled'] = 'Die Installation der neuen WoltLab Suite {$version} wurde freigegeben. Zur Durchführung des Upgrades klicken Sie bitte auf den Button „Updates suchen“.<br>
<br>
<a href="{link controller=\'PackageEnableUpgradeOverride\' application=\'wcf\'}{/link}">Upgrade abbrechen</a>';
$this->dynamicItems['wcf.acp.package.upgradeOverrideEnabled'] = '<?php
if (!isset($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'])) {
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\'] = new wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin;
}
?>Die Installation der neuen WoltLab Suite <?=wcf\\util\\StringUtil::encodeHTML($this->v[\'version\']);?> wurde freigegeben. Zur Durchführung des Upgrades klicken Sie bitte auf den Button „Updates suchen“.<br>
<br>
<a href="<?php $this->tagStack[] = [\'link\', [\'controller\' => \'PackageEnableUpgradeOverride\', \'application\' => \'wcf\']];
$this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->init($this->tagStack[count($this->tagStack) - 1][1], $this);
while ($this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->next($this)) { ob_start(); ?><?php echo $this->pluginObjects[\'wcf\\system\\template\\plugin\\LinkBlockTemplatePlugin\']->execute($this->tagStack[count($this->tagStack) - 1][1], ob_get_clean(), $this); }
array_pop($this->tagStack);?>">Upgrade abbrechen</a>';
$this->items['wcf.acp.package.quickInstallation'] = 'Installation per StoreCode';
$this->items['wcf.acp.package.quickInstallation.code'] = 'StoreCode';
$this->items['wcf.acp.package.quickInstallation.code.error.invalid'] = 'Der eingegebene StoreCode ist ungültig.';
$this->items['wcf.acp.package.quickInstallation.code.description'] = '{if LANGUAGE_USE_INFORMAL_VARIANT}Füge{else}Fügen Sie{/if} den StoreCode aus dem offiziellen Plugin-Store aus der Zwischenablage ein, um die Installation zu starten.';
$this->dynamicItems['wcf.acp.package.quickInstallation.code.description'] = '<?php if (LANGUAGE_USE_INFORMAL_VARIANT) { ?>Füge<?php } else { ?>Fügen Sie<?php } ?> den StoreCode aus dem offiziellen Plugin-Store aus der Zwischenablage ein, um die Installation zu starten.';
$this->items['wcf.acp.package.pluginStore.file'] = 'WoltLab® Plugin-Store';
$this->items['wcf.acp.package.pluginStore.file.link'] = 'Eintrag im Plugin-Store anzeigen';
$this->items['wcf.acp.package.packageName.package1'] = 'WoltLab Suite Core';
$this->items['wcf.acp.package.packageDescription.package1'] = 'Freies CMS und Web-Framework, das eindrucksvolle Websites und Communities ermöglicht.';
