<?php
/**
* generated at Thu, 08 Jan 2026 08:26:36 +0000
*/
if (!\defined('ENABLE_ENTERPRISE_MODE')) \define('ENABLE_ENTERPRISE_MODE', 0);
if (!\defined('LAST_UPDATE_TIME')) \define('LAST_UPDATE_TIME', 1767860787);
if (!\defined('WCF_UUID')) \define('WCF_UUID', 'e5cca1dd-47cc-40bf-b253-32e413445cda');
if (!\defined('FIRST_TIME_SETUP_STATE')) \define('FIRST_TIME_SETUP_STATE', -1);
if (!\defined('SERVICE_WORKER_PUBLIC_KEY')) \define('SERVICE_WORKER_PUBLIC_KEY', '');
if (!\defined('SERVICE_WORKER_PRIVATE_KEY')) \define('SERVICE_WORKER_PRIVATE_KEY', '');
if (!\defined('VISITOR_USE_TINY_BUILD')) \define('VISITOR_USE_TINY_BUILD', 0);
if (!\defined('MODULE_ARTICLE')) \define('MODULE_ARTICLE', 1);
if (!\defined('MODULE_SMILEY')) \define('MODULE_SMILEY', 1);
if (!\defined('MODULE_USERS_ONLINE')) \define('MODULE_USERS_ONLINE', 1);
if (!\defined('MODULE_USER_RANK')) \define('MODULE_USER_RANK', 1);
if (!\defined('MODULE_USER_SIGNATURE')) \define('MODULE_USER_SIGNATURE', 1);
if (!\defined('MODULE_MEMBERS_LIST')) \define('MODULE_MEMBERS_LIST', 1);
if (!\defined('MODULE_TEAM_PAGE')) \define('MODULE_TEAM_PAGE', 1);
if (!\defined('MODULE_LIKE')) \define('MODULE_LIKE', 1);
if (!\defined('MODULE_USER_PROFILE_WALL')) \define('MODULE_USER_PROFILE_WALL', 1);
if (!\defined('MODULE_TROPHY')) \define('MODULE_TROPHY', 1);
if (!\defined('MODULE_TAGGING')) \define('MODULE_TAGGING', 1);
if (!\defined('MODULE_POLL')) \define('MODULE_POLL', 1);
if (!\defined('MODULE_WCF_AD')) \define('MODULE_WCF_AD', 0);
if (!\defined('ENABLE_DEBUG_MODE')) \define('ENABLE_DEBUG_MODE', 0);
if (!\defined('ENABLE_PRODUCTION_DEBUG_MODE')) \define('ENABLE_PRODUCTION_DEBUG_MODE', 1);
if (!\defined('ENABLE_BENCHMARK')) \define('ENABLE_BENCHMARK', 0);
if (!\defined('ENABLE_DEVELOPER_TOOLS')) \define('ENABLE_DEVELOPER_TOOLS', 0);
if (!\defined('PAGE_TITLE')) \define('PAGE_TITLE', 'WoltLab Suite');
if (!\defined('PAGE_DESCRIPTION')) \define('PAGE_DESCRIPTION', '');
if (!\defined('USE_PAGE_TITLE_ON_LANDING_PAGE')) \define('USE_PAGE_TITLE_ON_LANDING_PAGE', 1);
if (!\defined('META_DESCRIPTION')) \define('META_DESCRIPTION', '');
if (!\defined('OG_IMAGE')) \define('OG_IMAGE', '');
if (!\defined('FB_SHARE_APP_ID')) \define('FB_SHARE_APP_ID', '');
if (!\defined('SHOW_VERSION_NUMBER')) \define('SHOW_VERSION_NUMBER', 1);
if (!\defined('EXTERNAL_LINK_TARGET_BLANK')) \define('EXTERNAL_LINK_TARGET_BLANK', 0);
if (!\defined('SHOW_UPDATE_NOTICE_FRONTEND')) \define('SHOW_UPDATE_NOTICE_FRONTEND', 1);
if (!\defined('LANGUAGE_USE_INFORMAL_VARIANT')) \define('LANGUAGE_USE_INFORMAL_VARIANT', 0);
if (!\defined('SHOW_STYLE_CHANGER')) \define('SHOW_STYLE_CHANGER', 0);
if (!\defined('ENABLE_AD_ROTATION')) \define('ENABLE_AD_ROTATION', 1);
if (!\defined('ENABLE_POLLING')) \define('ENABLE_POLLING', 1);
if (!\defined('PAGE_LOGO_LINK_TO_APP_DEFAULT')) \define('PAGE_LOGO_LINK_TO_APP_DEFAULT', 1);
if (!\defined('BREADCRUMBS_HOME_USE_PAGE_TITLE')) \define('BREADCRUMBS_HOME_USE_PAGE_TITLE', 1);
if (!\defined('INTERNAL_HOSTNAMES')) \define('INTERNAL_HOSTNAMES', '');
if (!\defined('HEAD_CODE')) \define('HEAD_CODE', '');
if (!\defined('FOOTER_CODE')) \define('FOOTER_CODE', '');
if (!\defined('URL_OMIT_INDEX_PHP')) \define('URL_OMIT_INDEX_PHP', 0);
if (!\defined('URL_TITLE_COMPONENT_REPLACEMENT')) \define('URL_TITLE_COMPONENT_REPLACEMENT', '');
if (!\defined('SITEMAP_INDEX_TIME_FRAME')) \define('SITEMAP_INDEX_TIME_FRAME', 365);
if (!\defined('OFFLINE')) \define('OFFLINE', 0);
if (!\defined('OFFLINE_MESSAGE')) \define('OFFLINE_MESSAGE', '');
if (!\defined('OFFLINE_MESSAGE_ALLOW_HTML')) \define('OFFLINE_MESSAGE_ALLOW_HTML', 0);
if (!\defined('LOG_IP_ADDRESS')) \define('LOG_IP_ADDRESS', 0);
if (!\defined('PRUNE_IP_ADDRESS')) \define('PRUNE_IP_ADDRESS', 30);
if (!\defined('IP_ADDRESS_SEARCH_ENGINE')) \define('IP_ADDRESS_SEARCH_ENGINE', '');
if (!\defined('IMAGE_ADAPTER_TYPE')) \define('IMAGE_ADAPTER_TYPE', 'imagick');
if (!\defined('SEARCH_ENGINE')) \define('SEARCH_ENGINE', 'mysql');
if (!\defined('EXCEPTION_PRIVACY')) \define('EXCEPTION_PRIVACY', 'reduced');
if (!\defined('COOKIE_PREFIX')) \define('COOKIE_PREFIX', 'wsc_ee13ae_');
if (!\defined('PACKAGE_SERVER_AUTH_CODE')) \define('PACKAGE_SERVER_AUTH_CODE', '');
if (!\defined('PROXY_SERVER_HTTP')) \define('PROXY_SERVER_HTTP', '');
if (!\defined('USER_ONLINE_TIMEOUT')) \define('USER_ONLINE_TIMEOUT', 900);
if (!\defined('ENABLE_USER_AUTHENTICATION_FAILURE')) \define('ENABLE_USER_AUTHENTICATION_FAILURE', 1);
if (!\defined('USER_AUTHENTICATION_FAILURE_TIMEOUT')) \define('USER_AUTHENTICATION_FAILURE_TIMEOUT', 7200);
if (!\defined('USER_AUTHENTICATION_FAILURE_IP_CAPTCHA')) \define('USER_AUTHENTICATION_FAILURE_IP_CAPTCHA', 3);
if (!\defined('USER_AUTHENTICATION_FAILURE_IP_BLOCK')) \define('USER_AUTHENTICATION_FAILURE_IP_BLOCK', 10);
if (!\defined('USER_AUTHENTICATION_FAILURE_USER_CAPTCHA')) \define('USER_AUTHENTICATION_FAILURE_USER_CAPTCHA', 3);
if (!\defined('USER_AUTHENTICATION_FAILURE_EXPIRATION')) \define('USER_AUTHENTICATION_FAILURE_EXPIRATION', 30);
if (!\defined('SIGNATURE_SECRET')) \define('SIGNATURE_SECRET', 'f053941109a8945641f96ba2869b2392c0a9c69c');
if (!\defined('BLACKLIST_SFS_ENABLE')) \define('BLACKLIST_SFS_ENABLE', 1);
if (!\defined('BLACKLIST_SFS_USERNAME')) \define('BLACKLIST_SFS_USERNAME', 'skip');
if (!\defined('BLACKLIST_SFS_EMAIL_ADDRESS')) \define('BLACKLIST_SFS_EMAIL_ADDRESS', 'moreThanOnce');
if (!\defined('BLACKLIST_SFS_IP_ADDRESS')) \define('BLACKLIST_SFS_IP_ADDRESS', '90percentile');
if (!\defined('CAPTCHA_TYPE')) \define('CAPTCHA_TYPE', '');
if (!\defined('REGISTER_USE_CAPTCHA')) \define('REGISTER_USE_CAPTCHA', 1);
if (!\defined('LOST_PASSWORD_USE_CAPTCHA')) \define('LOST_PASSWORD_USE_CAPTCHA', 1);
if (!\defined('RECAPTCHA_PUBLICKEY')) \define('RECAPTCHA_PUBLICKEY', '');
if (!\defined('RECAPTCHA_PRIVATEKEY')) \define('RECAPTCHA_PRIVATEKEY', '');
if (!\defined('RECAPTCHA_PUBLICKEY_INVISIBLE')) \define('RECAPTCHA_PUBLICKEY_INVISIBLE', '');
if (!\defined('RECAPTCHA_PRIVATEKEY_INVISIBLE')) \define('RECAPTCHA_PRIVATEKEY_INVISIBLE', '');
if (!\defined('TIMEZONE')) \define('TIMEZONE', 'Europe/Berlin');
if (!\defined('GOOGLE_MAPS_API_KEY')) \define('GOOGLE_MAPS_API_KEY', '');
if (!\defined('GOOGLE_MAPS_ZOOM')) \define('GOOGLE_MAPS_ZOOM', '13');
if (!\defined('GOOGLE_MAPS_DEFAULT_LATITUDE')) \define('GOOGLE_MAPS_DEFAULT_LATITUDE', '52.517');
if (!\defined('GOOGLE_MAPS_DEFAULT_LONGITUDE')) \define('GOOGLE_MAPS_DEFAULT_LONGITUDE', '13.4');
if (!\defined('MAIL_FROM_NAME')) \define('MAIL_FROM_NAME', 'Admin');
if (!\defined('MAIL_FROM_ADDRESS')) \define('MAIL_FROM_ADDRESS', 'test@test.de');
if (!\defined('MAIL_ADMIN_ADDRESS')) \define('MAIL_ADMIN_ADDRESS', 'test@test.de');
if (!\defined('MAIL_SIGNATURE')) \define('MAIL_SIGNATURE', '');
if (!\defined('MAIL_SIGNATURE_HTML')) \define('MAIL_SIGNATURE_HTML', '');
if (!\defined('MAIL_SEND_METHOD')) \define('MAIL_SEND_METHOD', 'php');
if (!\defined('MAIL_SMTP_HOST')) \define('MAIL_SMTP_HOST', '');
if (!\defined('MAIL_SMTP_PORT')) \define('MAIL_SMTP_PORT', 587);
if (!\defined('MAIL_SMTP_STARTTLS')) \define('MAIL_SMTP_STARTTLS', 'encrypt');
if (!\defined('MAIL_SMTP_USER')) \define('MAIL_SMTP_USER', '');
if (!\defined('MAIL_SMTP_PASSWORD')) \define('MAIL_SMTP_PASSWORD', '');
if (!\defined('MAIL_USE_F_PARAM')) \define('MAIL_USE_F_PARAM', 1);
if (!\defined('CACHE_SOURCE_TYPE')) \define('CACHE_SOURCE_TYPE', 'disk');
if (!\defined('CACHE_SOURCE_REDIS_HOST')) \define('CACHE_SOURCE_REDIS_HOST', '');
if (!\defined('AVAILABLE_PAYMENT_METHODS')) \define('AVAILABLE_PAYMENT_METHODS', '');
if (!\defined('PAYPAL_EMAIL_ADDRESS')) \define('PAYPAL_EMAIL_ADDRESS', '');
if (!\defined('MODULE_PAID_SUBSCRIPTION')) \define('MODULE_PAID_SUBSCRIPTION', 0);
if (!\defined('PAID_SUBSCRIPTION_ENABLE_TOS_CONFIRMATION')) \define('PAID_SUBSCRIPTION_ENABLE_TOS_CONFIRMATION', 0);
if (!\defined('PAID_SUBSCRIPTION_TOS_URL')) \define('PAID_SUBSCRIPTION_TOS_URL', '');
if (!\defined('ATTACHMENT_RETAIN_DIMENSIONS')) \define('ATTACHMENT_RETAIN_DIMENSIONS', 0);
if (!\defined('ATTACHMENT_THUMBNAIL_HEIGHT')) \define('ATTACHMENT_THUMBNAIL_HEIGHT', 198);
if (!\defined('ATTACHMENT_THUMBNAIL_WIDTH')) \define('ATTACHMENT_THUMBNAIL_WIDTH', 352);
if (!\defined('ATTACHMENT_IMAGE_AUTOSCALE')) \define('ATTACHMENT_IMAGE_AUTOSCALE', 1);
if (!\defined('ATTACHMENT_IMAGE_AUTOSCALE_MAX_WIDTH')) \define('ATTACHMENT_IMAGE_AUTOSCALE_MAX_WIDTH', 1920);
if (!\defined('ATTACHMENT_IMAGE_AUTOSCALE_MAX_HEIGHT')) \define('ATTACHMENT_IMAGE_AUTOSCALE_MAX_HEIGHT', 1200);
if (!\defined('ATTACHMENT_IMAGE_AUTOSCALE_FILE_TYPE')) \define('ATTACHMENT_IMAGE_AUTOSCALE_FILE_TYPE', 'keep');
if (!\defined('ATTACHMENT_IMAGE_AUTOSCALE_QUALITY')) \define('ATTACHMENT_IMAGE_AUTOSCALE_QUALITY', 80);
if (!\defined('MODULE_EDIT_HISTORY')) \define('MODULE_EDIT_HISTORY', 1);
if (!\defined('EDIT_HISTORY_EXPIRATION')) \define('EDIT_HISTORY_EXPIRATION', 90);
if (!\defined('ENABLE_SHARE_BUTTONS')) \define('ENABLE_SHARE_BUTTONS', 1);
if (!\defined('SHARE_BUTTONS_PROVIDERS')) \define('SHARE_BUTTONS_PROVIDERS', 'Facebook
Twitter
Reddit
LinkedIn
Pinterest');
if (!\defined('IMAGE_ALLOW_EXTERNAL_SOURCE')) \define('IMAGE_ALLOW_EXTERNAL_SOURCE', 0);
if (!\defined('IMAGE_EXTERNAL_SOURCE_WHITELIST')) \define('IMAGE_EXTERNAL_SOURCE_WHITELIST', '');
if (!\defined('MESSAGE_FORCE_SECURE_IMAGES')) \define('MESSAGE_FORCE_SECURE_IMAGES', 0);
if (!\defined('MODULE_IMAGE_PROXY')) \define('MODULE_IMAGE_PROXY', 0);
if (!\defined('IMAGE_PROXY_INSECURE_ONLY')) \define('IMAGE_PROXY_INSECURE_ONLY', 0);
if (!\defined('IMAGE_PROXY_ENABLE_PRUNE')) \define('IMAGE_PROXY_ENABLE_PRUNE', 1);
if (!\defined('IMAGE_PROXY_EXPIRATION')) \define('IMAGE_PROXY_EXPIRATION', 14);
if (!\defined('IMAGE_PROXY_HOST_WHITELIST')) \define('IMAGE_PROXY_HOST_WHITELIST', '');
if (!\defined('MODULE_URL_UNFURLING')) \define('MODULE_URL_UNFURLING', 1);
if (!\defined('FORMATTING_REMOVE_COLOR')) \define('FORMATTING_REMOVE_COLOR', 1);
if (!\defined('FORMATTING_REMOVE_FONT')) \define('FORMATTING_REMOVE_FONT', 1);
if (!\defined('FORMATTING_REMOVE_SIZE')) \define('FORMATTING_REMOVE_SIZE', 1);
if (!\defined('CENSORED_WORDS')) \define('CENSORED_WORDS', '');
if (!\defined('PASSWORD_MIN_SCORE')) \define('PASSWORD_MIN_SCORE', '1');
if (!\defined('REGISTER_FORBIDDEN_USERNAMES')) \define('REGISTER_FORBIDDEN_USERNAMES', '');
if (!\defined('REGISTER_FORBIDDEN_EMAILS')) \define('REGISTER_FORBIDDEN_EMAILS', '');
if (!\defined('REGISTER_ALLOWED_EMAILS')) \define('REGISTER_ALLOWED_EMAILS', '');
if (!\defined('FORCE_LOGIN')) \define('FORCE_LOGIN', 0);
if (!\defined('REGISTER_DISABLED')) \define('REGISTER_DISABLED', 0);
if (!\defined('REGISTER_ENABLE_DISCLAIMER')) \define('REGISTER_ENABLE_DISCLAIMER', 1);
if (!\defined('REGISTER_ACTIVATION_METHOD')) \define('REGISTER_ACTIVATION_METHOD', '1');
if (!\defined('REGISTER_ANTISPAM_ACTION')) \define('REGISTER_ANTISPAM_ACTION', 'disable');
if (!\defined('REGISTER_USERNAME_MIN_LENGTH')) \define('REGISTER_USERNAME_MIN_LENGTH', 3);
if (!\defined('REGISTER_USERNAME_MAX_LENGTH')) \define('REGISTER_USERNAME_MAX_LENGTH', 25);
if (!\defined('REGISTER_USERNAME_FORCE_ASCII')) \define('REGISTER_USERNAME_FORCE_ASCII', '2');
if (!\defined('REGISTER_MIN_USER_AGE')) \define('REGISTER_MIN_USER_AGE', 0);
if (!\defined('GITHUB_PUBLIC_KEY')) \define('GITHUB_PUBLIC_KEY', '');
if (!\defined('GITHUB_PRIVATE_KEY')) \define('GITHUB_PRIVATE_KEY', '');
if (!\defined('TWITTER_PUBLIC_KEY')) \define('TWITTER_PUBLIC_KEY', '');
if (!\defined('TWITTER_PRIVATE_KEY')) \define('TWITTER_PRIVATE_KEY', '');
if (!\defined('FACEBOOK_PUBLIC_KEY')) \define('FACEBOOK_PUBLIC_KEY', '');
if (!\defined('FACEBOOK_PRIVATE_KEY')) \define('FACEBOOK_PRIVATE_KEY', '');
if (!\defined('GOOGLE_PUBLIC_KEY')) \define('GOOGLE_PUBLIC_KEY', '');
if (!\defined('GOOGLE_PRIVATE_KEY')) \define('GOOGLE_PRIVATE_KEY', '');
if (!\defined('AVATAR_DEFAULT_TYPE')) \define('AVATAR_DEFAULT_TYPE', 'initials');
if (!\defined('SIGNATURE_MAX_IMAGE_HEIGHT')) \define('SIGNATURE_MAX_IMAGE_HEIGHT', 150);
if (!\defined('USER_TITLE_MAX_LENGTH')) \define('USER_TITLE_MAX_LENGTH', 25);
if (!\defined('USER_FORBIDDEN_TITLES')) \define('USER_FORBIDDEN_TITLES', '');
if (!\defined('PROFILE_SHOW_OLD_USERNAME')) \define('PROFILE_SHOW_OLD_USERNAME', 182);
if (!\defined('PROFILE_ENABLE_VISITORS')) \define('PROFILE_ENABLE_VISITORS', 1);
if (!\defined('MEMBERS_LIST_USERS_PER_PAGE')) \define('MEMBERS_LIST_USERS_PER_PAGE', 30);
if (!\defined('MEMBERS_LIST_DEFAULT_SORT_FIELD')) \define('MEMBERS_LIST_DEFAULT_SORT_FIELD', 'username');
if (!\defined('MEMBERS_LIST_DEFAULT_SORT_ORDER')) \define('MEMBERS_LIST_DEFAULT_SORT_ORDER', 'DESC');
if (!\defined('USERS_ONLINE_SHOW_GUESTS')) \define('USERS_ONLINE_SHOW_GUESTS', 1);
if (!\defined('USERS_ONLINE_SHOW_ROBOTS')) \define('USERS_ONLINE_SHOW_ROBOTS', 1);
if (!\defined('USERS_ONLINE_DEFAULT_SORT_FIELD')) \define('USERS_ONLINE_DEFAULT_SORT_FIELD', 'lastActivityTime');
if (!\defined('USERS_ONLINE_DEFAULT_SORT_ORDER')) \define('USERS_ONLINE_DEFAULT_SORT_ORDER', 'DESC');
if (!\defined('USERS_ONLINE_PAGE_REFRESH')) \define('USERS_ONLINE_PAGE_REFRESH', 0);
if (!\defined('USERS_ONLINE_ENABLE_LEGEND')) \define('USERS_ONLINE_ENABLE_LEGEND', 1);
if (!\defined('USERS_ONLINE_RECORD')) \define('USERS_ONLINE_RECORD', 0);
if (!\defined('USERS_ONLINE_RECORD_TIME')) \define('USERS_ONLINE_RECORD_TIME', 0);
if (!\defined('USER_CLEANUP_NOTIFICATION_LIFETIME')) \define('USER_CLEANUP_NOTIFICATION_LIFETIME', 31);
if (!\defined('USER_CLEANUP_ACTIVITY_EVENT_LIFETIME')) \define('USER_CLEANUP_ACTIVITY_EVENT_LIFETIME', 60);
if (!\defined('USER_CLEANUP_PROFILE_VISITOR_LIFETIME')) \define('USER_CLEANUP_PROFILE_VISITOR_LIFETIME', 60);
if (!\defined('LIKE_SHOW_SUMMARY')) \define('LIKE_SHOW_SUMMARY', 0);
if (!\defined('MESSAGE_SIDEBAR_ENABLE_ONLINE_STATUS')) \define('MESSAGE_SIDEBAR_ENABLE_ONLINE_STATUS', 1);
if (!\defined('MESSAGE_SIDEBAR_ENABLE_LIKES_RECEIVED')) \define('MESSAGE_SIDEBAR_ENABLE_LIKES_RECEIVED', 1);
if (!\defined('MESSAGE_SIDEBAR_ENABLE_ACTIVITY_POINTS')) \define('MESSAGE_SIDEBAR_ENABLE_ACTIVITY_POINTS', 0);
if (!\defined('MESSAGE_SIDEBAR_ENABLE_TROPHY_POINTS')) \define('MESSAGE_SIDEBAR_ENABLE_TROPHY_POINTS', 1);
if (!\defined('MESSAGE_SIDEBAR_ENABLE_ARTICLES')) \define('MESSAGE_SIDEBAR_ENABLE_ARTICLES', 1);
if (!\defined('MESSAGE_SIDEBAR_USER_OPTIONS')) \define('MESSAGE_SIDEBAR_USER_OPTIONS', '');
if (!\defined('TAGGING_MAX_TAG_LENGTH')) \define('TAGGING_MAX_TAG_LENGTH', 30);
if (!\defined('MESSAGE_MAX_QUOTE_DEPTH')) \define('MESSAGE_MAX_QUOTE_DEPTH', 1);
if (!\defined('MESSAGE_ENABLE_TOC')) \define('MESSAGE_ENABLE_TOC', 1);
if (!\defined('MESSAGE_PUBLIC_HIGHLIGHTERS')) \define('MESSAGE_PUBLIC_HIGHLIGHTERS', 'c
cpp
csharp
css
go
html
java
javascript
json
php
python
ruby
rust
sql
typescript
xml
yaml');
if (!\defined('MESSAGE_ENABLE_USER_CONSENT')) \define('MESSAGE_ENABLE_USER_CONSENT', 1);
if (!\defined('MODIFICATION_LOG_EXPIRATION')) \define('MODIFICATION_LOG_EXPIRATION', 0);
if (!\defined('SEARCH_RESULTS_PER_PAGE')) \define('SEARCH_RESULTS_PER_PAGE', 20);
if (!\defined('SEARCH_DEFAULT_SORT_FIELD')) \define('SEARCH_DEFAULT_SORT_FIELD', 'time');
if (!\defined('SEARCH_DEFAULT_SORT_ORDER')) \define('SEARCH_DEFAULT_SORT_ORDER', 'DESC');
if (!\defined('SEARCH_MAX_COMBINED_TAGS')) \define('SEARCH_MAX_COMBINED_TAGS', 3);
if (!\defined('SEARCH_ENABLE_PAGES')) \define('SEARCH_ENABLE_PAGES', 1);
if (!\defined('SEARCH_ENABLE_ARTICLES')) \define('SEARCH_ENABLE_ARTICLES', 1);
if (!\defined('POLL_MAX_OPTIONS')) \define('POLL_MAX_OPTIONS', 20);
if (!\defined('POLL_FULL_WIDTH')) \define('POLL_FULL_WIDTH', 0);
if (!\defined('MODULE_CONTACT_FORM')) \define('MODULE_CONTACT_FORM', 0);
if (!\defined('CONTACT_FORM_ENABLE_ATTACHMENTS')) \define('CONTACT_FORM_ENABLE_ATTACHMENTS', 0);
if (!\defined('CONTACT_FORM_PRUNE_ATTACHMENTS')) \define('CONTACT_FORM_PRUNE_ATTACHMENTS', 180);
if (!\defined('MEDIA_SMALL_THUMBNAIL_WIDTH')) \define('MEDIA_SMALL_THUMBNAIL_WIDTH', 280);
if (!\defined('MEDIA_SMALL_THUMBNAIL_HEIGHT')) \define('MEDIA_SMALL_THUMBNAIL_HEIGHT', 210);
if (!\defined('MEDIA_SMALL_THUMBNAIL_RETAIN_DIMENSIONS')) \define('MEDIA_SMALL_THUMBNAIL_RETAIN_DIMENSIONS', 1);
if (!\defined('MEDIA_MEDIUM_THUMBNAIL_WIDTH')) \define('MEDIA_MEDIUM_THUMBNAIL_WIDTH', 560);
if (!\defined('MEDIA_MEDIUM_THUMBNAIL_HEIGHT')) \define('MEDIA_MEDIUM_THUMBNAIL_HEIGHT', 420);
if (!\defined('MEDIA_MEDIUM_THUMBNAIL_RETAIN_DIMENSIONS')) \define('MEDIA_MEDIUM_THUMBNAIL_RETAIN_DIMENSIONS', 1);
if (!\defined('MEDIA_LARGE_THUMBNAIL_WIDTH')) \define('MEDIA_LARGE_THUMBNAIL_WIDTH', 1200);
if (!\defined('MEDIA_LARGE_THUMBNAIL_HEIGHT')) \define('MEDIA_LARGE_THUMBNAIL_HEIGHT', 900);
if (!\defined('MEDIA_LARGE_THUMBNAIL_RETAIN_DIMENSIONS')) \define('MEDIA_LARGE_THUMBNAIL_RETAIN_DIMENSIONS', 1);
if (!\defined('ARTICLE_SHOW_ABOUT_AUTHOR')) \define('ARTICLE_SHOW_ABOUT_AUTHOR', 0);
if (!\defined('ARTICLE_ENABLE_COMMENTS_DEFAULT_VALUE')) \define('ARTICLE_ENABLE_COMMENTS_DEFAULT_VALUE', 1);
if (!\defined('ARTICLE_ENABLE_LIKE')) \define('ARTICLE_ENABLE_LIKE', 1);
if (!\defined('ARTICLES_PER_PAGE')) \define('ARTICLES_PER_PAGE', 20);
if (!\defined('ARTICLE_RELATED_ARTICLES')) \define('ARTICLE_RELATED_ARTICLES', 3);
if (!\defined('ARTICLE_RELATED_ARTICLES_MATCH_THRESHOLD')) \define('ARTICLE_RELATED_ARTICLES_MATCH_THRESHOLD', 50);
if (!\defined('ARTICLE_SORT_ORDER')) \define('ARTICLE_SORT_ORDER', 'DESC');
if (!\defined('LOG_MISSING_LANGUAGE_ITEMS')) \define('LOG_MISSING_LANGUAGE_ITEMS', 0);
if (!\defined('WCF_OPTION_INC_PHP_SUCCESS')) \define('WCF_OPTION_INC_PHP_SUCCESS', true);
