<?php
/**
 * WoltLab Suite
 * Template: textOptionType
 * Compiled at: Thu, 08 Jan 2026 08:26:35 +0000
 * 
 * DO NOT EDIT THIS FILE
 */
$this->v['tpl']['template'] = 'textOptionType';
?>
<input type="<?=wcf\util\StringUtil::encodeHTML($this->v['inputType']);?>" id="<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>" name="values[<?=wcf\util\StringUtil::encodeHTML($this->v['option']->optionName);?>]" value="<?=wcf\util\StringUtil::encodeHTML($this->v['value']);?>"<?php if ($this->v['inputClass']) { ?> class="<?=wcf\util\StringUtil::encodeHTML($this->v['inputClass']);?>"<?php } ?><?php if ($this->v['inputType'] == 'password') { ?> autocomplete="new-password"<?php } elseif ($this->v['option']->disableAutocomplete) { ?> autocomplete="off"<?php } ?>>